mongodb/mongo-php-library

src/Collection.php
https://jira.mongodb.org/browse/PHPLIB-87
=> PHPLIB-87: Remove manual bsonSerialize() call

src/Exception/Exception.php, src/Exception/InvalidArgumentException.php, src/Exception/RuntimeException.php, src/Exception/UnexpectedValueException.php
https://jira.mongodb.org/browse/PHPLIB-83
=> PHPLIB-83: Extend driver exceptions

src/Collection.php
https://jira.mongodb.org/browse/PHPLIB-105
=> PHPLIB-105: Remove Collection::VERSION constant

src/BulkWriteResult.php, src/Model/IndexInput.php, tests/Collection/BulkWriteFunctionalTest.php, tests/Model/IndexInputTest.php
https://jira.mongodb.org/browse/PHPLIB-108
=> PHPLIB-108: Use MongoDB\BSON namespace prefix

.travis.yml, src/Collection.php, src/Operation/BulkWrite.php, src/Operation/CreateCollection.php, src/Operation/CreateIndexes.php, src/Operation/Delete.php, src/Operation/DeleteMany.php, src/Operation/DeleteOne.php, src/Operation/InsertMany.php, src/Operation/InsertOne.php, src/Operation/ReplaceOne.php, src/Operation/Update.php, src/Operation/UpdateMany.php, src/Operation/UpdateOne.php, tests/Collection/BulkWriteFunctionalTest.php, tests/Operation/BulkWriteTest.php, tests/Operation/DeleteTest.php, tests/Operation/InsertManyTest.php, tests/Operation/InsertOneTest.php, tests/Operation/ReplaceOneTest.php, tests/Operation/TestCase.php, tests/Operation/UpdateManyTest.php, tests/Operation/UpdateOneTest.php, tests/Operation/UpdateTest.php
https://jira.mongodb.org/browse/PHPLIB-109
=> PHPLIB-109: Write operation classes

.travis.yml, composer.json
https://jira.mongodb.org/browse/PHPLIB-120
=> PHPLIB-120: Require PHP 5.4+

src/Client.php, tests/ClientTest.php
* https://jira.mongodb.org/browse/PHPLIB-90
* https://jira.mongodb.org/browse/PHPLIB-143
=> PHPLIB-90, PHPLIB-143: Client::__toString() and default URI

src/Client.php, src/Collection.php, src/Database.php, tests/ClientTest.php, tests/Collection/CollectionFunctionalTest.php, tests/Database/DatabaseFunctionalTest.php, tests/Operation/TestCase.php, tests/TestCase.php
* https://jira.mongodb.org/browse/PHPLIB-144
* https://jira.mongodb.org/browse/PHPLIB-145
* https://jira.mongodb.org/browse/PHPLIB-49
=> PHPLIB-144, PHPLIB-145: Options arrays and debug handlers

src/Operation/FindOne.php
https://jira.mongodb.org/browse/PHPLIB-152
=> PHPLIB-152: Use 1 instead of -1 for FindOne limit

src/Client.php, tests/ClientTest.php
https://jira.mongodb.org/browse/PHPLIB-151
This reverts commit 451f72c478a70e90d723da23a8eb1fd54169f735.
=> Revert "PHPLIB-151: Use IPv4 localhost address for default URI"

.travis.yml, composer.json
https://jira.mongodb.org/browse/PHPLIB-132
=> PHPLIB-132: Bump ext-mongodb dependency to >=1.1.0

src/Operation/CreateCollection.php, tests/Operation/CreateCollectionTest.php
https://jira.mongodb.org/browse/PHPLIB-135
=> PHPLIB-135: Support validator options for CreateCollection

src/Operation/BulkWrite.php, src/Operation/InsertMany.php, src/Operation/InsertOne.php, src/functions.php, tests/Operation/BulkWriteFunctionalTest.php, tests/Operation/InsertManyFunctionalTest.php, tests/Operation/InsertOneFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-157
Fixes #85
=> PHPLIB-157: Improve _id extraction for Serializable objects

src/Model/BSONArray.php, src/Model/BSONDocument.php, tests/Model/BSONArrayTest.php, tests/Model/BSONDocumentTest.php
https://jira.mongodb.org/browse/PHPLIB-163
=> PHPLIB-163: __set_state() for BSON array and document models

src/Client.php, src/Database.php, tests/ClientTest.php, tests/Database/DatabaseFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-162
=> PHPLIB-162: Support database and collection selection via __get()

src/Client.php, src/Collection.php, src/Database.php, src/Operation/DropCollection.php, src/Operation/DropDatabase.php, src/Operation/DropIndexes.php, tests/Collection/CollectionFunctionalTest.php, tests/FunctionalTestCase.php, tests/Operation/DropCollectionTest.php, tests/Operation/DropDatabaseTest.php
https://jira.mongodb.org/browse/PHPLIB-164
=> PHPLIB-164: Use type map for command responses

src/Client.php, src/Collection.php, src/Database.php, tests/Collection/CollectionFunctionalTest.php, tests/Collection/CrudSpec/AggregateFunctionalTest.php, tests/Collection/FunctionalTestCase.php, tests/Database/DatabaseFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-165
=> PHPLIB-165: Take explicit db/coll name args in Collection ctor

src/Database.php, src/Operation/CreateCollection.php, tests/Operation/CreateCollectionTest.php
https://jira.mongodb.org/browse/PHPLIB-164
=> PHPLIB-164: CreateCollection should use type map

.travis.yml, composer.json
Incorporates a commit from https://github.com/mongodb/mongo-php-library/pull/158.
=> Add PHPUnit development dependency

src/GridFS/Bucket.php, src/GridFS/WritableStream.php
https://jira.mongodb.org/browse/PHPLIB-197
=> PHPLIB-197: Support non-ObjectID identifiers for GridFS files

src/GridFS/Bucket.php, src/GridFS/ReadableStream.php, src/GridFS/WritableStream.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/WritableStreamFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-202
This also improves test coverage for downloadToStreamByName().
=> PHPLIB-202: Use stream_copy_to_stream() in Bucket upload/download methods

src/GridFS/Bucket.php, tests/GridFS/BucketFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-198
=> PHPLIB-198: Support readConcern option for GridFS collections

src/GridFS/StreamWrapper.php, src/GridFS/WritableStream.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/SpecFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-199
=> PHPLIB-199: Convert Exceptions to E_USER_WARNING in StreamWrapper

src/Operation/FindAndModify.php, src/functions.php, tests/FunctionsTest.php
https://jira.mongodb.org/browse/PHPLIB-219
=> PHPLIB-219: Fix BSON serialization of findAndModify write concern

src/Client.php
https://jira.mongodb.org/browse/PHPLIB-193
=> PHPLIB-193: Do not pass typeMap Client option to Manager

src/GridFS/WritableStream.php
https://jira.mongodb.org/browse/PHPLIB-222
=> PHPLIB-222: Pass UTCDateTime constructor argument as integer

src/Client.php, tests/ClientTest.php
https://jira.mongodb.org/browse/PHPLIB-220
=> PHPLIB-220: Default Client URI to "mongodb://127.0.0.1/"

src/Client.php, src/Collection.php, src/Database.php, src/Exception/UnsupportedException.php, src/Operation/Aggregate.php, src/Operation/CreateCollection.php, src/Operation/CreateIndexes.php, src/Operation/Distinct.php, src/Operation/DropCollection.php, src/Operation/DropDatabase.php, src/Operation/DropIndexes.php, src/Operation/Find.php, src/Operation/FindAndModify.php, tests/Operation/AggregateTest.php, tests/Operation/CreateCollectionTest.php, tests/Operation/CreateIndexesTest.php, tests/Operation/DropCollectionTest.php, tests/Operation/DropDatabaseTest.php, tests/Operation/DropIndexesTest.php
https://jira.mongodb.org/browse/PHPLIB-200
Related questions in:
* https://jira.mongodb.org/browse/SPEC-494
* https://jira.mongodb.org/browse/SPEC-695
=> PHPLIB-200: Support writeConcern option for commands that write

src/Operation/Find.php
https://jira.mongodb.org/browse/PHPLIB-224
=> PHPLIB-224: Translate Find options to canonical Query options

src/GridFS/StreamWrapper.php, src/GridFS/WritableStream.php, tests/GridFS/StreamWrapperFunctionalTest.php, tests/GridFS/WritableStreamFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-248
https://jira.mongodb.org/browse/PHPLIB-249
https://jira.mongodb.org/browse/PHPLIB-250
https://jira.mongodb.org/browse/PHPLIB-251
=> PHPLIB-248, 249, 250, 251: GridFS stat improvements

docs/includes/apiargs-MongoDBCollection-common-option.yaml, docs/includes/extracts-note.yaml, docs/reference/method/MongoDBCollection-count.txt, docs/reference/method/MongoDBCollection-deleteMany.txt, docs/reference/method/MongoDBCollection-deleteOne.txt, docs/reference/method/MongoDBCollection-distinct.txt, docs/reference/method/MongoDBCollection-find.txt, docs/reference/method/MongoDBCollection-findOne.txt, docs/reference/method/MongoDBCollection-findOneAndDelete.txt, docs/reference/method/MongoDBCollection-findOneAndReplace.txt, docs/reference/method/MongoDBCollection-findOneAndUpdate.txt, docs/reference/method/MongoDBCollection-replaceOne.txt, docs/reference/method/MongoDBCollection-updateMany.txt, docs/reference/method/MongoDBCollection-updateOne.txt, docs/reference/method/MongoDBGridFSBucket-find.txt, docs/reference/method/MongoDBGridFSBucket-findOne.txt, docs/tutorial/crud.txt
https://jira.mongodb.org/browse/PHPLIB-208
Related to: https://github.com/mongodb/mongo-php-library/issues/217
=> PHPLIB-208: Remind users about BSON comparison behavior

docs/tutorial.txt, docs/tutorial/decimal128.txt
https://jira.mongodb.org/browse/PHPLIB-218
=> PHPLIB-218: Tutorial for Decimal128

docs/reference/method/MongoDBCollection-findOneAndUpdate.txt, docs/tutorial.txt, docs/tutorial/collation.txt
https://jira.mongodb.org/browse/PHPLIB-212
=> PHPLIB-212: Tutorial for collation

src/GridFS/ReadableStream.php, src/GridFS/StreamWrapper.php, src/GridFS/WritableStream.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/FunctionalTestCase.php, tests/GridFS/StreamWrapperFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-213
=> PHPLIB-213: Support seeking and partial file retrieval for GridFS streams

docs/tutorial/crud.txt
https://jira.mongodb.org/browse/PHPLIB-243
Related: https://github.com/mongodb/mongo-php-driver/issues/186
=> PHPLIB-243: Add regex query examples to CRUD tutorial

docs/reference/method/MongoDBClient__construct.txt
https://jira.mongodb.org/browse/PHPLIB-257
=> PHPLIB-257: Document that connections are initialized lazily

src/Collection.php
https://jira.mongodb.org/browse/PHPLIB-260
=> PHPLIB-260: Remove duplicate server selection in Collection::findOne()

tests/DocumentationExamplesTest.php, tests/TestCase.php
https://jira.mongodb.org/browse/PHPLIB-263
=> PHPLIB-263: Documentation examples for shell commands

docs/includes/apiargs-MongoDBGridFSBucket-common-option.yaml, docs/includes/extracts-note.yaml, docs/reference/bson.txt, docs/reference/method/MongoDBBulkWriteResult-getInsertedIds.txt, docs/reference/method/MongoDBBulkWriteResult-getUpsertedIds.txt, docs/reference/method/MongoDBCollection-find.txt, docs/reference/method/MongoDBCollection-findOne.txt, docs/reference/method/MongoDBCollection-findOneAndDelete.txt, docs/reference/method/MongoDBCollection-findOneAndReplace.txt, docs/reference/method/MongoDBCollection-findOneAndUpdate.txt, docs/reference/method/MongoDBCollection-insertMany.txt, docs/reference/method/MongoDBCollection-insertOne.txt, docs/reference/method/MongoDBGridFSBucket-uploadFromStream.txt, docs/reference/method/MongoDBInsertManyResult-getInsertedIds.txt, docs/reference/method/MongoDBInsertOneResult-getInsertedId.txt, docs/reference/method/MongoDBUpdateResult-getUpsertedId.txt, docs/tutorial/commands.txt, docs/tutorial/crud.txt, src/BulkWriteResult.php, src/InsertManyResult.php, src/InsertOneResult.php, src/UpdateResult.php, tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/SpecFunctionalTest.php, tests/Operation/MapReduceTest.php
https://jira.mongodb.org/browse/PHPLIB-280
=> PHPLIB-280: Rename ObjectID to ObjectId

docs/reference/class/MongoDBGridFSBucket.txt, docs/reference/method/MongoDBGridFSBucket-getChunkSizeBytes.txt, src/GridFS/Bucket.php, tests/GridFS/BucketFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-272
=> PHPLIB-272: Implement chunkSizeBytes accessor for Bucket class

docs/reference/class/MongoDBGridFSBucket.txt, docs/reference/method/MongoDBGridFSBucket-getChunksCollection.txt, docs/reference/method/MongoDBGridFSBucket-getFilesCollection.txt, src/GridFS/Bucket.php, src/GridFS/CollectionWrapper.php, tests/GridFS/BucketFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-258
Fixes https://github.com/mongodb/mongo-php-library/issues/332
=> PHPLIB-258: Accessors for GridFS files and chunks collections

docs/includes/apiargs-MongoDBCollection-method-count-option.yaml, src/Operation/Count.php, tests/Operation/CountFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-285
=> PHPLIB-285: Do not convert count's hint document to a string

docs/includes/apiargs-MongoDBCollection-method-find-option.yaml, docs/includes/apiargs-MongoDBCollection-method-findOne-option.yaml, src/Operation/Find.php, src/Operation/FindOne.php, tests/Operation/FindFunctionalTest.php, tests/Operation/FindTest.php
https://jira.mongodb.org/browse/PHPLIB-264
=> PHPLIB-264: Hint and modifier options for Find and FindOne

docs/includes/apiargs-MongoDBCollection-method-find-option.yaml, docs/includes/apiargs-common-option.yaml, src/Operation/Find.php, tests/Operation/FindFunctionalTest.php, tests/Operation/FindTest.php
https://jira.mongodb.org/browse/PHPLIB-268
=> PHPLIB-268 Add option maxAwaitTimeMS on getMore commands

docs/includes/apiargs-MongoDBCollection-method-find-option.yaml
https://jira.mongodb.org/browse/PHPLIB-288
=> PHPLIB-288 Document how to specify singleBatch option with Find

tests/Model/TypeMapArrayIteratorTest.php
This class was originally added in PHPLIB-112
=> Test for internal TypeMapArrayIterator class

docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, src/Operation/Aggregate.php, tests/Operation/AggregateTest.php
https://jira.mongodb.org/browse/PHPLIB-266
=> PHPLIB-266 Support passing index hint to aggregations

docs/includes/apiargs-MongoDBCollection-method-dropIndex-option.yaml, docs/includes/apiargs-MongoDBCollection-method-dropIndexes-option.yaml, src/Operation/DropIndexes.php, tests/Operation/DropIndexesTest.php
https://jira.mongodb.org/browse/PHPLIB-297
=> PHPLIB-297 Support maxTimeMS option for DropIndexes operation

tests/DocumentationExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-289
=> [WAIT] PHPLIB-289 ChangeStreams Examples for Docs

tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php
https://jira.mongodb.org/browse/PHPLIB-300
=> PHPLIB-300 Test suite should not query featureCompatibilityVersion for server versions before 3.4

composer.json
@kvwalker: just want to confirm that this is your preferred email address (pulled it from GitHub). This info will end up being rendered on https://packagist.org/packages/mongodb/mongodb.
=> Swap @bjori for @kvwalker

src/Collection.php
https://jira.mongodb.org/browse/PHPLIB-314
=> PHPLIB-314: Make mapReduce inline check more robust

docs/tutorial.txt, docs/tutorial/tailable-cursor.txt
https://jira.mongodb.org/browse/PHPLIB-267
=> PHPLIB-267 Document example of tailable cursor iteration

src/GridFS/WritableStream.php, tests/GridFS/StreamWrapperFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-306
=> PHPLIB-306: Set GridFS uploadDate at completion time

.travis.yml, composer.json, docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, docs/includes/apiargs-MongoDBCollection-method-mapReduce-option.yaml, src/Collection.php, src/Operation/Aggregate.php, src/Operation/Count.php, src/Operation/CreateCollection.php, src/Operation/CreateIndexes.php, src/Operation/Distinct.php, src/Operation/DropCollection.php, src/Operation/DropDatabase.php, src/Operation/DropIndexes.php, src/Operation/FindAndModify.php, src/Operation/MapReduce.php, src/functions.php, tests/FunctionsTest.php
https://jira.mongodb.org/browse/PHPLIB-316
Please read through carefully. There was quite a bit of code copypasta involved in this.
=> PHPLIB-316: Migrate operations to use read and write command methods

tests/DocumentationExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-310
=> PHPLIB-310: Add pipeline stage to ChangeStreams example for Docs

src/Operation/MapReduce.php, tests/Collection/CollectionFunctionalTest.php, tests/Operation/MapReduceFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-315
=> PHPLIB-315: Remove default for mapReduce verbose option

src/Model/TypeMapArrayIterator.php, tests/Model/TypeMapArrayIteratorTest.php
https://jira.mongodb.org/browse/PHPLIB-292
=> PHPLIB-292: Apply type map to offsetGet and throw exceptions for mutate methods in TypeMapArrayIterator

docs/includes/apiargs-MongoDBClient-method-startSession-option.yaml, docs/reference/class/MongoDBClient.txt, docs/reference/method/MongoDBClient-startSession.txt, src/Client.php, tests/ClientFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-303
=> PHPLIB-303: Implement MongoDB\Client::startSession()

docs/includes/apiargs-MongoDBCollection-method-watch-option.yaml, src/ChangeStream.php, src/Exception/ResumeTokenException.php, src/Operation/Watch.php, tests/Operation/WatchFunctionalTest.php, tests/Operation/WatchTest.php
https://jira.mongodb.org/browse/PHPLIB-323
=> PHPLIB-323: Support typeMap option for change streams

docs/reference.txt, docs/reference/method/MongoDBChangeStream-current.txt, docs/reference/method/MongoDBChangeStream-getCursorId.txt, docs/reference/method/MongoDBChangeStream-key.txt, docs/reference/method/MongoDBChangeStream-next.txt, docs/reference/method/MongoDBChangeStream-rewind.txt, docs/reference/method/MongoDBChangeStream-valid.txt, docs/reference/method/MongoDBCollection-mapReduce.txt, docs/reference/method/MongoDBMapReduceResult-getCounts.txt, docs/reference/method/MongoDBMapReduceResult-getExecutionTimeMS.txt, docs/reference/method/MongoDBMapReduceResult-getIterator.txt, docs/reference/method/MongoDBMapReduceResult-getTiming.txt, docs/reference/result-classes.txt, docs/tutorial.txt, docs/tutorial/tailable-cursor.txt, src/ChangeStream.php
https://jira.mongodb.org/browse/PHPLIB-328
=> Document ChangeStream and MapReduceResult classes

src/GridFS/ReadableStream.php, tests/GridFS/ReadableStreamFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-252
=> PHPLIB-252: Allow seeking to advance chunk iterator instead of always re-querying

src/Collection.php, src/Operation/Aggregate.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/AggregateTest.php
https://jira.mongodb.org/browse/PHPLIB-333
=> PHPLIB-333: Allow typeMap option when useCursor is false for Aggregate

docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, src/Operation/Aggregate.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/AggregateTest.php
https://jira.mongodb.org/browse/PHPLIB-172
=> PHPLIB-172: Support explain option for aggregate command

tests/Operation/WatchFunctionalTest.php
This addresses a few issues I noticed while reviewing #510.
=> Improvements to WatchFunctionalTest

src/ChangeStream.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-327
https://jira.mongodb.org/browse/PHPLIB-335
=> PHPLIB-327, PHPLIB-335: ChangeStream::next() key increment fixes

src/Collection.php, tests/Collection/CollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-336
=> PHPLIB-336: Split out session command option in createIndex()

docs/includes/apiargs-MongoDBDatabase-method-modifyCollection-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-modifyCollection-param.yaml, docs/includes/apiargs-common-param.yaml, docs/reference/class/MongoDBDatabase.txt, docs/reference/method/MongoDBDatabase-modifyCollection.txt, src/Database.php, src/Operation/ModifyCollection.php, tests/Database/DatabaseFunctionalTest.php, tests/Operation/ModifyCollectionFunctionalTest.php, tests/Operation/ModifyCollectionTest.php
https://jira.mongodb.org/browse/PHPLIB-66
=> PHPLIB-66: Wrapper method for collMod command

docs/includes/apiargs-MongoDBCollection-method-explain-option.yaml, docs/includes/apiargs-MongoDBCollection-method-explain-param.yaml, docs/reference/class/MongoDBCollection.txt, docs/reference/method/MongoDBCollection-explain.txt, src/Collection.php, tests/Collection/CollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-332
=> PHPLIB-332: Create explain helper on Collection class

docs/includes/apiargs-MongoDBCollection-method-dropIndex-param.yaml, src/Collection.php, src/Model/IndexInfo.php, tests/Operation/DropIndexesFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-84
=> PHPLIB-84: Allow Collection::dropIndex() to accept an IndexInfo object

docs/reference/method/MongoDBModelCollectionInfo-getCappedMax.txt, docs/reference/method/MongoDBModelCollectionInfo-getCappedSize.txt, docs/reference/method/MongoDBModelCollectionInfo-getName.txt, docs/reference/method/MongoDBModelCollectionInfo-getOptions.txt, docs/reference/method/MongoDBModelCollectionInfo-isCapped.txt, docs/reference/method/MongoDBModelDatabaseInfo-getName.txt, docs/reference/method/MongoDBModelDatabaseInfo-getSizeOnDisk.txt, docs/reference/method/MongoDBModelDatabaseInfo-isEmpty.txt, docs/reference/method/MongoDBModelIndexInfo-getKey.txt, docs/reference/method/MongoDBModelIndexInfo-getName.txt, docs/reference/method/MongoDBModelIndexInfo-getNamespace.txt, docs/reference/method/MongoDBModelIndexInfo-getVersion.txt, docs/reference/method/MongoDBModelIndexInfo-isSparse.txt, docs/reference/method/MongoDBModelIndexInfo-isTtl.txt, docs/reference/method/MongoDBModelIndexInfo-isUnique.txt
I originally merged this PR into master before realizing that it should have been merged into v1.3. I reverted the incorrect merge into master and this is the PR to merge correctly into v1.3.
https://jira.mongodb.org/browse/PHPLIB-278
=> PHPLIB-278: Add examples for calling methods on database, collection, and index models

src/Model/CollectionInfo.php, src/Model/DatabaseInfo.php, tests/Model/CollectionInfoTest.php, tests/Model/DatabaseInfoTest.php, tests/Operation/ListCollectionsFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-226
=> PHPLIB-226: Implement ArrayAccess for CollectionInfo and DatabaseInfo

docs/includes/apiargs-MongoDBDatabase-method-createCollection-option.yaml, src/Operation/CreateCollection.php, tests/Operation/CreateCollectionTest.php, tests/TestCase.php
https://jira.mongodb.org/browse/PHPLIB-346
=> PHPLIB-346: Deprecate autoIndexId option for CreateCollection

docs/includes/apiargs-MongoDBCollection-method-find-option.yaml, src/Operation/Find.php, tests/Operation/FindTest.php
https://jira.mongodb.org/browse/PHPLIB-339
=> PHPLIB-339: Deprecate snapshot option

docs/includes/apiargs-MongoDBDatabase-method-selectGridFSBucket-option.yaml, docs/includes/apiargs-MongoDBGridFSBucket-method-construct-option.yaml, docs/includes/apiargs-MongoDBGridFSBucket-method-openUploadStream-option.yaml, docs/includes/apiargs-MongoDBGridFSBucket-method-uploadFromStream-option.yaml
=> PHPLIB-319: Fix indentation in disableMD5 option doc snippets

src/Model/BSONIterator.php
#526 introduced a class constant, which we really don't need to expose as part of our public API.
=> Use private static member for internal constant

src/Operation/Watch.php
https://jira.mongodb.org/browse/PHPLIB-361
=> PHPLIB-361: Disable causalConsistency for implicit change stream session

docs/reference/method/MongoDBCollection-countDocuments.txt
https://jira.mongodb.org/browse/PHPLIB-359
=> PHPLIB-359: Alternatives to restricted query operators for countDocuments()

docs/reference/method/MongoDBCollection-count.txt, docs/reference/method/MongoDBCollection-countDocuments.txt, docs/reference/method/MongoDBCollection-estimatedDocumentCount.txt
https://jira.mongodb.org/browse/PHPLIB-354
=> PHPLIB-364: Deprecate count() and elaborate on count method behaviors

src/ChangeStream.php, src/Collection.php, src/Exception/UnsupportedException.php, src/Operation/BulkWrite.php, src/Operation/CountDocuments.php, src/Operation/Find.php
https://scrutinizer-ci.com/g/jmikola/mongo-php-library/inspections/f99cba3a-b40b-44f8-a820-ef2877d1a821/patches
=> Code formatting patches from Scrutinizer CI

tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php
https://jira.mongodb.org/browse/PHPLIB-373
=> PHPLIB-373: Improve logic to skip transaction tests

tests/Collection/CrudSpecFunctionalTest.php, tests/Collection/spec-tests/write/bulkWrite-arrayFilters.json, tests/Collection/spec-tests/write/insertMany.json, tests/Collection/spec-tests/write/updateMany-arrayFilters.json, tests/Collection/spec-tests/write/updateOne-arrayFilters.json
https://jira.mongodb.org/browse/SPEC-1135
https://jira.mongodb.org/browse/SPEC-1136
Spec changes from https://github.com/mongodb/specifications/pull/376 and https://github.com/mongodb/specifications/pull/377.
=> Sync CRUD spec tests for SPEC-1135 and SPEC-1136

src/Operation/Aggregate.php, tests/Collection/CrudSpecFunctionalTest.php, tests/Operation/AggregateFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-398
=> PHPLIB-398: Aggregate with $out should ignore batchSize option

.travis.yml
https://jira.mongodb.org/browse/PHPLIB-412
=> PHPLIB-412: Use distro-specific server binaries

tests/Operation/AggregateFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-431
=> PHPLIB-431: Relax aggregate explain test for 4.2 servers

.travis.yml, composer.json
https://jira.mongodb.org/browse/PHPLIB-429
=> PHPLIB-429: Remove support for PHP 5.5

tests/SpecTests/CommandExpectations.php, tests/SpecTests/CommandMonitoringSpecTest.php, tests/SpecTests/Context.php, tests/SpecTests/DocumentsMatchConstraint.php, tests/SpecTests/DocumentsMatchConstraintTest.php, tests/SpecTests/FunctionalTestCase.php, tests/SpecTests/Operation.php, tests/SpecTests/RetryableWritesSpecTest.php, tests/SpecTests/TransactionsSpecTest.php, tests/SpecTests/command-monitoring/bulkWrite.json, tests/SpecTests/command-monitoring/command.json, tests/SpecTests/command-monitoring/deleteMany.json, tests/SpecTests/command-monitoring/deleteOne.json, tests/SpecTests/command-monitoring/find.json, tests/SpecTests/command-monitoring/insertMany.json, tests/SpecTests/command-monitoring/insertOne.json, tests/SpecTests/command-monitoring/unacknowledgedBulkWrite.json, tests/SpecTests/command-monitoring/updateMany.json, tests/SpecTests/command-monitoring/updateOne.json, tests/bootstrap.php
https://jira.mongodb.org/browse/PHPLIB-410
Spec tests synced with mongodb/specifications@4820c7bad9b06b71f169c0d4b99aba6fbb319243
=> PHPLIB-410: Command Monitoring test runner

tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-446
=> PHPLIB-446: Skip tests that modify resume token for server 4.1.8+

src/ChangeStream.php
https://jira.mongodb.org/browse/PHPLIB-433
=> PHPLIB-433: Check for NonResumableChangeStreamError label

tests/SpecTests/ChangeStreamsSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-416
=>  PHPLIB-416: Remove skip for consecutive resume test

.travis.yml, mongo-orchestration/replica_sets/replicaset-one-node.json, mongo-orchestration/replica_sets/replicaset.json, mongo-orchestration/sharded_clusters/cluster.json, mongo-orchestration/sharded_clusters/cluster_replset.json, mongo-orchestration/standalone/standalone-auth.json, mongo-orchestration/standalone/standalone-ssl.json, mongo-orchestration/standalone/standalone.json
https://jira.mongodb.org/browse/PHPLIB-449
=> PHPLIB-449: Add 4.2.0-rc1 replica set to Travis CI matrix

.travis.yml, tests/SpecTests/ChangeStreamsProseTest.php
https://jira.mongodb.org/browse/PHPLIB-443
=> PHPLIB-443: Check server version before using failCommand

docs/reference/method/MongoDBChangeStream-current.txt, docs/reference/method/MongoDBChangeStream-getCursorId.txt, docs/reference/method/MongoDBChangeStream-getResumeToken.txt, docs/reference/method/MongoDBChangeStream-key.txt, docs/reference/method/MongoDBChangeStream-next.txt, docs/reference/method/MongoDBChangeStream-rewind.txt, docs/reference/method/MongoDBChangeStream-valid.txt, docs/reference/method/MongoDBClient-watch.txt, docs/reference/method/MongoDBCollection-watch.txt, docs/reference/method/MongoDBDatabase-watch.txt, docs/reference/result-classes.txt
https://jira.mongodb.org/browse/PHPLIB-435
=> PHPLIB-435: Document ChangeStream::getResumeToken()

src/Operation/CountDocuments.php, src/Operation/EstimatedDocumentCount.php
https://jira.mongodb.org/browse/PHPLIB-357
=> PHPLIB-357: Refactor CountDocuments and EstimatedDocumentCount Operations to encapsulate a Count/Aggregation Operation

tests/DocumentationExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-474
=> PHPLIB-474: Provide transaction example using new withTransaction API

src/Client.php, src/Collection.php, src/Database.php, src/Operation/Watch.php, src/functions.php, tests/SpecTests/TransactionsSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-473
=> PHPLIB-473: Ensure read concern is inherited for transactions

tests/SpecTests/PrimaryStepDownSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-490
=> PHPLIB-490: Update spec tests for primary stepdown

.gitignore, .travis.yml, composer.json, docs/includes/apiargs-MongoDBClient-method-construct-driverOptions.yaml, src/Client.php, src/Exception/InvalidArgumentException.php, tests/ClientTest.php
https://jira.mongodb.org/browse/PHPLIB-511
=> PHPLIB-511: Handle autoEncryptionOpts in MongoDB\Client

docs/includes/apiargs-MongoDBClient-method-construct-driverOptions.yaml
https://jira.mongodb.org/browse/PHPLIB-521
=> PHPLIB-521: Deprecate obsolete driver options

tests/SpecTests/crud/bulkWrite-arrayFilters.json, tests/SpecTests/crud/bulkWrite-update-hint.json
https://jira.mongodb.org/browse/PHPLIB-533
=> PHPLIB-533: Separate BulkWrite tests by operation

tests/SpecTests/CrudSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-540
=> PHPLIB-540: Ensure that the WriteConcernError "errInfo" object is propagated

docs/includes/apiargs-MongoDBClient-method-listDatabases-option.yaml, src/Operation/ListDatabases.php, tests/Operation/ListDatabasesFunctionalTest.php, tests/Operation/ListDatabasesTest.php
https://jira.mongodb.org/browse/PHPLIB-545
=> PHPLIB-545: Support the authorizedDatabases options for listDatabases

docs/includes/apiargs-MongoDBCollection-method-createIndex-option.yaml, docs/includes/apiargs-MongoDBCollection-method-createIndexes-option.yaml, src/Collection.php, src/Exception/UnsupportedException.php, src/Operation/CreateIndexes.php, tests/Operation/CreateIndexesFunctionalTest.php, tests/Operation/CreateIndexesTest.php
https://jira.mongodb.org/browse/PHPLIB-544
=> PHPLIB-544: Add commitQuorum option to createIndexes

tests/SpecTests/FunctionalTestCase.php
https://jira.mongodb.org/browse/PHPLIB-552
=> PHPLIB-522: sort outcome collection by ID

tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/Context.php, tests/SpecTests/client-side-encryption/tests/aggregate.json, tests/SpecTests/client-side-encryption/tests/basic.json, tests/SpecTests/client-side-encryption/tests/bulk.json, tests/SpecTests/client-side-encryption/tests/bypassAutoEncryption.json, tests/SpecTests/client-side-encryption/tests/count.json, tests/SpecTests/client-side-encryption/tests/countDocuments.json, tests/SpecTests/client-side-encryption/tests/delete.json, tests/SpecTests/client-side-encryption/tests/distinct.json, tests/SpecTests/client-side-encryption/tests/explain.json, tests/SpecTests/client-side-encryption/tests/find.json, tests/SpecTests/client-side-encryption/tests/findOneAndDelete.json, tests/SpecTests/client-side-encryption/tests/findOneAndReplace.json, tests/SpecTests/client-side-encryption/tests/findOneAndUpdate.json, tests/SpecTests/client-side-encryption/tests/getMore.json, tests/SpecTests/client-side-encryption/tests/insert.json, tests/SpecTests/client-side-encryption/tests/keyAltName.json, tests/SpecTests/client-side-encryption/tests/localKMS.json, tests/SpecTests/client-side-encryption/tests/localSchema.json, tests/SpecTests/client-side-encryption/tests/missingKey.json, tests/SpecTests/client-side-encryption/tests/replaceOne.json, tests/SpecTests/client-side-encryption/tests/types.json, tests/SpecTests/client-side-encryption/tests/updateMany.json, tests/SpecTests/client-side-encryption/tests/updateOne.json
https://jira.mongodb.org/browse/PHPLIB-554
=> PHPLIB-554: Stop using admin database for encryption keys

src/Exception/UnsupportedException.php, src/Operation/Find.php, tests/SpecTests/crud/find-allowdiskuse-clientError.json, tests/SpecTests/crud/find-allowdiskuse-serverError.json
https://jira.mongodb.org/browse/PHPLIB-556
=> PHPLIB-556: Throw client-side error when allowDiskUse is not supported by a server

.travis.yml, tests/Operation/WatchFunctionalTest.php
Also bumps older server versions to their latest patch release
=> Test against PHPC 1.8.0 and server 4.4.0 on Travis CI

tests/SpecTests/TransactionsSpecTest.php
This was introduced in 1245eb94e97d4958a6ed124b4a8b5453f2d60be3
=> Remove duplicate skipReason check

.travis.yml, composer.json, tests/SpecTests/ErrorExpectation.php, tests/SpecTests/retryable-writes/insertOne-serverErrors.json
https://jira.mongodb.org/browse/PHPLIB-581
https://jira.mongodb.org/browse/PHPLIB-585
=> PHPLIB-581, PHPLIB-585: Check error labels for retryable writes spec tests 

CONTRIBUTING.md
https://jira.mongodb.org/browse/PHPLIB-605
=> PHPLIB-605: Update instructions for external doc updates

tests/UnifiedSpecTests/valid-fail/operation-failure.json
https://jira.mongodb.org/browse/PHPLIB-612
=> PHPLIB-612: Expect success for operations without expectError and expectResult 

tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/change-streams/change-streams.json
=> PHPLIB-624 Sync change stream spec tests for delta oplog entries

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/config.yml
Complements https://github.com/mongodb/mongo-php-driver/pull/1218
=> Add external links to new issue workflow

tests/UnifiedSpecTests/Context.php, tests/UnifiedSpecTests/EntityMap.php, tests/UnifiedSpecTests/EventCollector.php, tests/UnifiedSpecTests/EventObserver.php, tests/UnifiedSpecTests/Loop.php, tests/UnifiedSpecTests/Operation.php, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/UnifiedTestCase.php, tests/UnifiedSpecTests/UnifiedTestRunner.php, tests/UnifiedSpecTests/valid-fail/entity-client-storeEventsAsEntities-conflict_with_client_id.json, tests/UnifiedSpecTests/valid-fail/entity-client-storeEventsAsEntities-conflict_within_different_array.json, tests/UnifiedSpecTests/valid-fail/entity-client-storeEventsAsEntities-conflict_within_same_array.json, tests/UnifiedSpecTests/valid-pass/entity-client-storeEventsAsEntities.json
https://jira.mongodb.org/browse/PHPLIB-613
https://jira.mongodb.org/browse/PHPLIB-627
https://jira.mongodb.org/browse/PHPLIB-640
This includes a commit syncing spec tests with mongodb/specifications#921, which should be revised after that PR is merged so that it instead refers to the merged commit in that repository.
=> PHPLIB-627: Comprehensive Atlas Tests

tests/FunctionalTestCase.php, tests/UnifiedSpecTests/UnifiedTestRunner.php
=> PHPLIB-634 Ignore pre-release flags in server version numbers

.evergreen/config.yml, .evergreen/run-tests.sh, tests/UnifiedSpecTests/UnifiedSpecTest.php
=> PHPLIB-650 Run versioned API tests with acceptApiVersion2

tests/UnifiedSpecTests/ExpectedError.php
https://jira.mongodb.org/browse/PHPLIB-656
=> PHPLIB-656: Ensure isClientError assertions are handled

tests/DocumentationExamplesTest.php
=> PHPLIB-653 Add versioned API connection examples for docs

tests/UnifiedSpecTests/crud/aggregate-let.json
https://jira.mongodb.org/browse/PHPLIB-663
Synced with mongodb/specifications@3a58fc612b3520030a97a1161a5651c451c40f8e from https://github.com/mongodb/specifications/pull/1014
=> PHPLIB-663: Update aggregate-let spec test

docs/tutorial/collation.txt
=> PHPLIB-706 Fix syntax error in docs example

tests/SpecTests/command-monitoring/find.json
https://jira.mongodb.org/browse/PHPLIB-707
Synced with mongodb/specifications@b8928fa15752a9270e39ad2d2a14fd0b3eb0bfbc
=> PHPLIB-707: Remove modifiers from command monitoring spec test

tests/UnifiedSpecTests/valid-fail/entity-findCursor-malformed.json, tests/UnifiedSpecTests/valid-fail/entity-findCursor.json, tests/UnifiedSpecTests/valid-fail/ignoreResultAndError-malformed.json
https://jira.mongodb.org/browse/PHPLIB-708
Synced with mongodb/specifications@73d1286c4fd34a71583feb262c0105b4286cb295
=> PHPLIB-708: Sync unified test runner valid-fail tests

.github/workflows/tests.yml
=> PHPLIB-716 Add PHP 8.1 to CI pipeline

docs/includes/apiargs-MongoDBCollection-method-find-option.yaml, docs/includes/apiargs-aggregate-option.yaml, src/Operation/Aggregate.php, src/Operation/Find.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/AggregateTest.php
https://jira.mongodb.org/browse/PHPLIB-721
=> PHPLIB-721: Aggregate allowDiskUse option should be unset by default

tests/SpecTests/atlas_data_lake/estimatedDocumentCount.json, tests/SpecTests/retryable-writes/bulkWrite-serverErrors.json, tests/SpecTests/retryable-writes/deleteOne-serverErrors.json, tests/SpecTests/retryable-writes/findOneAndDelete-serverErrors.json, tests/SpecTests/retryable-writes/findOneAndReplace-serverErrors.json, tests/SpecTests/retryable-writes/findOneAndUpdate-serverErrors.json, tests/SpecTests/retryable-writes/insertMany-serverErrors.json, tests/SpecTests/retryable-writes/insertOne-serverErrors.json, tests/SpecTests/retryable-writes/replaceOne-serverErrors.json, tests/SpecTests/retryable-writes/updateOne-serverErrors.json, tests/SpecTests/transactions/error-labels.json, tests/SpecTests/transactions/mongos-recovery-token.json, tests/SpecTests/transactions/retryable-abort.json, tests/SpecTests/transactions/retryable-commit.json
https://jira.mongodb.org/browse/PHPLIB-755
https://jira.mongodb.org/browse/PHPLIB-764
Patch build for Atlas Data Lake: https://spruce.mongodb.com/version/61a794ed2a60ed3f0cc836b9/tasks
=> PHPLIB-764 and PHPLIB-755: Update ADL, retryable writes, and transaction spec tests

src/Collection.php, src/Database.php, src/functions.php
https://jira.mongodb.org/browse/PHPLIB-760
=> PHPLIB-760: Force primary for $out/$merge if any servers are pre-5.0

.evergreen/config.yml
https://jira.mongodb.org/browse/PHPLIB-773
=> PHPLIB-773: Fix GCP_PRIVATE_KEY export

.evergreen/config.yml, .evergreen/run-tests.sh, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/Context.php, tests/SpecTests/client-side-encryption/corpus/corpus-encrypted.json, tests/SpecTests/client-side-encryption/corpus/corpus-key-kmip.json, tests/SpecTests/client-side-encryption/corpus/corpus-schema.json, tests/SpecTests/client-side-encryption/corpus/corpus.json, tests/SpecTests/client-side-encryption/tests/gcpKMS.json, tests/SpecTests/client-side-encryption/tests/kmipKMS.json
https://jira.mongodb.org/browse/PHPLIB-768
https://jira.mongodb.org/browse/PHPLIB-639
Depends on https://github.com/mongodb/mongo-php-driver/pull/1280
=> PHPLIB-768: Spec and prose tests for CSFLE KMIP support

.github/workflows/coding-standards.yml, .github/workflows/tests.yml
https://jira.mongodb.org/browse/PHPLIB-775
=> PHPLIB-775: Revert to stable versions in GitHub CI

tests/SpecTests/PrimaryStepDownSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-798
=> PHPLIB-798: Use more flexible assertions for connection counts

src/Operation/Watch.php
https://jira.mongodb.org/browse/PHPLIB-808
=> PHPLIB-808: Leave fullDocument change stream option unset by default

tests/SpecTests/Context.php, tests/UnifiedSpecTests/Context.php
https://jira.mongodb.org/browse/PHPLIB-761
=> PHPLIB-761: Disable client persistence when creating clients in test runners

composer.json
https://jira.mongodb.org/browse/PHPLIB-844
=> PHPLIB-844: Explicitly allow phpcodesniffer-composer-installer plugin

tests/UnifiedSpecTests/change-streams/change-streams-errors.json
https://jira.mongodb.org/browse/PHPLIB-652
Synced with mongodb/specifications@dbfbc0f4f10234b1fa4f3f216b0919c68e4607bb
=> PHPLIB-652: Update change stream error tests for 3.6 compat

.evergreen/config.yml, tests/UnifiedSpecTests/Context.php, tests/UnifiedSpecTests/UnifiedTestRunner.php, tests/UnifiedSpecTests/change-streams/change-streams-errors.json, tests/UnifiedSpecTests/change-streams/change-streams-pre_and_post_images.json, tests/UnifiedSpecTests/change-streams/change-streams-resume-allowlist.json, tests/UnifiedSpecTests/change-streams/change-streams-resume-errorLabels.json, tests/UnifiedSpecTests/change-streams/change-streams.json, tests/UnifiedSpecTests/valid-pass/poc-change-streams.json
https://jira.mongodb.org/browse/PHPLIB-757
https://jira.mongodb.org/browse/PHPLIB-850
POC for [DRIVERS-1967](https://jira.mongodb.org/browse/DRIVERS-1967):
* https://github.com/mongodb-labs/drivers-evergreen-tools/pull/194
* https://github.com/mongodb/specifications/pull/1186
Evergreen build with `serverless` task: https://spruce.mongodb.com/version/62680d903e8e862c2edebdee/tasks
=> PHPLIB-757: Serverless testing uses LB with single proxy

tests/FunctionalTestCase.php, tests/SpecTests/ClientSideEncryptionSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-647
=> PHPLIB-647: skipping CSFLE tests if mongocryptd is not available

tests/UnifiedSpecTests/valid-fail/operation-unsupported.json
https://jira.mongodb.org/browse/PHPLIB-865
=> PHPLIB-865: valid-fail test for unsupported operation

tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php
https://jira.mongodb.org/browse/PHPLIB-863
Introduces an isEnterprise() helper, since this example requires automatic encryption.
=> PHPLIB-863: Queryable encryption example for docs team

tests/UnifiedSpecTests/crud/distinct-comment.json
https://jira.mongodb.org/browse/PHPLIB-880
=> PHPLIB-880: Add comment option tests for distinct helper

tests/SpecTests/ClientSideEncryptionSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-885
This was a prose test for [DRIVERS-2297](https://jira.mongodb.org/browse/DRIVERS-2297) ([PHPC-2085](https://jira.mongodb.org/browse/PHPC-2085)) and missed in the previous PR for spec/prose tests.
=> PHPLIB-885: Bypass spawning mongocryptd with bypassQueryAnalysis

.evergreen/config.yml
https://jira.mongodb.org/browse/PHPLIB-858
Complete patch build: https://spruce.mongodb.com/version/62b0c896a4cf471beaebaa77/tasks
=> PHPLIB-858: Test against MongoDB 6.0 in Evergreen and revise matrices

.evergreen/config.yml, .evergreen/run-tests.sh, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/Context.php
https://jira.mongodb.org/browse/PHPLIB-891
Patch build: https://spruce.mongodb.com/version/62b49d1e2fbabe61ed9a241f/tasks
=> PHPLIB-891: Run CSFLE tests with crypt_shared

tests/SpecTests/ClientSideEncryptionSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-884
The necessary fix is included in MongoDB 6.0.0-rc10 (see: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/207).
=> PHPLIB-884: Remove manual preparation of "contention" option

tests/SpecTests/ClientSideEncryptionSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-890
=> PHPLIB-890: Test auto decryption occurs after CommandSucceeded events

tests/UnifiedSpecTests/sessions/driver-sessions-dirty-session-errors.json
https://jira.mongodb.org/browse/PHPLIB-900
=> PHPLIB-900: Spec test for discarding dirty implicit session incorrectly uses explicit session

tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/client-side-encryption/tests/fle2-Delete.json, tests/SpecTests/client-side-encryption/tests/fle2-EncryptedFields-vs-jsonSchema.json, tests/SpecTests/client-side-encryption/tests/fle2-FindOneAndUpdate.json, tests/SpecTests/client-side-encryption/tests/fle2-InsertFind-Indexed.json, tests/SpecTests/client-side-encryption/tests/fle2-Update.json
https://jira.mongodb.org/browse/PHPLIB-882
https://jira.mongodb.org/browse/PHPLIB-905
=> PHPLIB-882, PHPLIB-905: Update CSFLE tests for libmongocrypt 1.5.0

tests/UnifiedSpecTests/load-balancers/cursors.json, tests/UnifiedSpecTests/load-balancers/sdam-error-handling.json, tests/UnifiedSpecTests/load-balancers/transactions.json
https://jira.mongodb.org/browse/PHPLIB-936
Synced with mongodb/specifications@008d2f5aab41dabced03e0860bab614c0f15ded5
=> PHPLIB-936: Update schemaVersion in load balancer spec tests

tests/FunctionalTestCase.php
https://jira.mongodb.org/browse/PHPLIB-942
=> PHPLIB-942: Fix pattern for matching phpinfo() values

CONTRIBUTING.md
https://jira.mongodb.org/browse/PHPLIB-944
Related to https://github.com/mongodb/mongo-php-driver/pull/1354
=> PHPLIB-944: Document environment variables supported by the test suite

tests/SpecTests/client-side-encryption/tests/fle2-InsertFind-Unindexed.json
https://jira.mongodb.org/browse/PHPLIB-930
Synced with mongodb/specifications@1a911b5e8911f6f57426ec1d451dbdc19480afd8
=> PHPLIB-930: Update expected error in fle2-InsertFind-Unindexed test

tests/UnifiedSpecTests/change-streams/change-streams-disambiguatedPaths.json
https://jira.mongodb.org/browse/PHPLIB-946
Synced with mongodb/specifications@9a8abe81c3ae9727ae63ca758a434228d68d203e
=> PHPLIB-946: Forbid Serverless in Change Stream Disambiguated Unified Spec Tests

tests/UnifiedSpecTests/RunOnRequirement.php, tests/UnifiedSpecTests/ServerParameterHelper.php, tests/UnifiedSpecTests/UnifiedTestRunner.php
=> PHPLIB-982: Change evaluation of serverParameters to allow for server differences

phpcs.xml.dist, psalm.xml.dist
PHPLIB-979
This PR adds phpcs and psalm checks to the code in the examples folder.
=> PHPLIB-979: Run checks on example code

tests/UnifiedSpecTests/crud/bulkWrite-errorResponse.json, tests/UnifiedSpecTests/crud/deleteOne-errorResponse.json, tests/UnifiedSpecTests/crud/insertOne-errorResponse.json, tests/UnifiedSpecTests/crud/updateOne-errorResponse.json
https://jira.mongodb.org/browse/PHPLIB-909
Synced with https://github.com/mongodb/specifications/pull/1329
=> PHPLIB-909: Update errorResponse tests

.evergreen/config.yml
https://jira.mongodb.org/browse/PHPLIB-1024
Patch build: https://spruce.mongodb.com/version/6361e7210305b930285b661b/tasks
=> PHPLIB-1024: Add PHP 8.2 to Evergreen matrix

.github/workflows/coding-standards.yml, .github/workflows/static-analysis.yml, .github/workflows/tests.yml
It is still used here and there in the CI
=> Use `actions/checkout@v3`

docs/faq.txt, docs/reference/method/MongoDBCollection-find.txt, docs/reference/method/MongoDBCollection-findOne.txt, docs/reference/method/MongoDBCollection-updateMany.txt, docs/reference/method/MongoDBCollection-updateOne.txt, docs/tutorial/crud.txt
No matter the decision of 
* #1036 
the ones in this PR should be changed anyway
=> [Documentation] Add PHP open tag to examples

docs/faq.txt
A new day, a new PR ☀️ 
I propose to not trigger the code builds when changing the documentation, WDYT?
=> [Documentation] Spelling

tests/SpecTests/ClientSideEncryptionSpecTest.php
=> PHPLIB-619: Unskip Azure encryption test

tests/UnifiedSpecTests/client-side-encryption/rewrapManyDataKey.json
=> PHPLIB-1068: Sync rewrapManyDataKey unified spec test

src/Operation/EstimatedDocumentCount.php
https://jira.mongodb.org/browse/PHPLIB-1094
=> PHPLIB-1094: Remove obsolete internal constants

tests/SpecTests/client-side-encryption/tests/getMore.json, tests/UnifiedSpecTests/load-balancers/cursors.json, tests/UnifiedSpecTests/valid-pass/entity-cursor-iterateOnce.json, tests/UnifiedSpecTests/valid-pass/entity-find-cursor.json
https://jira.mongodb.org/browse/PHPLIB-1156
See: mongodb/specifications#1427
Patch build: https://spruce.mongodb.com/version/6476f49ad1fe07f45028a9ff/tasks
=> PHPLIB-1156: Use more flexible getMore cursor ID assertions

tests/Collection/CrudSpecFunctionalTest.php, tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php, tests/Operation/BulkWriteFunctionalTest.php, tests/Operation/CreateEncryptedCollectionFunctionalTest.php, tests/Operation/CreateIndexesFunctionalTest.php, tests/Operation/DeleteFunctionalTest.php, tests/Operation/ExplainFunctionalTest.php, tests/Operation/FindAndModifyFunctionalTest.php, tests/Operation/MapReduceFunctionalTest.php, tests/Operation/UpdateFunctionalTest.php, tests/Operation/WatchFunctionalTest.php, tests/SpecTests/ClientSideEncryption/Prose21_AutomaticDataEncryptionKeysTest.php, tests/SpecTests/ClientSideEncryption/Prose22_RangeExplicitEncryptionTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/RetryableWritesSpecTest.php
=> PHPLIB-1153: Add `FunctionalTestCase::skipIfServerVersion($op, $version)`

.github/workflows/benchmark.yml
Missing from https://github.com/mongodb/mongo-php-library/pull/1163
=> Add env to phpbench HTML report

.github/workflows/tests.yml
=> PHPLIB-1245: Test on PHP 8.3

docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, docs/includes/apiargs-MongoDBCollection-method-createSearchIndex-option.yaml, docs/includes/apiargs-MongoDBCollection-method-createSearchIndex-param.yaml, docs/includes/apiargs-MongoDBCollection-method-createSearchIndexes-option.yaml, docs/includes/apiargs-MongoDBCollection-method-createSearchIndexes-param.yaml, docs/includes/apiargs-MongoDBCollection-method-dropSearchIndex-option.yaml, docs/includes/apiargs-MongoDBCollection-method-dropSearchIndex-param.yaml, docs/includes/apiargs-MongoDBCollection-method-listSearchIndexes-option.yaml, docs/includes/apiargs-MongoDBCollection-method-listSearchIndexes-param.yaml, docs/includes/apiargs-MongoDBCollection-method-updateSearchIndex-option.yaml, docs/includes/apiargs-MongoDBCollection-method-updateSearchIndex-param.yaml, docs/includes/apiargs-MongoDBCollection-method-watch-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-aggregate-option.yaml, docs/includes/extracts-note.yaml, docs/reference/class/MongoDBCollection.txt, docs/reference/method/MongoDBCollection-createSearchIndex.txt, docs/reference/method/MongoDBCollection-createSearchIndexes.txt, docs/reference/method/MongoDBCollection-dropSearchIndex.txt, docs/reference/method/MongoDBCollection-listSearchIndexes.txt, docs/reference/method/MongoDBCollection-updateSearchIndex.txt
https://jira.mongodb.org/browse/PHPLIB-1143
https://jira.mongodb.org/browse/PHPLIB-1306
=> PHPLIB-1143: Document Atlas Search index helpers and fix aggregate "collation" docs

.evergreen/config/generated/test/require-api-version-5.0.yml, .evergreen/config/generated/test/require-api-version-6.0.yml, .evergreen/config/generated/test/require-api-version-7.0.yml, .evergreen/config/generated/test/require-api-version-latest.yml, .evergreen/config/generated/test/require-api-version-rapid.yml, .evergreen/config/templates/test/require-api-version.yml, tests/ClientFunctionalTest.php, tests/GridFS/BucketFunctionalTest.php
This PR fixes a couple of failures that occur due to the test client being created not having the required API version set. To avoid issues in the future, the PR also changes the names of those tasks to match the schema used elsewhere so they can be run in PR builds.
=> Fix evergreen failures

composer.json
- Upgrade to rector 0.19 to fix phpstan incompatibility (#1211)
=> Merge v1.17 into master

docs/includes/extracts-collection-option.yaml
https://jira.mongodb.org/browse/DOCSP-37027
=> DOCSP-37027: Remove use of post in collection-option-collation

docs/includes/extracts-watch-option.yaml, docs/reference/method/MongoDBDatabase-selectGridFSBucket.txt, docs/reference/method/MongoDBGridFSBucket-openUploadStream.txt, docs/reference/method/MongoDBGridFSBucket-uploadFromStream.txt, docs/reference/method/MongoDBGridFSBucket__construct.txt
See: https://github.com/mongodb/mongo-php-library/pull/1264#discussion_r1536871831
=> Fix versionadded syntax in option docs

.github/workflows/tests.yml
=> PHPLIB-1415 Add tests for PHP 8.4

docs/includes/extracts-option-requires.yaml, docs/reference.txt, docs/reference/method/MongoDBCollection-bulkWrite.txt, docs/reference/method/MongoDBCollection-dropIndex.txt, docs/reference/method/MongoDBCollection-dropIndexes.txt, docs/reference/method/MongoDBCollection-explain.txt, docs/reference/method/MongoDBCollection-findOneAndUpdate.txt, docs/reference/method/MongoDBCollection-updateMany.txt, docs/reference/method/MongoDBCollection-updateOne.txt, docs/reference/method/MongoDBDatabase-createCollection.txt, docs/reference/result-classes.txt, docs/tutorial/gridfs.txt
These changes also apply to the 1.17 branch.
JIRA - https://jira.mongodb.org/browse/DOCSP-37027
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-37027-v1.16/
Build log - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663a7863b67dbf804ad0be0d
=> DOCSP-37027: Fix 1.16 build errors

.github/workflows/merge-up.yml
With this change, new merge-up pull requests will have auto-merge enabled (using the "merge" strategy). This streamlines the merge-up flow.
=> Enable auto-merge in merge-up workflow

docs/reference/method/MongoDBClient-addSubscriber.txt, docs/reference/method/MongoDBClient-removeSubscriber.txt, docs/reference/method/MongoDBGridFSBucket-registerGlobalStreamWrapperAlias.txt
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-37027-more-fixes-1.18/
Build log - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663e4a71b67dbf804ac21d08
=> DOCSP-37027: Additional build fixes 1.18

docs/reference/method/MongoDBClient-addSubscriber.txt
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-37027-more-fixes-1.18/reference/method/MongoDBClient-addSubscriber/
=> DOCSP-3702: 1.18 build error

docs/tutorial/decimal128.txt
Fixes the broken link in row 120 [here.](https://docs.google.com/spreadsheets/d/1kQ4epk1M-ZW-Gby5YGfJmJCTLIGH5tauqFItcRLBqmg/edit#gid=566175930)
Staging: https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-38371-broken-links/tutorial/decimal128/
=> DOCSP-38371 - Remove broken link

.github/workflows/release.yml
=> Remove obsolete release message preparation

docs/reference/method/MongoDBClient__construct.txt, docs/tutorial/collation.txt
Jira: https://jira.mongodb.org/browse/DOCSP-38371 (spreadsheet rows 113 and 119 only)
Staging:
- [Stable API](https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-38371-more-links/reference/method/MongoDBClient__construct/)
- [Collations](https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-38371-more-links/tutorial/collation/)
**Note:** These changes apply to v1.16 only.
=> DOCSP-38371 - v1.16 broken links

src/Operation/Aggregate.php, src/Operation/Watch.php
Small deprecation issue introduced by https://github.com/mongodb/mongo-php-library/commit/24214b6e5a0380716357e5616c162d7025c974e6#diff-f4971086f83d128efd9587e65b576607ff80c1d3b9581d83ccb672bda677d85eR121
=> Fix optional parameter declared before required parameter
