mongodb/mongo-php-library

src/Client.php, src/Collection.php, src/Database.php, tests/CollectionTest.php
https://jira.mongodb.org/browse/PHPLIB-70
=> PHPLIB-70: Resource CRUD prototypes

composer.json, src/Client.php, src/Collection.php, src/Database.php, src/Exception/BadMethodCallException.php, src/Exception/Exception.php, src/Exception/InvalidArgumentException.php, src/Exception/UnexpectedTypeException.php, src/FeatureDetection.php, src/Model/CollectionInfo.php, src/Model/CollectionInfoCommandIterator.php, src/Model/CollectionInfoIterator.php, src/Model/CollectionInfoLegacyIterator.php, src/Model/DatabaseInfo.php, src/Model/DatabaseInfoIterator.php, src/Model/DatabaseInfoLegacyIterator.php, src/Model/IndexInfo.php, src/Model/IndexInfoIterator.php, src/Model/IndexInfoIteratorIterator.php, src/Model/IndexInput.php, tests/ClientFunctionalTest.php, tests/CollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-70
=> PHPLIB-70: DatabaseInfo models and index management

src/Client.php, src/Collection.php, src/Database.php, src/Exception/RuntimeException.php, src/Exception/UnexpectedValueException.php, src/Model/IndexInfo.php, src/Model/IndexInput.php, tests/Model/CollectionInfoTest.php, tests/Model/DatabaseInfoTest.php, tests/Model/IndexInfoTest.php, tests/Model/IndexInputTest.php
* https://jira.mongodb.org/browse/PHPLIB-75
* https://jira.mongodb.org/browse/PHPLIB-77
* https://jira.mongodb.org/browse/PHPLIB-88
=> Namespaced exceptions and model tests

src/Collection.php, src/Database.php
https://jira.mongodb.org/browse/PHPLIB-89
=> PHPLIB-89: String getters for Database and Collection classes

src/Client.php, src/Operation/Aggregate.php, src/Operation/Count.php, src/Operation/CreateCollection.php, src/Operation/CreateIndexes.php, src/Operation/Distinct.php, src/Operation/DropCollection.php, src/Operation/DropDatabase.php, src/Operation/DropIndexes.php, src/Operation/FindAndModify.php
https://jira.mongodb.org/browse/PHPLIB-73
=> PHPLIB-73: WC/RP inheritance and type map cleanup

.travis.yml, src/Client.php, src/Collection.php, src/Database.php, src/Operation/Aggregate.php, src/Operation/BulkWrite.php, src/Operation/Count.php, src/Operation/Delete.php, src/Operation/Distinct.php, src/Operation/Find.php, src/Operation/FindOne.php, src/Operation/InsertMany.php, src/Operation/InsertOne.php, src/Operation/Update.php, src/functions.php, tests/Operation/AggregateTest.php, tests/Operation/CountTest.php, tests/Operation/DistinctTest.php, tests/Operation/FindTest.php, tests/Operation/TestCase.php
https://jira.mongodb.org/browse/PHPLIB-111
=> PHPLIB-111: Ensure read ops use appropriate read preference

src/Operation/DropCollection.php, src/Operation/ListIndexes.php, tests/Operation/ListCollectionsFunctionalTest.php, tests/Operation/ListIndexesFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-123
=> PHPLIB-123: Do not throw when listing indexes on nonexistent collection

src/Operation/FindOne.php, src/Operation/FindOneAndDelete.php, src/Operation/FindOneAndReplace.php, src/Operation/FindOneAndUpdate.php, tests/Collection/CrudSpec/AggregateFunctionalTest.php, tests/Collection/FunctionalTestCase.php, tests/FunctionalTestCase.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/DropDatabaseFunctionalTest.php, tests/Operation/FindAndModifyTest.php, tests/Operation/FindOneAndDeleteTest.php, tests/Operation/FindOneAndReplaceTest.php, tests/Operation/FindOneAndUpdateTest.php, tests/Operation/FindOneFunctionalTest.php, tests/Operation/FindOneTest.php, tests/Operation/FindTest.php, tests/Operation/FunctionalTestCase.php, tests/Operation/TestCase.php
https://jira.mongodb.org/browse/PHPLIB-133
This PR also refactors the test suite a bit and adds coverage for FindAndModify operations.
=> PHPLIB-133: Support typeMap option in FindOne

src/BulkWriteResult.php, src/DeleteResult.php, src/Exception/BadMethodCallException.php, src/InsertManyResult.php, src/InsertOneResult.php, src/UpdateResult.php, tests/Operation/BulkWriteFunctionalTest.php, tests/Operation/DeleteFunctionalTest.php, tests/Operation/InsertManyFunctionalTest.php, tests/Operation/InsertOneFunctionalTest.php, tests/Operation/UpdateFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-68
=> PHPLIB-68: Throw when accessing fields in unacknowledged write result

src/Client.php, tests/ClientTest.php
https://jira.mongodb.org/browse/PHPLIB-151
This should help avoid failed IPv6 connections when "localhost" resolves to an IPv6 literal and mongod does not have `net.ipv6}} enabled to listen for IPv6.
=> PHPLIB-151: Use IPv4 localhost address for default URI

.travis.yml, src/Operation/Aggregate.php, src/Operation/Count.php, src/Operation/CreateCollection.php, src/Operation/CreateIndexes.php, src/Operation/Distinct.php, src/Operation/DropCollection.php, src/Operation/DropDatabase.php, src/Operation/DropIndexes.php, src/Operation/FindAndModify.php, src/Operation/ListDatabases.php
https://jira.mongodb.org/browse/PHPLIB-122
=> PHPLIB-122: Checking "ok" field in command results is redundant

src/Operation/Aggregate.php, src/Operation/BulkWrite.php, src/Operation/FindAndModify.php, src/Operation/FindOneAndReplace.php, src/Operation/FindOneAndUpdate.php, src/Operation/InsertMany.php, src/Operation/InsertOne.php, src/Operation/ReplaceOne.php, src/Operation/Update.php, src/Operation/UpdateMany.php, src/Operation/UpdateOne.php, tests/Operation/AggregateTest.php, tests/Operation/BulkWriteTest.php, tests/Operation/FindAndModifyTest.php, tests/Operation/InsertManyTest.php, tests/Operation/InsertOneTest.php, tests/Operation/UpdateTest.php
https://jira.mongodb.org/browse/PHPLIB-125
=> PHPLIB-125: Support bypassDocumentValidation option on write commands

src/Collection.php, src/Operation/FindAndModify.php, src/Operation/FindOneAndDelete.php, src/Operation/FindOneAndReplace.php, src/Operation/FindOneAndUpdate.php, tests/Operation/FindAndModifyTest.php
https://jira.mongodb.org/browse/PHPLIB-129
=> PHPLIB-129: Support writeConcern option for findAndModify

src/Collection.php, src/Database.php, src/Operation/Aggregate.php, src/Operation/Count.php, src/Operation/Distinct.php, src/Operation/Find.php, src/Operation/FindOne.php, src/functions.php, tests/Collection/CollectionFunctionalTest.php, tests/Database/DatabaseFunctionalTest.php, tests/FunctionsTest.php, tests/Operation/AggregateTest.php, tests/Operation/CountTest.php, tests/Operation/DistinctTest.php, tests/Operation/FindTest.php, tests/TestCase.php
https://jira.mongodb.org/browse/PHPLIB-130
=> PHPLIB-130: Support readConcern option

src/Operation/CreateCollection.php, tests/Operation/CreateCollectionTest.php
https://jira.mongodb.org/browse/PHPLIB-121
=> PHPLIB-121: Support indexOptionDefaults option for CreateCollection

src/Model/BSONDocument.php, tests/Model/BSONArrayTest.php, tests/Model/BSONDocumentTest.php
This was previously done during unserialization, but not the constructor.
=> BSONDocument should allow property access by default

src/Model/BSONArray.php, src/Model/BSONDocument.php, tests/Model/BSONArrayTest.php, tests/Model/BSONDocumentTest.php
https://jira.mongodb.org/browse/PHPLIB-185
Note: Serialization of BSON type classes (from the driver) still depends on PHPC-459.
=> PHPLIB-185: BSONArray and BSONDocument implement JsonSerializable

src/GridFS/Bucket.php, src/GridFS/ReadableStream.php, src/GridFS/StreamWrapper.php, src/GridFS/WritableStream.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/WritableStreamFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-215
This adds Bucket::getFileDocumentForStream() and Bucket::getFileIdForStream() methods, the latter of which was renamed from getIdFromStream().
Additionally, this replaces the getId() method in both internal stream classes with a getFile() method. The debug output for ReadableStream has also been simplified to include the entire file document instead of ID, chunkSize, and length.
=> PHPLIB-215: Accessor method for GridFS stream file document

src/GridFS/Bucket.php
The method `\MongoDB\GridFS\Bucket::getFileIdForStream()` could be throw `MongoDB\GridFS\Exception\CorruptFileException`, but the exception is not imported.
=> Import CorruptFileException in GridFS\Bucket

.travis.yml
Use the latest stable driver in the build matrix and remove MongoDB 2.4 (to be tested in a specific job).
This also restricts PHP 5.4 and 5.5 to a single job.
=> Revise Travis build matrix

tests/FunctionalTestCase.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/FunctionalTestCase.php, tests/GridFS/SpecFunctionalTest.php
This also adds a change that was missing from https://github.com/mongodb/mongo-php-library/pull/253 (for [PHPLIB-222](https://jira.mongodb.org/browse/PHPLIB-222)).
=> HHVM test suite compatibility

.travis.yml, src/Client.php
Fixes a bug introduced in 21b7d92aef4def00abade10911bae41f1b5ea378 for PHPLIB-200
=> Ensure Client's $writeConcern property is initialized

docs/includes/apiargs-MongoDBDatabase-method-selectGridFSBucket-option.yaml, docs/includes/apiargs-MongoDBGridFSBucket-method-construct-option.yaml, docs/includes/apiargs-MongoDBGridFSBucket-method-findOne-option.yaml, docs/reference/class/MongoDBGridFSBucket.txt, docs/reference/method/MongoDBCollection-findOne.txt, docs/reference/method/MongoDBDatabase-selectGridFSBucket.txt, docs/reference/method/MongoDBGridFSBucket-find.txt, docs/reference/method/MongoDBGridFSBucket-findOne.txt, docs/reference/method/MongoDBGridFSBucket-getFileDocumentForStream.txt, docs/reference/method/MongoDBGridFSBucket-getFileIdForStream.txt, src/Database.php, src/GridFS/Bucket.php, src/GridFS/CollectionWrapper.php, tests/GridFS/BucketFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-232
https://jira.mongodb.org/browse/PHPLIB-238
=> PHPLIB-232, PHPLIB-238: Bucket typeMap option and findOne()

src/Collection.php
https://jira.mongodb.org/browse/PHPLIB-228
=> PHPLIB-228: ReadConcern default should only be set when supported by the server

docs/includes/apiargs-MongoDBCollection-method-findOneAndDelete-option.yaml, docs/includes/apiargs-MongoDBCollection-method-findOneAndReplace-option.yaml, docs/includes/apiargs-MongoDBCollection-method-findOneAndUpdate-option.yaml, src/Operation/FindAndModify.php, src/Operation/FindOneAndDelete.php, src/Operation/FindOneAndReplace.php, src/Operation/FindOneAndUpdate.php
https://jira.mongodb.org/browse/PHPLIB-240
This reverts the logic in 21b7d92aef4def00abade10911bae41f1b5ea378, which was to ignore an unsupported write concern for the duration of 1.x. Since the Collection helper methods do not supply a default write concern option if it is not supported, this change will only affect users that were explicitly passing a write concern and relying on the library to ignore it.
While a minor BC break, this changes makes findAndModify consistent with other write commands.
=> PHPLIB-240: FindAndModify should throw for unsupported write concern

docs/includes/apiargs-MongoDBCollection-common-option.yaml, docs/includes/extracts-error.yaml, src/Exception/UnsupportedException.php, src/Operation/Aggregate.php, src/Operation/Count.php, src/Operation/Distinct.php, src/Operation/Find.php, src/Operation/FindOne.php
https://jira.mongodb.org/browse/PHPLIB-229
=> PHPLIB-229: Operations should not accept unsupported read concern options

docs/includes/extracts-error.yaml, docs/reference/exception-classes.txt, docs/reference/method/MongoDBGridFSBucket-delete.txt, docs/reference/method/MongoDBGridFSBucket-downloadToStream.txt, docs/reference/method/MongoDBGridFSBucket-downloadToStreamByName.txt, docs/reference/method/MongoDBGridFSBucket-drop.txt, docs/reference/method/MongoDBGridFSBucket-find.txt, docs/reference/method/MongoDBGridFSBucket-findOne.txt, docs/reference/method/MongoDBGridFSBucket-getFileDocumentForStream.txt, docs/reference/method/MongoDBGridFSBucket-getFileIdForStream.txt, docs/reference/method/MongoDBGridFSBucket-openDownloadStream.txt, docs/reference/method/MongoDBGridFSBucket-openDownloadStreamByName.txt, docs/reference/method/MongoDBGridFSBucket-rename.txt, docs/reference/method/MongoDBGridFSBucket-uploadFromStream.txt, docs/reference/method/MongoDBGridFSBucket__construct.txt, src/Exception/UnsupportedException.php, src/GridFS/Bucket.php, src/GridFS/WritableStream.php
https://jira.mongodb.org/browse/PHPLIB-221
=> PHPLIB-221: Document GridFS exceptions

src/Operation/Find.php
This property was missing from 8dcc778422a5370196fc8436ef80958d724ca9da.
=> PHPLIB-229: Declare read concern wire version for Find operation

src/Operation/Count.php, src/Operation/Distinct.php
This should have been done in 8dcc778422a5370196fc8436ef80958d724ca9da.
=> PHPLIB-229: Count and Distinct don't need Server to construct commands

src/GridFS/Bucket.php, tests/GridFS/BucketFunctionalTest.php
Fixes https://github.com/mongodb/mongo-php-library/issues/299
=> Check that stream metadata contains a GridFS StreamWrapper

src/GridFS/Bucket.php, src/GridFS/StreamWrapper.php, src/GridFS/WritableStream.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/SpecFunctionalTest.php, tests/GridFS/WritableStreamFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-241
https://jira.mongodb.org/browse/PHPLIB-244
https://jira.mongodb.org/browse/PHPLIB-245
=> GridFS upload refactoring and orphan cleanup on error

CONTRIBUTING.md, README.md, docs/tutorial/install-php-library.txt
By default, Composer installs the most recent stable version and declares a requirement with the caret operator (allowing any newer versions up to but not including the next major version).
Supersedes https://github.com/mongodb/mongo-php-library/pull/314.
PHP.net manual updated in: http://svn.php.net/viewvc?view=revision&revision=341423
=> Remove library version from Composer install examples

src/GridFS/CollectionWrapper.php, src/GridFS/ReadableStream.php, src/GridFS/StreamWrapper.php, tests/GridFS/ReadableStreamFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-247
=> PHPLIB-247: Use strings instead of memory stream for GridFS download buffering

docs/includes/apiargs-MongoDBCollection-method-bulkWrite-option.yaml, docs/includes/extracts-bulkwriteexception.yaml, docs/includes/extracts-error.yaml, docs/reference/method/MongoDBCollection-bulkWrite.txt, docs/reference/method/MongoDBCollection-deleteMany.txt, docs/reference/method/MongoDBCollection-deleteOne.txt, docs/reference/method/MongoDBCollection-insertMany.txt, docs/reference/method/MongoDBCollection-insertOne.txt, docs/reference/method/MongoDBCollection-replaceOne.txt, docs/reference/method/MongoDBCollection-updateMany.txt, docs/reference/method/MongoDBCollection-updateOne.txt
https://jira.mongodb.org/browse/PHPLIB-246
Clarify how the "ordered" option may impact bulk write operations. Also advise users to inspect the BulkWriteException's WriteResult to determine the nature of the error.
Related: https://github.com/mongodb/mongo-php-library/issues/165
=> PHPLIB-246: Document BulkWriteException thrown by write operations

docs/tutorial/crud.txt
https://jira.mongodb.org/browse/PHPLIB-265
As requested in https://github.com/mongodb/mongo-php-library/pull/337#issuecomment-291384402.
=> PHPLIB-265: Add regex example with character escaping

src/MapReduceResult.php, src/Operation/MapReduce.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/MapReduceFunctionalTest.php, tests/Operation/MapReduceTest.php
https://jira.mongodb.org/browse/PHPLIB-53
/cc @alcaeus
=> PHPLIB-53: Create mapReduce command helper

.travis.yml
https://jira.mongodb.org/browse/PHPLIB-279
This also switches to container-based build environments, which allow installing multiple versions of MongoDB via the apt addon.
/cc @alcaeus: I based this on https://github.com/doctrine/mongodb/pull/301 but found a way to still test MongoDB 2.4 (if you care about that sort of thing ^_^).
=> Remove PHP 5.4 and add PHP 7.1 and 7.2 to CI build matrix

docs/reference/bson.txt, docs/reference/class/MongoDBClient.txt, docs/reference/class/MongoDBCollection.txt, docs/reference/class/MongoDBDatabase.txt, docs/reference/class/MongoDBGridFSBucket.txt, docs/reference/method/MongoDBClient-getReadConcern.txt, docs/reference/method/MongoDBClient-getReadPreference.txt, docs/reference/method/MongoDBClient-getTypeMap.txt, docs/reference/method/MongoDBClient-getWriteConcern.txt, docs/reference/method/MongoDBCollection-getReadConcern.txt, docs/reference/method/MongoDBCollection-getReadPreference.txt, docs/reference/method/MongoDBCollection-getTypeMap.txt, docs/reference/method/MongoDBCollection-getWriteConcern.txt, docs/reference/method/MongoDBDatabase-getReadConcern.txt, docs/reference/method/MongoDBDatabase-getReadPreference.txt, docs/reference/method/MongoDBDatabase-getTypeMap.txt, docs/reference/method/MongoDBDatabase-getWriteConcern.txt, docs/reference/method/MongoDBGridFSBucket-getReadConcern.txt, docs/reference/method/MongoDBGridFSBucket-getReadPreference.txt, docs/reference/method/MongoDBGridFSBucket-getTypeMap.txt, docs/reference/method/MongoDBGridFSBucket-getWriteConcern.txt, src/Client.php, src/Collection.php, src/Database.php, src/GridFS/Bucket.php
https://jira.mongodb.org/browse/PHPLIB-271
This incorporates @petr-buchin's work in https://github.com/mongodb/mongo-php-library/pull/385.
@petr-buchin: Ultimately, it wasn't necessary to support `null` return values from the read and write concern accessors. In https://github.com/mongodb/mongo-php-library/pull/399, I handled detection of default RC and WC entirely in the operation classes, which means the core classes can freely carry around the default objects from the Manager. Thanks very much for the initial work on this (especially the docs!).
=> PHPLIB-271: Implement accessors for options on core classes

src/Operation/Aggregate.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/AggregateTest.php
https://jira.mongodb.org/browse/PHPLIB-281
Fixes https://github.com/mongodb/mongo-php-library/issues/398
=> PHPLIB-281: Allow empty pipeline array for aggregation

src/Operation/BulkWrite.php, src/Operation/InsertMany.php, src/Operation/InsertOne.php, src/functions.php
https://jira.mongodb.org/browse/PHPLIB-275
=> PHPLIB-275: BulkWrite::insert() always returns the ID in 1.3.0+

docs/includes/apiargs-MongoDBCollection-method-mapReduce-option.yaml, docs/includes/apiargs-MongoDBCollection-method-mapReduce-param.yaml, docs/reference/class/MongoDBCollection.txt, docs/reference/method/MongoDBCollection-mapReduce.txt, src/Collection.php, src/Operation/MapReduce.php, tests/Collection/CollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-53
=> PHPLIB-53 Add documentation for mapReduce

docs/includes/apiargs-MongoDBCollection-method-find-option.yaml, docs/includes/apiargs-common-option.yaml, docs/reference/method/MongoDBClient-getReadConcern.txt, docs/reference/method/MongoDBClient-getReadPreference.txt, docs/reference/method/MongoDBClient-getTypeMap.txt, docs/reference/method/MongoDBClient-getWriteConcern.txt, docs/reference/method/MongoDBCollection-getReadConcern.txt, docs/reference/method/MongoDBCollection-getReadPreference.txt, docs/reference/method/MongoDBCollection-getTypeMap.txt, docs/reference/method/MongoDBCollection-getWriteConcern.txt, docs/reference/method/MongoDBCollection-mapReduce.txt, docs/reference/method/MongoDBDatabase-getReadConcern.txt, docs/reference/method/MongoDBDatabase-getReadPreference.txt, docs/reference/method/MongoDBDatabase-getTypeMap.txt, docs/reference/method/MongoDBDatabase-getWriteConcern.txt, docs/reference/method/MongoDBGridFSBucket-getChunkSizeBytes.txt, docs/reference/method/MongoDBGridFSBucket-getChunksCollection.txt, docs/reference/method/MongoDBGridFSBucket-getFilesCollection.txt, docs/reference/method/MongoDBGridFSBucket-getReadConcern.txt, docs/reference/method/MongoDBGridFSBucket-getReadPreference.txt, docs/reference/method/MongoDBGridFSBucket-getTypeMap.txt, docs/reference/method/MongoDBGridFSBucket-getWriteConcern.txt
https://jira.mongodb.org/browse/PHPLIB-284
=> PHPLIB-284 Highlight API changes in documentation

tests/Operation/FindFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-268
On servers before 3.2, the option is ignored, which results in a noticeable delay while running the test suite.
=> PHPLIB-268: Skip maxAwaitTimeMS functional test for older servers

docs/reference/method/MongoDBDatabase-selectCollection.txt
The call is made following the MongoDB\Client::selectCollection() signature instead of the MongoDB\Database::selectCollection() signature
=> Fix example 1

docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, src/Operation/Aggregate.php, tests/Operation/AggregateTest.php
https://jira.mongodb.org/browse/PHPLIB-293
=> PHPLIB-293 Add support for a comment parameter to the aggregate command

docs/includes/apiargs-MongoDBCollection-method-createIndex-option.yaml, docs/includes/apiargs-MongoDBCollection-method-createIndexes-option.yaml, src/Collection.php, src/Operation/CreateIndexes.php, tests/Operation/CreateIndexesTest.php
https://jira.mongodb.org/browse/PHPLIB-254
=> PHPLIB-254 Support maxTimeMS option for CreateIndexes operation

tests/GridFS/ReadableStreamFunctionalTest.php
Depends on https://github.com/mongodb/mongo-php-library/pull/457/files#diff-f1209ee81335e16d7fb9c54819f0edb6R178
=> Test ReadableStream::seek() with out-of-range offset

src/Operation/MapReduce.php, tests/Operation/MapReduceFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-313
=> PHPLIB-313 Check that MapReduce's finalize option is an instance of JavascriptInterface

docs/includes/apiargs-MongoDBCollection-method-watch-option.yaml, docs/tutorial/tailable-cursor.txt, src/Operation/Aggregate.php, src/Operation/ChangeStream.php, tests/Operation/ChangeStreamFunctionalTest.php, tests/Operation/FindFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-276
=> PHPLIB-276: Add maxAwaitTimeMS support for change streams

tests/Model/BSONArrayTest.php, tests/Model/BSONDocumentTest.php, tests/Model/CollectionInfoTest.php, tests/Model/DatabaseInfoTest.php, tests/Model/IndexInfoTest.php, tests/Model/IndexInputTest.php, tests/Model/TypeMapArrayIteratorTest.php, tests/Operation/BulkWriteFunctionalTest.php, tests/Operation/DeleteFunctionalTest.php, tests/Operation/InsertManyFunctionalTest.php, tests/Operation/InsertOneFunctionalTest.php, tests/Operation/UpdateFunctionalTest.php
The Operation classes were previously relying on `MongoDB\Tests\Collection\FunctionalTestCase`, so they required additional changes to initialize a Collection instance for asserting outcome of write operations.
=> Fix namespaces in test classes

docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, docs/includes/apiargs-MongoDBCollection-method-createIndex-option.yaml, docs/reference/method/MongoDBBulkWriteResult-getModifiedCount.txt, docs/reference/method/MongoDBUpdateResult-getModifiedCount.txt, src/Model/TypeMapArrayIterator.php, src/Operation/Aggregate.php, src/Operation/CreateIndexes.php, tests/DocumentationExamplesTest.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/BulkWriteFunctionalTest.php, tests/Operation/CountFunctionalTest.php, tests/Operation/CreateIndexesFunctionalTest.php, tests/Operation/UpdateFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-304
=> PHPLIB-304 and PHPLIB-282: Deprecate inline result methods for aggregate and drop support for MongoDB 2.4

src/ChangeStream.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-322
=> PHPLIB-322: Add resume logic to ChangeStream::rewind()

src/Exception/ResumeTokenException.php
Missed this before merging https://github.com/mongodb/mongo-php-library/pull/480.
Thank you, PedantryTest.
=> Fix order of ResumeTokenException methods

.travis.yml, .travis/debug-core.sh, .travis/mo.sh, tests/Operation/FindFunctionalTest.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-299
While implementing this PR, I realized that we can cache the result of `pecl install mongodb` and avoid spending time recompiling the extension for each job. I've opened [PHPLIB-324](https://jira.mongodb.org/browse/PHPLIB-324) to track that task.
=> PHPLIB-299: Ensure Travis uses expected server versions

docs/includes/apiargs-MongoDBClient-method-listDatabases-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-listCollections-option.yaml, src/Operation/ListCollections.php, src/Operation/ListDatabases.php, tests/Operation/ListDatabasesFunctionalTest.php, tests/Operation/ListDatabasesTest.php
https://jira.mongodb.org/browse/PHPLIB-283
=>  PHPLIB-283: Support filter option for ListDatabases

src/functions.php, tests/ClientTest.php, tests/FunctionsTest.php
https://jira.mongodb.org/browse/PHPLIB-318
=> PHPLIB-318: Remove utility functions to convert read and write concerns to documents

src/Collection.php
https://jira.mongodb.org/browse/PHPLIB-325
I tested this locally why subbing in PHPLIB's default type map in all of the WatchFunctionalTest options arguments. My only concern was that resume token extraction still works, but I then realized that the existing type map test in WatchFunctionalTest already covered that, too.
=> PHPLIB-325: Apply Collection typeMap to change streams

composer.json, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/ReadableStreamFunctionalTest.php, tests/GridFS/SpecFunctionalTest.php, tests/GridFS/WritableStreamFunctionalTest.php, tests/Operation/ReplaceOneTest.php, tests/Operation/UpdateManyTest.php, tests/Operation/UpdateOneTest.php, tests/bootstrap.php
https://jira.mongodb.org/browse/PHPLIB-294
=> PHPLIB-294: Make test suite compatible with PHPUnit 6.4

.travis.yml
https://jira.mongodb.org/browse/PHPLIB-324
=> PHPLIB-324: Cache extension installation for Travis CI jobs

docs/includes/apiargs-MongoDBCollection-method-updateOne-option.yaml
Looks like we forgot to add this in #440.
=> Document arrayFilters option for UpdateOne

docs/reference/method/MongoDBModelCollectionInfo-getCappedMax.txt, docs/reference/method/MongoDBModelCollectionInfo-getCappedSize.txt, docs/reference/method/MongoDBModelCollectionInfo-getName.txt, docs/reference/method/MongoDBModelCollectionInfo-getOptions.txt, docs/reference/method/MongoDBModelCollectionInfo-isCapped.txt, docs/reference/method/MongoDBModelDatabaseInfo-getName.txt, docs/reference/method/MongoDBModelDatabaseInfo-getSizeOnDisk.txt, docs/reference/method/MongoDBModelDatabaseInfo-isEmpty.txt, docs/reference/method/MongoDBModelIndexInfo-getKey.txt, docs/reference/method/MongoDBModelIndexInfo-getName.txt, docs/reference/method/MongoDBModelIndexInfo-getNamespace.txt, docs/reference/method/MongoDBModelIndexInfo-getVersion.txt, docs/reference/method/MongoDBModelIndexInfo-isSparse.txt, docs/reference/method/MongoDBModelIndexInfo-isTtl.txt, docs/reference/method/MongoDBModelIndexInfo-isUnique.txt
https://jira.mongodb.org/browse/PHPLIB-278
=> PHPLIB-278: Add examples for calling methods on database, collection, and index models

docs/reference/enumeration-classes.txt, docs/reference/method/MongoDBModelIndexInfo-is2dSphere.txt, docs/reference/method/MongoDBModelIndexInfo-isGeoHaystack.txt, docs/reference/method/MongoDBModelIndexInfo-isText.txt, src/Model/IndexInfo.php, tests/Model/IndexInfoFunctionalTest.php, tests/Model/IndexInfoTest.php
https://jira.mongodb.org/browse/PHPLIB-80
=> PHPLIB-80: Add IndexInfo helper methods for special index type options

src/ChangeStream.php, src/Operation/Watch.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-342
I marked this [WIP] because I'll update `WatchFunctionalTest` to verify that the `lsid`s of all aggregates and getMores are the same after [PHPC-1152](https://jira.mongodb.org/browse/PHPC-1152) is merged.
=> PHPLIB-342: Change streams should use the same session when resuming

docs/reference/method/MongoDBGridFSBucket-delete.txt, docs/reference/method/MongoDBGridFSBucket-downloadToStream.txt, docs/reference/method/MongoDBGridFSBucket-downloadToStreamByName.txt, docs/reference/method/MongoDBGridFSBucket-drop.txt, docs/reference/method/MongoDBGridFSBucket-find.txt, docs/reference/method/MongoDBGridFSBucket-findOne.txt, docs/reference/method/MongoDBGridFSBucket-getBucketName.txt, docs/reference/method/MongoDBGridFSBucket-getChunkSizeBytes.txt, docs/reference/method/MongoDBGridFSBucket-getChunksCollection.txt, docs/reference/method/MongoDBGridFSBucket-getDatabaseName.txt, docs/reference/method/MongoDBGridFSBucket-getFileDocumentForStream.txt, docs/reference/method/MongoDBGridFSBucket-getFileIdForStream.txt, docs/reference/method/MongoDBGridFSBucket-getFilesCollection.txt, docs/reference/method/MongoDBGridFSBucket-openDownloadStream.txt, docs/reference/method/MongoDBGridFSBucket-openDownloadStreamByName.txt, docs/reference/method/MongoDBGridFSBucket-openUploadStream.txt, docs/reference/method/MongoDBGridFSBucket-rename.txt, docs/reference/method/MongoDBGridFSBucket-uploadFromStream.txt, docs/reference/method/MongoDBGridFSBucket__construct.txt
https://jira.mongodb.org/browse/PHPLIB-233
=> PHPLIB-233: Add examples for each GridFS API method

src/Model/BSONIterator.php, tests/Model/BSONIteratorTest.php
https://jira.mongodb.org/browse/PHPLIB-262
=> PHPLIB-262: Implement iterator for BSON files

docs/includes/apiargs-MongoDBCollection-method-find-option.yaml, src/Operation/Find.php, src/Operation/FindOne.php, tests/Operation/FindTest.php
https://jira.mongodb.org/browse/PHPLIB-340
=> PHPLIB-340: Deprecate maxScan query option

src/functions.php, tests/Model/BSONArrayTest.php, tests/Model/BSONDocumentTest.php, tests/Model/UncloneableObject.php
https://jira.mongodb.org/browse/PHPLIB-367
This should address the issue reported in https://github.com/mongodb/mongo-php-library/issues/559.
=> PHPLIB-367: BSONArray/Document cloning should respect uncloneable objects

src/Operation/FindAndModify.php
PHPLIB 1.4.0 implicitly dropped support for MongoDB 2.6 and earlier, so this is no longer needed. I likely missed this in https://github.com/mongodb/mongo-php-library/commit/9f36faf78fbe51a1474f424ed2ac11fc14149744.
=> Remove pre-3.0 compat code in FindAndModify

tests/Collection/CrudSpecFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-386
I noticed this while testing PHPLIB against the new CRUD spec tests added in https://github.com/mongodb/specifications/pull/396.
=> PHPLIB-386: Assert upsertedIds field in bulkWrite CRUD spec tests

tests/Collection/CrudSpecFunctionalTest.php, tests/Collection/spec-tests/read/count-empty.json, tests/Collection/spec-tests/write/bulkWrite-collation.json, tests/Collection/spec-tests/write/bulkWrite.json, tests/Collection/spec-tests/write/insertMany.json, tests/Collection/spec-tests/write/updateMany-arrayFilters.json
https://jira.mongodb.org/browse/PHPLIB-387
These improvements complement test revisions in https://github.com/mongodb/specifications/pull/399.
We can wait until the new spec tests are merged so that they can be incorporated into this PR; however, the test runner changes can be reviewed immediately.
=> PHPLIB-387: Support errors and unordered writes in CRUD spec tests

composer.json, tests/Collection/CollectionFunctionalTest.php, tests/Collection/FunctionalTestCase.php, tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/FindFunctionalTest.php, tests/Operation/FunctionalTestCase.php, tests/Operation/MapReduceFunctionalTest.php, tests/Operation/ModifyCollectionFunctionalTest.php, tests/Operation/WatchFunctionalTest.php
See: https://github.com/mongodb/mongo-php-library/issues/562
This is a regression test for [CDRIVER-2744](https://jira.mongodb.org/browse/CDRIVER-2744). It builds upon https://github.com/mongodb/mongo-php-library/pull/563 (for [PHPLIB-373](https://jira.mongodb.org/browse/PHPLIB-373)) and may be fixed by either:
* [PHPLIB-375](https://jira.mongodb.org/browse/PHPLIB-375): omitting read preference option for commands and queries sent in non-sharded topologies
* [PHPC-1236](https://jira.mongodb.org/browse/PHPC-1236): Bumping libmongoc to 1.11.1 (once released)
I don't think we should merge this while failing and would suggest leaving it open until one of the solutions can be implemented.
=> Regression tests for find() and aggregate() using primary RP within transaction

.travis.yml
https://jira.mongodb.org/browse/PHPLIB-412
Use a Trusty image for PHP 5.5, since it is not available on Xenial.
Based on https://github.com/mongodb/mongo-php-driver/pull/956
=> PHPLIB-412: Use virtualized Xenial image in Travis CI

tests/GridFS/SpecFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-414
This ensures that we use `MultipleIterator::MIT_NEED_ANY` when iterating the subject-under-test and expected output collections so that comparison does not stop prematurely if one collection containers fewer (or no) documents. This is similar to changes done in #592 for the CRUD spec test runner.
When making that improvement, I realized that the GridFS spec tests assumes that drivers _do not_ clean up orphan chunks when deleting a non-existent file despite the fact that such behavior is permitted as a "MAY" (see: [File Deletion](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#file-deletion))
=> PHPLIB-414: Improve collection comparison in GridFS spec tests

tests/SpecTests/FunctionalTestCase.php, tests/SpecTests/RetryableWritesSpecTest.php, tests/SpecTests/retryable-writes/bulkWrite-serverErrors.json, tests/SpecTests/retryable-writes/bulkWrite.json, tests/SpecTests/retryable-writes/deleteMany.json, tests/SpecTests/retryable-writes/deleteOne-serverErrors.json, tests/SpecTests/retryable-writes/deleteOne.json, tests/SpecTests/retryable-writes/findOneAndDelete-serverErrors.json, tests/SpecTests/retryable-writes/findOneAndDelete.json, tests/SpecTests/retryable-writes/findOneAndReplace-serverErrors.json, tests/SpecTests/retryable-writes/findOneAndReplace.json, tests/SpecTests/retryable-writes/findOneAndUpdate-serverErrors.json, tests/SpecTests/retryable-writes/findOneAndUpdate.json, tests/SpecTests/retryable-writes/insertMany-serverErrors.json, tests/SpecTests/retryable-writes/insertMany.json, tests/SpecTests/retryable-writes/insertOne-serverErrors.json, tests/SpecTests/retryable-writes/insertOne.json, tests/SpecTests/retryable-writes/replaceOne-serverErrors.json, tests/SpecTests/retryable-writes/replaceOne.json, tests/SpecTests/retryable-writes/updateMany.json, tests/SpecTests/retryable-writes/updateOne-serverErrors.json, tests/SpecTests/retryable-writes/updateOne.json
https://jira.mongodb.org/browse/PHPLIB-307
This depends on WriteResult accessibility for bulk write errors ([PHPC-1373](https://jira.mongodb.org/browse/PHPC-1373)) and `retryWrites=true` by default ([PHPC-1324](https://jira.mongodb.org/browse/PHPC-1324)); however, the test runner can work around that for the time being and we can revisit those with TODO items after bumping to `ext-mongodb` 1.6.0.
=> PHPLIB-307: Retryable writes test runner

tests/TestCase.php
b175a3f950d42ed4f289972937dfcc1ca6f9ebc1 upgraded PHPUnit to 5.7, so these are no longer needed.
=> Remove BC test methods for PHPUnit 4.x

tests/SpecTests/ChangeStreamsSpecTest.php, tests/SpecTests/CommandExpectations.php, tests/SpecTests/Context.php, tests/SpecTests/DocumentsMatchConstraint.php, tests/SpecTests/DocumentsMatchConstraintTest.php, tests/SpecTests/ErrorExpectation.php, tests/SpecTests/FunctionalTestCase.php, tests/SpecTests/Operation.php, tests/SpecTests/ResultExpectation.php, tests/SpecTests/RetryableWritesSpecTest.php, tests/SpecTests/TransactionsSpecTest.php, tests/SpecTests/change-streams/README.rst, tests/SpecTests/change-streams/change-streams-errors.json, tests/SpecTests/change-streams/change-streams-errors.yml, tests/SpecTests/change-streams/change-streams.json, tests/SpecTests/change-streams/change-streams.yml
Depends on https://github.com/mongodb/mongo-php-library/pull/615. Can be rebased after that is merged.
https://jira.mongodb.org/browse/PHPLIB-366
=> PHPLIB-366: Change streams test runner

src/ChangeStream.php, tests/SpecTests/ChangeStreamsProseTest.php, tests/SpecTests/FunctionalTestCase.php
https://jira.mongodb.org/browse/PHPLIB-443
This PR is a single commit, but depends on https://github.com/mongodb/mongo-php-library/pull/616.
The fifth prose test serves as a regression test for this bug.
=> PHPLIB-443: Propagate non-resumable errors during ChangeStream iteration

src/ChangeStream.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-442
This extracts common logic in next() and rewind() to a new method, which is now also called by resume() after it rewinds the internal iterator.
=>  PHPLIB-442: Ensure change stream resume token is updated after resume

tests/DocumentationExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-381
=> PHPLIB-381: Update fourth change stream example

tests/SpecTests/ChangeStreamsSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-416
The fix from PHPLIB-442 also allows this test to pass.
=> PHPLIB-416: Remove skip for consecutive resume test

src/ChangeStream.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-445
Note: this will conflict with https://github.com/mongodb/mongo-php-library/pull/621, so it'd be preferable to resolve that first and then rebase this after merging up to master.
=> PHPLIB-445: Leave key as-is if ChangeStream::next() fails to extract resume token

src/ChangeStream.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-441
=> PHPLIB-441: Increment ChangeStream key consistently when resuming

tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-441
Since consecutive calls to rewind() are NOPs, this must invoke next() to trigger a second resume. Additionally, leave a note about how this test might change with PHPLIB-448.
=> PHPLIB-441: Fix testResumeMultipleTimesInSuccession

src/Operation/Watch.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-454
=> PHPLIB-454: Fix test failures when startAtOperationTime is unsupported

src/Operation/Watch.php, tests/Collection/CollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-368
Aggregate::execute() already checks for this. This also adds a note in CollectionFunctionalTest that watch() is prohibited within a transaction, as is done for other methods.
=> PHPLIB-368: Remove redundant check for RC within transaction

docs/includes/apiargs-MongoDBClient-method-watch-option.yaml, docs/includes/apiargs-MongoDBCollection-method-watch-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-watch-option.yaml, docs/includes/apiargs-method-watch-option.yaml, src/Operation/Watch.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-407
Note: this does not address using the startAfter option for resuming. That will be implemented in PHPLIB-411 with the introduction of a resume token accessor method and support for postBatchResumeToken.
=> PHPLIB-407: Support startAfter change stream option

src/ChangeStream.php, src/Model/TailableCursorIterator.php, src/Operation/Watch.php, tests/Model/TailableCursorIteratorTest.php, tests/Operation/WatchFunctionalTest.php, tests/SpecTests/ChangeStreamsProseTest.php, tests/SpecTests/ChangeStreamsSpecTest.php, tests/SpecTests/Operation.php
https://jira.mongodb.org/browse/PHPLIB-451
https://jira.mongodb.org/browse/PHPLIB-416
A few highlights from the commit messages:
* Write ops in change stream tests now use `w:majority` to avoid spurious test failures due to timing.
* Introduced an internal TailableCursorIterator class, which can be used to ensure that rewinding is a NOP (i.e. `getMore` will not be executed) for tailable cursors with an empty `firstBatch`.
* Watch tests were revised to no longer expect `rewind()` to encounter an error and resume. In most tests, `rewind()` is a NOP because the change stream has no events to return upon creation.
* Since Watch now always executes aggregate commands with APM, the check for `startAtOperationTime` support was moved to `createResumeCallable()`.
* Various assertions for …
=> PHPLIB-451: ChangeStream::rewind() should never execute getMore

tests/Collection/CollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-368
=> PHPLIB-368: Use PHP 5.6+ compatible syntax

docs/includes/apiargs-MongoDBDatabase-method-aggregate-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-aggregate-param.yaml, docs/includes/apiargs-aggregate-option.yaml, docs/reference/class/MongoDBDatabase.txt, docs/reference/method/MongoDBDatabase-aggregate.txt, docs/tutorial/crud.txt, src/Collection.php, src/Database.php, src/functions.php, tests/SpecTests/CommandExpectations.php, tests/SpecTests/Context.php, tests/SpecTests/CrudSpecTest.php, tests/SpecTests/Operation.php, tests/SpecTests/ResultExpectation.php, tests/SpecTests/crud/aggregate-merge.json, tests/SpecTests/crud/aggregate-out-readConcern.json, tests/SpecTests/crud/bulkWrite-arrayFilters.json, tests/SpecTests/crud/db-aggregate.json, tests/SpecTests/crud/updateWithPipelines.json
https://jira.mongodb.org/browse/PHPLIB-402
I've extracted the `is_in_transaction` helper from `MongoDB\Collection` in a separate to functions since we need it more often. I've also decided to extract the options for the aggregate helper to a common file to avoid unnecessary duplication of option descriptions.
=> PHPLIB-402: Add aggregate helper to Database class

docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-aggregate-option.yaml, docs/includes/apiargs-aggregate-option.yaml, src/Collection.php, src/Database.php, src/Operation/Aggregate.php, src/functions.php, tests/Collection/CrudSpecFunctionalTest.php, tests/SpecTests/Context.php, tests/SpecTests/CrudSpecTest.php, tests/SpecTests/Operation.php
https://jira.mongodb.org/browse/PHPLIB-438
=> PHPLIB-438: Unify handling for write stages in aggregation pipelines

.travis.yml
http://jira.mongodb.org/browse/PHPLIB-460
With these changes, we're preparing the build file to do more than just running tests. To make feedback more immediate and to save resources, the build now runs a smoke screen testing step before running the full build pipeline. This should catch simple errors and will also do static analysis before running all tests. Once smoke screen testing has completed, the full build pipeline will be executed.
This PR also adds testing against PHP 7.4 with the build currently failing due to a deprecation:
```
Function ReflectionType::__toString() is deprecated
/home/travis/build/alcaeus/mongo-php-library/tests/Operation/ExplainTest.php:17
```
This will be fixed at a later step once I've figured out what's causing this.
=> PHPLIB-460: Use travis build stages

src/Operation/Aggregate.php, tests/SpecTests/CommandExpectations.php
* Don't collect unexpected extra commands in spec tests: as discussed in https://github.com/mongodb/mongo-php-library/pull/642#discussion_r307108104, it makes more sense to not collect commands that we're not going to be asserting against instead of dropping them later.
* While the docs for the aggregation helpers in `MongoDB\Database` and `MongoDB\Collection` have been updated with respect to read concerns and write stages, the documentation in the `MongoDB\Operation\Aggregate` wasn't. This is done in this PR.
=> Refactor command logging for spec tests and fix docs

src/Exception/ResumeTokenException.php, src/Operation/Aggregate.php, tests/SpecTests/CommandExpectations.php
https://jira.mongodb.org/browse/PHPLIB-401
=> PHPLIB-401: ResumeTokenException extends RuntimeException

tests/Collection/CrudSpecFunctionalTest.php, tests/GridFS/SpecFunctionalTest.php, tests/SpecTests/ChangeStreamsSpecTest.php, tests/SpecTests/CommandMonitoringSpecTest.php, tests/SpecTests/CrudSpecTest.php, tests/SpecTests/RetryableWritesSpecTest.php, tests/SpecTests/TransactionsSpecTest.php
This fixes issues in tools like PhpStorm that are not able to show test progress when the test name changes.
=> Use named datasets in spec tests

.travis.yml, tests/FunctionalTestCase.php
In preparation for PHPLIB-430, this ensures that relevant functionality works on replica set clusters with a single `mongos` node.
Note: tests related to change streams are disabled on this cluster while I investigate an issue with `getMore` commands not returning data on the first call after inserting data and only returning data on a subsequent call to `getMore`.
=> Run tests on sharded cluster with Replica Sets

mongo-orchestration/sharded_clusters/cluster.json, mongo-orchestration/sharded_clusters/cluster_replset.json, tests/FunctionalTestCase.php, tests/Operation/WatchFunctionalTest.php, tests/SpecTests/RetryableWritesSpecTest.php, tests/SpecTests/TransactionsSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-430
This PR changes the mongo-orchestration configs for sharded cluster to include a second mongos node for each. To ensure that we're not running into errors due to running subsequent commands on separate mongos instances, the tests modify the connection URI to only use a single mongos node, unless explicitly requested to use multiple nodes. This is currently only the case in select tests for the retryable-writes and transaction specs.
Note that some tests had to be disabled: 
* Transaction tests on these clusters fail due to an error thrown in the driver, see https://github.com/mongodb/mongo-php-driver/pull/984 for more details. Once this has been removed in the driver, we can then run these tests again.
* Retryable write tests are skipped on …
=> PHPLIB-430: Add test environment with multiple mongos nodes

tests/FunctionalTestCase.php, tests/Operation/WatchFunctionalTest.php
Since failCommand is only available on newer server versions and need a special parameter to be enabled, the configureFailPoint helper now automatically skips a test if failCommand is not available, instead of failing the test with an error.
=> Automatically skip tests if failCommand is not available

composer.json, tests/SpecTests/DocumentsMatchConstraint.php, tests/SpecTests/DocumentsMatchConstraintTest.php, tests/bootstrap.php
https://jira.mongodb.org/browse/PHPLIB-459
This improves the error messages for the above constraint by no longer just printing the expected and actual object, but also by giving a reason for the failure and showing a diff. Comparison follows.
Instead of simply comparing values, this uses `sebastian/comparator` internally to compare object values and uses its exceptions to generate failure messages.
---
Here's an actual comparison failure before:
```
Failed asserting that stdClass Object &000000001f899da5000000004f623c22 (
'update' => 'test'
'ordered' => true
'$db' => 'crud-tests'
'lsid' => stdClass Object &000000001f899dc2000000004f623c22 (
'id' => MongoDB\BSON\Binary Object &000000001f899daa000000004f623c22 (
'data' => '(?z??A??-y{?T?C'
'type' => 4
)
)
'updates' => Array &0 (
0 => …
```
=> PHPLIB-459: Support better failure descriptions in DocumentsMatchConstraint

src/ChangeStream.php, src/Operation/Watch.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-457
=> PHPLIB-457: Audit and implement any missing change stream spec prose tests

.travis.yml, .travis/setup_mo.sh, tests/Collection/CollectionFunctionalTest.php, tests/FunctionalTestCase.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/WatchFunctionalTest.php, tests/SpecTests/ChangeStreamsSpecTest.php, tests/SpecTests/ErrorExpectation.php
This pulls in alpha3 of the driver for travis-ci builds and updates the build pipeline to test against MongoDB 4.2.0 by default. MongoDB 4.0.12 is still tested as part of the "older server versions" sections in travis-ci.
This PR also fixes some leftover warnings from the PHPUnit upgrade that was done in #665.
=> Update to latest ext-mongodb and MongoDB server versions

docs/includes/apiargs-MongoDBCollection-common-param.yaml, src/Operation/FindAndModify.php, src/Operation/FindOneAndUpdate.php, src/Operation/ReplaceOne.php, src/Operation/Update.php, src/Operation/UpdateMany.php, src/Operation/UpdateOne.php, src/functions.php, tests/FunctionsTest.php, tests/Operation/FindOneAndUpdateTest.php, tests/Operation/UpdateManyTest.php, tests/Operation/UpdateOneTest.php, tests/SpecTests/CrudSpecTest.php, tests/SpecTests/crud/updateWithPipelines.json
https://jira.mongodb.org/browse/PHPLIB-418
=> PHPLIB-418: Add the ability to specify a pipeline to an update command

mongo-orchestration/replica_sets/replicaset-old.json, mongo-orchestration/replica_sets/replicaset-one-node.json, mongo-orchestration/replica_sets/replicaset.json, tests/SpecTests/PrimaryStepDownSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-467
=> PHPLIB-467: Connections survive primary step-down

src/Model/ChangeStreamIterator.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-456
Contrary to the suggestion in the ticket, the implementation could not happen in `MongoDB\ChangeStream`. Doing so would've required catching the `ResumeTokenException` thrown in `MongoDB\Model\ChangeStreamIterator` and rethrowing it after updating its `valid` flag. To avoid this, I added the logic to the iterator itself, which now requires the cursor to be valid and also have a valid resume token to be considered valid.
=> PHPLIB-456: Always invalidate ChangeStream position if iteration fails

tests/Operation/WatchFunctionalTest.php
ChangeStream::getResumeToken() did not exist at the time this test was written; however, we do this assertion in testStartAfterOption().
This was originally suggested in https://github.com/mongodb/mongo-php-library/pull/659, but fell out as a related change to `testStartAfterOption()` was no longer needed.
=> Assert initial resume token in resumeAfter test

src/Operation/WithTransaction.php, src/functions.php, tests/SpecTests/ErrorExpectation.php, tests/SpecTests/Operation.php, tests/SpecTests/TransactionsSpecTest.php, tests/SpecTests/transactions-convenient-api/callback-aborts.json, tests/SpecTests/transactions-convenient-api/callback-commits.json, tests/SpecTests/transactions-convenient-api/callback-retry.json, tests/SpecTests/transactions-convenient-api/commit-retry.json, tests/SpecTests/transactions-convenient-api/commit-transienttransactionerror-4.2.json, tests/SpecTests/transactions-convenient-api/commit-transienttransactionerror.json, tests/SpecTests/transactions-convenient-api/commit-writeconcernerror.json, tests/SpecTests/transactions-convenient-api/commit.json, tests/SpecTests/transactions-convenient-api/transaction-options.json
https://jira.mongodb.org/browse/PHPLIB-468
As discussed, this is a prototype implementation for the convenient API for transactions. I've also added the spec tests and adapted the transaction test runner to cover these as well to avoid code duplication.
=> PHPLIB-468: Implement Convenient API for Transactions

.travis.yml, src/Client.php, src/Collection.php, src/Database.php, src/Operation/Watch.php, src/functions.php, tests/FunctionalTestCase.php, tests/SpecTests/CommandExpectations.php, tests/SpecTests/Context.php, tests/SpecTests/Operation.php, tests/SpecTests/RetryableWritesSpecTest.php, tests/SpecTests/TransactionsSpecTest.php, tests/SpecTests/transactions/errors-client.json, tests/SpecTests/transactions/retryable-abort.json, tests/SpecTests/transactions/retryable-commit.json
https://jira.mongodb.org/browse/PHPLIB-466
=> PHPLIB-466: Support mongos pinning for sharded transactions

tests/Operation/WatchFunctionalTest.php
The logic of this is the same as in the test for the C driver ([see link](https://github.com/mongodb/mongo-c-driver/blob/9994d4568176ec1503c50c92e68a6b0f2ee2bf2a/src/libmongoc/tests/test-mongoc-change-stream.c#L2291..L2295)), which also uses `startAtOperationTime` to ensure a non-empty batch is returned when running without either `startAfter` and `resumeAfter` option.
=> PHPLIB-457: Add missing change stream prose test 14

docs/includes/apiargs-common-option.yaml
The operation field isn't used for anything in our documentation. This was introduced in d5c501a2ae0ee3fa7295d653e7061cbe643df029 and it looks like we missed cleaning it up in later commits that changed every other operation field to null.
=> Clear value for obsolete options field

docs/includes/apiargs-function-with_transaction-param.yaml, docs/reference.txt, docs/reference/function/with_transaction.txt, docs/reference/functions.txt
https://jira.mongodb.org/browse/PHPLIB-468
I ended up adding a functions chapter after all, as I didn't want to just put the function somewhere. The tutorial is copied from the documentation examples, I feel that is most familiar. We can always add more examples if we feel that's necessary.
=> PHPLIB-468: Add documentation for with_transaction

tests/SpecTests/ErrorExpectation.php, tests/SpecTests/Operation.php
https://jira.mongodb.org/browse/PHPLIB-482
While looking at [PHPLIB-481](https://jira.mongodb.org/browse/PHPLIB-481), I realised that the crud spec tests don't check error expectations. While we're unlikely to miss any errors because of this (since the return value of the operation call is most likely not going to match the expectation), I still think it's sensible to add these to the 1.5 branch to ensure we're correctly running the spec tests.
=> PHPLIB-482: Add missing error expectation to crud tests

docs/upgrade.txt
https://jira.mongodb.org/browse/PHPLIB-455
=> PHPLIB-455: Add BSON class mapping to upgrade guide

src/Operation/BulkWrite.php, tests/Operation/BulkWriteFunctionalTest.php, tests/Operation/BulkWriteTest.php, tests/SpecTests/crud/updateWithPipelines.json
https://jira.mongodb.org/browse/PHPLIB-481
=> PHPLIB-481: Add the ability to specify a pipeline to an update within bulk write

src/Collection.php, tests/Collection/CollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-485
=> PHPLIB-485: Inherit collection's typeMap in distinct

docs/includes/apiargs-MongoDBCollection-method-mapReduce-option.yaml, docs/includes/apiargs-MongoDBCollection-method-mapReduce-param.yaml, src/Operation/MapReduce.php
https://jira.mongodb.org/browse/PHPLIB-477
Contrary to the original wording suggestion, I replaced the usage of "CodeWScope" for "Javascript instance with a scope". I don't think users will be familiar with the internal nomenclature of BSON types, so this may be more understandable to the average user.
Apart from deprecating these in the documentation, we also emit an `E_USER_DEPRECATED` PHP error that can be logged with libraries like [symfony/phpunit-bridge](https://github.com/symfony/phpunit-bridge).
=> PHPLIB-477: Deprecate CodeWScope for use within the mapReduce command

src/Operation/MapReduce.php
https://jira.mongodb.org/browse/PHPLIB-480
I've skipped the `mapparams` deprecation, as it's not possible to pass that option into the command through the helper.
=> PHPLIB-480: Deprecate MapReduce options

src/Model/CachingIterator.php, tests/Model/CachingIteratorTest.php
https://jira.mongodb.org/browse/PHPLIB-501
This was discovered while investigating https://github.com/doctrine/mongodb-odm/issues/2092. The different behaviour can be seen in action here: https://3v4l.org/UIfIb. Note that when we don't specifically unset the generator, it stays around much longer even though the wrapping iterator has already been garbage collected.
=> PHPLIB-501: Prevent memory leaks from generators

src/Client.php, src/GridFS/Bucket.php, src/GridFS/WritableStream.php, src/Operation/Watch.php, tests/ClientTest.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/WritableStreamFunctionalTest.php, tests/Operation/AggregateTest.php, tests/Operation/BulkWriteTest.php, tests/Operation/FindAndModifyTest.php, tests/Operation/FindOneAndReplaceTest.php, tests/Operation/FindOneAndUpdateTest.php, tests/Operation/InsertManyTest.php, tests/Operation/UpdateTest.php, tests/Operation/WatchTest.php, tests/TestCase.php
https://jira.mongodb.org/browse/PHPLIB-494
This fixes a few validation errors where it is possible to use `null` as a valid value for an option, resulting in undefined behaviour. All other options that have a default value are directly checked for their type, without an `isset` check to guard against a missing option since it should always be present due to the array union.
=> PHPLIB-494: Fix validation of options with default values

mongo-orchestration/sharded_clusters/cluster_replset.json, tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php, tests/Operation/WatchFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-461
Due to the way `getMore` works on sharded clusters, we can't rely on the first `getMore` call after an insert to return the data we expect. I'll quote the response from the query team to my questions about why `getMore` behaves this way.
> First, it will be useful to understand the semantics of `getMore` on a tailable `awaitData` cursor such as that created by `$changeStream`:
> 1. If there are documents available when the `getMore` starts running, then `getMore` will read up to `batchSize` OR `EOF`, whichever comes first. It will then return immediately without waiting for any further results.
> 2. If there are no documents available when the `getMore` starts running, it will wait up to the specified `awaitData` timeout to see if any documents …
=> PHPLIB-461: Fix functional tests for change streams on sharded clusters

.travis.yml, .travis/install-extension.sh
This allows us to later switch to always test against dev driver versions until the RC phase of the extension, saving us the trouble of releasing alpha builds of the driver for internal testing purposes.
=> PHPLIB-519: Allow testing against development driver versions

docs/includes/apiargs-MongoDBClient-method-createClientEncryption-param.yaml, docs/reference/class/MongoDBClient.txt, docs/reference/method/MongoDBClient-createClientEncryption.txt, src/Client.php, tests/ClientTest.php
https://jira.mongodb.org/browse/PHPLIB-512
Note: contains commits from #708, only the last two commits are for the ticket in question.
=> PHPLIB-512: Expose ClientEncryption API in MongoDB\Client

tests/SpecTests/Operation.php
https://jira.mongodb.org/browse/PHPLIB-502
This makes use of the new `getTransactionState` accessor introduced in https://github.com/mongodb/mongo-php-driver/pull/1061 to assert against the transaction state in spec tests.
=> PHPLIB-502: Assert against transaction state

tests/SpecTests/Context.php, tests/SpecTests/FunctionalTestCase.php
Server versions < 3.4 do not support write concerns for drop commands. Rather than pass the context's write options directly to drop(), filter them through the Collection class so it can decide to inherit them based on the server's wire version.
Likewise for executing find() on the output collection.
Cherry-picked from https://github.com/mongodb/mongo-php-library/pull/711. This didn't come up sooner because all existing CRUD and transaction tests have `minServerVersion` requirements > 3.4.
=> Rely on Collection to apply read/write opts for old servers

docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, docs/includes/apiargs-MongoDBCollection-method-find-option.yaml, docs/includes/apiargs-MongoDBCollection-method-findOne-option.yaml, docs/includes/apiargs-MongoDBCollection-method-replaceOne-option.yaml, docs/includes/apiargs-MongoDBCollection-method-updateMany-option.yaml, docs/includes/apiargs-MongoDBCollection-method-updateOne-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-aggregate-option.yaml, docs/includes/apiargs-aggregate-option.yaml, docs/includes/apiargs-common-option.yaml, src/Exception/UnsupportedException.php, src/Operation/ReplaceOne.php, src/Operation/Update.php, src/Operation/UpdateMany.php, src/Operation/UpdateOne.php, tests/SpecTests/crud/bulkWrite-update-hint.json, tests/SpecTests/crud/find-allowdiskuse.json, tests/SpecTests/crud/replaceOne-hint.json, tests/SpecTests/crud/updateMany-hint.json, tests/SpecTests/crud/updateOne-hint.json
https://jira.mongodb.org/browse/PHPLIB-491
=> PHPLIB-491: Support hint for update command

.travis.yml, composer.json, phpcs.xml.dist, src/Client.php, src/Collection.php, src/Database.php, src/GridFS/Bucket.php, src/GridFS/StreamWrapper.php, src/Model/ChangeStreamIterator.php, src/Operation/Aggregate.php, src/Operation/FindAndModify.php, src/Operation/WithTransaction.php, tests/Collection/CrudSpecFunctionalTest.php, tests/CommandObserver.php, tests/GridFS/ReadableStreamFunctionalTest.php, tests/GridFS/SpecFunctionalTest.php, tests/Model/CachingIteratorTest.php, tests/SpecTests/ChangeStreamsSpecTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/CommandMonitoringSpecTest.php, tests/SpecTests/Context.php, tests/SpecTests/CrudSpecTest.php, tests/SpecTests/ErrorExpectation.php, tests/SpecTests/FunctionalTestCase.php, tests/SpecTests/Operation.php, tests/SpecTests/RetryableReadsSpecTest.php, tests/SpecTests/RetryableWritesSpecTest.php, tests/SpecTests/TransactionsSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-529
Follows https://github.com/mongodb/mongo-php-driver/pull/1096.
=> PHPLIB-529: Drop support for PHP 5.6

.travis.yml, src/MapReduceResult.php, src/Model/CollectionInfoCommandIterator.php, src/Operation/ListCollections.php, tests/Collection/CollectionFunctionalTest.php, tests/Operation/MapReduceFunctionalTest.php, tests/SpecTests/CrudSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-530, https://jira.mongodb.org/browse/PHPLIB-515
While working on #721, I noticed that we don't test against MongoDB 4.3. This PR adds 4.3 to the build pipeline and fixes test failures that come from this. Also removes execution stats from MapReduce (PHPLIB-515).
=> PHPLIB-530: Test against MongoDB 4.3

.travis.yml, composer.json, docs/includes/apiargs-MongoDBCollection-method-find-option.yaml, docs/includes/apiargs-MongoDBCollection-method-findOne-option.yaml, docs/includes/apiargs-MongoDBGridFSBucket-method-find-option.yaml, docs/includes/apiargs-MongoDBGridFSBucket-method-findOne-option.yaml, src/Operation/Find.php, tests/SpecTests/CrudSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-500
PHP 5 build failures will be fixed by #720.
=>  PHPLIB-500: Support for allowDiskUse on find operations

.travis.yml, tests/SpecTests/CommandExpectations.php, tests/SpecTests/Operation.php, tests/SpecTests/transactions/create-collection.json, tests/SpecTests/transactions/create-index.json
This is a proof of concept PR for https://github.com/mongodb/specifications/pull/749.
=> Test collection/index creation within transaction

tests/SpecTests/CommandExpectations.php, tests/SpecTests/Context.php, tests/SpecTests/ErrorExpectation.php, tests/SpecTests/Operation.php, tests/SpecTests/ReadWriteConcernSpecTest.php, tests/SpecTests/ResultExpectation.php, tests/SpecTests/read-write-concern/operation/default-write-concern-2.6.json, tests/SpecTests/read-write-concern/operation/default-write-concern-3.2.json, tests/SpecTests/read-write-concern/operation/default-write-concern-3.4.json, tests/SpecTests/read-write-concern/operation/default-write-concern-4.2.json
https://jira.mongodb.org/browse/PHPLIB-536
=> PHPLIB-536: Add spec tests for default write concern

composer.json, docs/includes/apiargs-MongoDBClient-method-construct-driverOptions.yaml, src/Client.php, tests/ClientTest.php
https://jira.mongodb.org/browse/PHPLIB-516
=> PHPLIB-516: Append PHPLIB version information to handshake data

docs/reference/method/MongoDBCollection-countDocuments.txt, docs/reference/method/MongoDBCollection-createIndex.txt
https://jira.mongodb.org/browse/PHPLIB-434
=> PHPLIB-434: Add note about performance of countDocuments

src/GridFS/CollectionWrapper.php, tests/GridFS/BucketFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-522
Instead of using a strict array comparison (which checks order of elements as well as type-safe value checks), we are now using a `MultipleIterator` to iterate over the expected and actual keys in order. Since we assume numeric values for index sort only, we check if the actual value is numeric, then cast to int to cover for some drivers (e.g. the shell) creating indexes with float values for sort.
For the chunks index, we attempt to create the index even if an index with the same keys but non-unique exists. This will cause an exception, but there is no other way to work around this issue. Other index options are not considered for either index.
=> PHPLIB-522: Loosen index equality checks for GridFS

tests/SpecTests/crud/bulkWrite-arrayFilters-clientError.json, tests/SpecTests/transactions/error-labels.json
Syncs spec tests for [PHPLIB-555](https://jira.mongodb.org/browse/PHPLIB-555) and [PHPLIB-551](https://jira.mongodb.org/browse/PHPLIB-551).
=> Sync spec tests

docs/reference/method/MongoDBCollection-explain.txt, src/Operation/Aggregate.php, src/Operation/Explain.php, src/Operation/Explainable.php, tests/Operation/ExplainFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-559
To be consistent with other methods, passing an `Aggregate` instance to `explain` on servers < 4.0 will throw an exception, as these versions don't support passing an `aggregate` command to `explain`. Users that still use older MongoDB versions can continue to use the `explain` flag in `aggregate`, which remains unchanged in this PR.
=> PHPLIB-559: Make aggregate command explainable

tests/SpecTests/PrimaryStepDownSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-561
While the test is currently skipped due to issues with subsequent tests (see [PHPLIB-471](https://jira.mongodb.org/browse/PHPLIB-471)), we can still make the change to retry `replSetStepDown` up to 10 times.
=> PHPLIB-561: Retry replSetStepDown in connection failover test

src/Database.php, tests/Database/DatabaseFunctionalTest.php, tests/FunctionalTestCase.php
https://jira.mongodb.org/browse/PHPLIB-558
~Same as with https://github.com/mongodb/mongo-php-driver/pull/1144, I've targeted the upcoming minor release for this fix, but can back port to the current stable release for a July patch release.~
=> PHPLIB-558: Don't inherit read preference in Database::command

tests/SpecTests/crud/bulkWrite-update-validation.json, tests/SpecTests/crud/replaceOne-validation.json, tests/SpecTests/crud/updateMany-validation.json, tests/SpecTests/crud/updateOne-validation.json
https://jira.mongodb.org/browse/PHPLIB-560
=> PHPLIB-560: Tests for update/replacement validation

src/Model/CachingIterator.php
This was overlooked from 52df7a112e760b595a3485f50c23adf0591b95e8
Context: https://github.com/mongodb/mongo-php-library/pull/758#discussion_r449075127
=> Remove mention of Generator in CachingIterator comments

docs/reference/method/MongoDBClient-listDatabaseNames.txt, docs/reference/method/MongoDBDatabase-listCollectionNames.txt, docs/reference/method/MongoDBDatabase-listCollections.txt, src/Client.php, src/Command/ListCollections.php, src/Command/ListDatabases.php, src/Database.php, src/Model/CallbackIterator.php, src/Operation/ListCollectionNames.php, src/Operation/ListDatabaseNames.php, tests/ClientFunctionalTest.php, tests/Command/ListCollectionsTest.php, tests/Command/ListDatabasesTest.php, tests/Database/CollectionManagementFunctionalTest.php, tests/Operation/ListCollectionNamesFunctionalTest.php, tests/Operation/ListDatabaseNamesFunctionalTest.php, tests/SpecTests/Operation.php, tests/SpecTests/RetryableReadsSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-547
=> PHPLIB-547: Add helpers to list database and collection names

docs/index.txt, docs/reference/method/MongoDBCollection-createIndex.txt, docs/reference/method/MongoDBCollection-deleteMany.txt, docs/reference/method/MongoDBCollection-deleteOne.txt, docs/tutorial/example-data.txt, docs/tutorial/install-php-library.txt
https://jira.mongodb.org/browse/PHPLIB-523
https://jira.mongodb.org/browse/PHPLIB-524
A third commit also fixes various syntax/formatting issues I noticed while working on these two pages.
Opening against v1.1 as I can apply there and merge up to master so this changes applies to all published versions of the manual. Separately, I'd propose we consider hiding some older version in the drop-down. I can't imagine that docs for v1.1 is very relevant for anyone.
To build locally from a clone of https://github.com/mongodb/docs-php-library with this repo cloned in `../phplib`:
```
#!/bin/sh
rm -r build/master
rsync -a --delete ../phplib/docs/ source/
giza -l warning make publish
```
You can then serve the docs with:
```
#!/bin/sh
php -S localhost:8080 -t ./build/master/html/
```
=> PHPLIB-523, PHPLIB-524: Restructure docs index and install pages

src/ChangeStream.php, tests/SpecTests/change-streams/change-streams-errors.json, tests/SpecTests/change-streams/change-streams-resume-whitelist.json
https://jira.mongodb.org/browse/PHPLIB-566
https://jira.mongodb.org/browse/PHPLIB-567
POC of https://github.com/mongodb/specifications/pull/834 for [DRIVERS-1308](https://jira.mongodb.org/browse/DRIVERS-1308). Language ticket is pending.
=> PHPLIB-566, PHPLIB-567: Treat CursorNotFound as a resumable change stream error and sync tests

.travis.yml, src/Operation/DropCollection.php, tests/Operation/DropCollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-570
Changes the try/catch to CommandException and allows the original command reply to be returned instead of a synthetic document (based on pre-3.2 server responses). Also uses MongoDB 3.0 for prefer-lowest CI environment.
=> PHPLIB-570: Consult NamespaceNotFound error code in DropCollection

.travis.yml, tests/Operation/DropCollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-570
Fix CI failures from https://github.com/mongodb/mongo-php-library/pull/768
Will ensure I wait for CI results before merging this time :stuck_out_tongue:
=> PHPLIB-570: Fix CI failures from previous PR

docs/reference/class/MongoDBClient.txt, docs/reference/class/MongoDBDatabase.txt, docs/reference/method/MongoDBClient-listDatabaseNames.txt, docs/reference/method/MongoDBClient-listDatabases.txt
https://jira.mongodb.org/browse/PHPLIB-547
Fixes a typo from https://github.com/mongodb/mongo-php-library/pull/758
=> PHPLIB-547: Fix links to new enumeration methods

tests/Collection/CollectionFunctionalTest.php, tests/Operation/WatchFunctionalTest.php
Related: https://jira.mongodb.org/browse/PHPLIB-461
=> Fix flaky test failures due to timeouts on mongos

tests/SpecTests/change-streams/change-streams-errors.json, tests/SpecTests/change-streams/change-streams.json
https://jira.mongodb.org/browse/PHPLIB-580
Synced with mongodb/specifications@90d96dabac9c645f922f2fcad1940c5c9a83e2b7
=> PHPLIB-580: Correctly express lack of event assertions in change stream tests

phpcs.xml.dist, src/GridFS/Bucket.php, src/GridFS/Exception/StreamException.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/UnusableStream.php
PHPLIB-425
I'm not too happy with throwing a generic `StreamException`, but there really isn't more information we can reliably add to the error messages (except for mentioning whether it happened on up- or download). Targeting 1.8 for this change, since we're throwing new exceptions in three methods, which I don't want to add in a patch release. Happy to retarget the PR to 1.7 if we're not worried about the new exceptions.
=> PHPLIB-425: GridFS methods should throw if stream copying fails

src/GridFS/StreamWrapper.php, tests/GridFS/BucketFunctionalTest.php
PHPLIB-345
This applies a suggestion by @sgolemon to avoid PHP trying to use previously destroyed stream objects. The behaviour can be shown by leaving a dangling writable stream, which causes errors on shutdown. The workaround ensures that the stream wrapper instance "forgets" that it owned a stream wrapper, as `StreamWrapper::stream_close` is called after `StreamWrapper::__destruct`.
=> PHPLIB-345: Fix PHP shutdown error with dangling writable streams

tests/Database/DatabaseFunctionalTest.php, tests/FunctionalTestCase.php
This function was introduced in 7a54cbe82f6cf07962410d7afa3f2f8c1d3e5f6d and only used in one test.
=> Fix logic for isReplicaSet

.evergreen/config.yml, .evergreen/run-tests.sh, phpunit.xml.dist, tests/SpecTests/AtlasDataLakeSpecTest.php, tests/SpecTests/atlas_data_lake/aggregate.json, tests/SpecTests/atlas_data_lake/estimatedDocumentCount.json, tests/SpecTests/atlas_data_lake/find.json, tests/SpecTests/atlas_data_lake/getMore.json, tests/SpecTests/atlas_data_lake/listCollections.json, tests/SpecTests/atlas_data_lake/listDatabases.json, tests/SpecTests/atlas_data_lake/runCommand.json
https://jira.mongodb.org/browse/PHPLIB-569
Tests synced with mongodb/specifications@bdc283c5279490389ef1b2c36fc5058cae95f755
This is waiting on Evergreen migration ([PHPLIB-469](https://jira.mongodb.org/browse/PHPLIB-469)). In the meantime, I've been testing locally with the following `phpunit.xml` modification:
```
<env name="MONGODB_URI" value="mongodb://mhuser:pencil@127.0.0.1:27017"/>
```
=> PHPLIB-569: Atlas Data Lake spec tests

.evergreen/config.yml, .evergreen/run-tests.sh, composer.json, phpunit.evergreen.xml, tests/EvergreenLogListener.php
PHPLIB-582
This ticket unfortunately is incomplete due to a few issues with the build system.
Reporting test results using `attach.results` does not allow us to easily add logs (e.g. information about assertion failures, traces, test output, etc.) to the test results. This is possible using `attach.xunit_results`, but I could not get that command to read the results files written by PHPUnit. For one, PHPUnit reports nested test suites (a feature of JUnit), which the parser in evergreen does not understand. This should be fixed by [EVG-12951](https://jira.mongodb.org/browse/EVG-12951).
While I had a temporary listener that worked around this by flattening the file (and to report a single test suite containing all tests), this still didn't yield any results. This went as far as Evergreen …
=> PHPLIB-582: Create JSON test result file for evergreen

.evergreen/config.yml, .evergreen/install-dependencies.sh
PHPLIB-563
This PR makes a few last changes to the pipeline:
- Exclude rhel74-zseries and rhel71-power8 because they don't pass or don't even start. Since this also affects PHPC, I'd take care of this in the PHPC follow-up epic.
- Add tests against lowest supported versions. We test the base driver release and oldest composer dependencies against all server versions.
- PHP 7.0 now also works on Debian 9.2 an RHEL 7.0. I was able to work around the pecl errors that prevented running on those platforms
Pull requests currently test the "test-php-versions" pipeline, which tests the driver on all PHP versions and several operating systems against the latest server. I'm open to adding additional variants/tasks to the mix, but thought that those were a good starting point.
=> PHPLIB-563: Finalise PHP runtime axis

tests/SpecTests/DocumentsMatchConstraint.php
Fixes a typo from 0b923b08985fe369d50d071fefa31e03b221b6fd
=> Consult $actualValue when setting $actualType

src/Model/IndexInput.php, src/Operation/CreateIndexes.php, tests/Model/IndexInputTest.php
https://jira.mongodb.org/browse/PHPLIB-591
Also adds an extra option to the BSON serialization test.
=> PHPLIB-591: CreateIndexes should not specify "ns" for index specifications

.evergreen/config.yml, .travis.yml
With travis-ci experiencing long queues, it makes sense to reduce the size of the build pipeline and exclude all variants that are being tested on evergreen. We now run a set of smokescreen tests on PHP 7.4, `phpcs` checks on PHP 7.1 (lowest version supported by doctrine/coding-standard) and PHP 8 builds for each topologies (as PHP 8 is not supported on Evergreen yet).
=> Update build pipeline

docs/reference/method/MongoDBCollection-aggregate.txt, docs/reference/method/MongoDBDatabase-aggregate.txt, docs/tutorial/collation.txt
=> PHPLIB-577: Add examples for aggregation methods

.evergreen/config.yml, composer.json, docs/tutorial/tailable-cursor.txt, src/GridFS/ReadableStream.php, src/Model/CachingIterator.php, src/Model/CallbackIterator.php, tests/Collection/CrudSpecFunctionalTest.php, tests/GridFS/SpecFunctionalTest.php, tests/Operation/FindFunctionalTest.php, tests/SpecTests/FunctionalTestCase.php, tests/SpecTests/PrimaryStepDownSpecTest.php, tests/UnifiedSpecTests/CollectionData.php
PHPLIB-598
@jmikola I decided to clean up the tailable cursor docs as well and add a note about needing to wrap cursors in an `IteratorIterator` before manually iterating. Let me know if you'd rather keep the original documentation intact and add a note that wrapping is no longer necessary with 1.9.0+.
=> PHPLIB-598: Clean up cursor usages to account for iterator changes

src/Model/CachingIterator.php, tests/Model/CachingIteratorTest.php
PHPLIB-608
Note that this does not affect 1.8, as `CachingIterator` always wraps the given traversable in an `IteratorIterator`, which corrects this wrong behaviour in underlying iterators. In the upcoming 1.9 release, this is no longer the case for any traversable that implements the `Iterator` interface, so this wrong behaviour can lead to extra elements given (hence the test failures).
=> PHPLIB-608 Fix wrong validity check in CachingIterator

tests/UnifiedSpecTests/UnifiedSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-611
=> PHPLIB-611: Ensure valid-fail tests are executed by unified test runner

composer.json
This simple bump allows for the 2.0 version of this lib, which leverages Composer 2 APIs and drops any sub dependency.
There are basically no BC; for more details, see the [the changelog](https://github.com/Jean85/pretty-package-versions/blob/2.x/CHANGELOG.md).
=> Allow PrettyVersion 2.0

.evergreen/config/php.ini, .evergreen/install-dependencies.sh, .evergreen/run-tests.sh, phpunit.evergreen.xml, tests/Collection/CollectionFunctionalTest.php, tests/Collection/CrudSpecFunctionalTest.php, tests/Database/DatabaseFunctionalTest.php, tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php, tests/Model/IndexInfoFunctionalTest.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/ListCollectionsFunctionalTest.php, tests/Operation/MapReduceFunctionalTest.php, tests/Operation/ModifyCollectionFunctionalTest.php, tests/Operation/WatchFunctionalTest.php
PHPLIB-617
Since this version is not tested on evergreen yet, this includes the minimal scripts required to test on evergreen without adding an evergreen configuration.
=> PHPLIB-617 Continuous Matrix Testing for 4.0 era drivers

tests/Collection/CollectionFunctionalTest.php, tests/Model/IndexInfoFunctionalTest.php, tests/Operation/ListCollectionsFunctionalTest.php, tests/Operation/MapReduceFunctionalTest.php, tests/SpecTests/FunctionalTestCase.php, tests/SpecTests/RetryableReadsSpecTest.php
PHPLIB-616
This branch skips tests that fail when running the 4.2 driver against newer servers. The patch build has been updated to test 4.2 as well: https://spruce.mongodb.com/version/602f72fc9ccd4e172a60e6e8/tasks
The failing tests are tricky: these are single tests in some of the spec tests which we can't skip due to how data providers work. Skipping the entire test suite seems overkill, so I'll have to figure out another way to fix this.
=> PHPLIB-616 Continuous Matrix Testing for 4.2 era drivers

tests/Model/IndexInfoFunctionalTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php
PHPLIB-615
Patch build here: https://spruce.mongodb.com/version/6040d7ab5623437bced1668d/tasks
CSFLE tests needed a change as there were intermittent failures on replica sets. Using a majority write concern fixes this. This was done for some tests, but apparently I missed a few of them when I originally did this.
Once this PR is merged, I'll merge changes up to the current development branch and update the PR to drivers-matrix-testing to test against the actual compat versions instead of branches on my fork.
=> PHPLIB-615 Matrix testing for 4.4 era drivers

src/Operation/EstimatedDocumentCount.php, tests/FunctionalTestCase.php, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/retryable-reads/estimatedDocumentCount-4.9.json, tests/SpecTests/retryable-reads/estimatedDocumentCount-pre4.9.json, tests/SpecTests/retryable-reads/estimatedDocumentCount-serverErrors-4.9.json, tests/SpecTests/retryable-reads/estimatedDocumentCount-serverErrors-pre4.9.json, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/crud/estimatedDocumentCount.json
=> PHPLIB-618: Change estimatedDocumentCount to use $collStats

.evergreen/config.yml, .evergreen/run-tests.sh, tests/ClientFunctionalTest.php, tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php, tests/Operation/FindAndModifyFunctionalTest.php, tests/Operation/WatchFunctionalTest.php, tests/SpecTests/AtlasDataLakeSpecTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/Context.php, tests/SpecTests/CrudSpecTest.php, tests/SpecTests/PrimaryStepDownSpecTest.php, tests/SpecTests/TransactionsSpecTest.php, tests/TestCase.php, tests/UnifiedSpecTests/Context.php, tests/UnifiedSpecTests/RunOnRequirement.php, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/valid-fail/entity-client-apiVersion-unsupported.json, tests/UnifiedSpecTests/valid-pass/poc-change-streams.json, tests/UnifiedSpecTests/valid-pass/poc-gridfs.json, tests/UnifiedSpecTests/valid-pass/poc-retryable-writes.json, tests/UnifiedSpecTests/versioned-api/crud-api-version-1-strict.json, tests/UnifiedSpecTests/versioned-api/crud-api-version-1.json, tests/UnifiedSpecTests/versioned-api/runcommand-helper-no-api-version-declared.json, tests/UnifiedSpecTests/versioned-api/test-commands-deprecation-errors.json, tests/UnifiedSpecTests/versioned-api/test-commands-strict-mode.json, tests/UnifiedSpecTests/versioned-api/transaction-handling.json
PHPLIB-622
Docs are part of #815. Currently tests against a WIP version of ext-mongodb, which I'll remove once https://github.com/mongodb/mongo-php-driver/pull/1204 is merged.
=> PHPLIB-622 Versioned MongoDB API for Drivers

docs/includes/apiargs-MongoDBClient-method-construct-driverOptions.yaml, docs/tutorial.txt, docs/tutorial/versioned-api.txt
PHPLIB-621
This is the PHPLIB counterpart to the API documentation drafted in https://github.com/alcaeus/doc-en/pull/1. I wanted to get a head start on these changes, but wait with wrapping up documentation until the features are merged. Nonetheless, the tutorial and API documentation is ready to be reviewed.
Note: The first commit sorts non-deprecated driver options to the top in alphabetical order, with deprecated options documented last. The other two commits document the usage of the `serverApi` options.
=> PHPLIB-621 Document Versioned API usage

.evergreen/config.yml, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/transactions/mongos-unpin.json
https://jira.mongodb.org/browse/PHPLIB-642
Synced with mongodb/specifications@ec326862be443d11f0233cee2de32a95751144df
No code changes apart from commenting out `lowest-supported` in the Evergreen config, so I'll merge after CI is green.
=> PHPLIB-642: Sync transactions tests for unpinning after abort

tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/crud/aggregate.json, tests/UnifiedSpecTests/crud/db-aggregate.json, tests/UnifiedSpecTests/crud/unacknowledged-bulkWrite-delete-hint-clientError.json, tests/UnifiedSpecTests/crud/unacknowledged-bulkWrite-update-hint-clientError.json, tests/UnifiedSpecTests/crud/unacknowledged-deleteMany-hint-clientError.json, tests/UnifiedSpecTests/crud/unacknowledged-deleteOne-hint-clientError.json, tests/UnifiedSpecTests/crud/unacknowledged-findOneAndDelete-hint-clientError.json, tests/UnifiedSpecTests/crud/unacknowledged-findOneAndReplace-hint-clientError.json, tests/UnifiedSpecTests/crud/unacknowledged-findOneAndUpdate-hint-clientError.json, tests/UnifiedSpecTests/crud/unacknowledged-replaceOne-hint-clientError.json, tests/UnifiedSpecTests/crud/unacknowledged-updateMany-hint-clientError.json, tests/UnifiedSpecTests/crud/unacknowledged-updateOne-hint-clientError.json
https://jira.mongodb.org/browse/PHPLIB-657
The skipping of tests within `db-aggregate.json` is unfortunate, but it should be temporary until schemaVersion 1.4 is implemented. See [DRIVERS-1130](https://jira.mongodb.org/browse/DRIVERS-1130) for more details. On the bright side, we do get a new `aggregate.json` test.
Incompatible tests for unacknowledged writes using hints are explicitly skipped (see: [DRIVERS-991](https://jira.mongodb.org/browse/DRIVERS-991) and [DRIVERS-1340](https://jira.mongodb.org/browse/DRIVERS-1340) for context).
=> PHPLIB-657: Skip incompatible unified tests and resync CRUD

docs/includes/apiargs-MongoDBDatabase-method-createCollection-option.yaml, src/Operation/CreateCollection.php, tests/Operation/CreateCollectionTest.php, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/collection-management/timeseries-collection.json
=> PHPLIB-659 Support options for time-series collections

tests/SpecTests/TransactionsSpecTest.php, tests/UnifiedSpecTests/UnifiedSpecTest.php
These tests will be fixed with PHPLIB-665 which is currently being worked on. Until then, we can skip these tests.
=> Fix failing transaction spec tests

.evergreen/config.yml, .evergreen/install-dependencies.sh, composer.json, tests/ClientFunctionalTest.php, tests/Collection/CrudSpecFunctionalTest.php, tests/Collection/FunctionalTestCase.php, tests/Database/FunctionalTestCase.php, tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php, tests/GridFS/FunctionalTestCase.php, tests/GridFS/ReadableStreamFunctionalTest.php, tests/GridFS/StreamWrapperFunctionalTest.php, tests/GridFS/WritableStreamFunctionalTest.php, tests/Model/ChangeStreamIteratorTest.php, tests/Model/IndexInfoFunctionalTest.php, tests/Operation/BulkWriteFunctionalTest.php, tests/Operation/DeleteFunctionalTest.php, tests/Operation/FunctionalTestCase.php, tests/Operation/InsertManyFunctionalTest.php, tests/Operation/InsertOneFunctionalTest.php, tests/Operation/UpdateFunctionalTest.php, tests/Operation/WatchFunctionalTest.php, tests/SpecTests/AtlasDataLakeSpecTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/FunctionalTestCase.php, tests/SpecTests/PrimaryStepDownSpecTest.php, tests/SpecTests/TransactionsSpecTest.php, tests/UnifiedSpecTests/UnifiedSpecTest.php
PHPLIB-589
While we're only removing the (now deprecated) `SetUpTearDownTrait` at this time, more significant changes will happen once we drop PHP 7.1, as this allows us to start introducing argument types.
=> PHPLIB-589 Drop support for PHP 7.0

src/Operation/ListIndexes.php
https://jira.mongodb.org/browse/PHPLIB-636
=> PHPLIB-636: ListIndexes should use CommandException for catching missing namespace and database errors

src/Model/CollectionInfo.php, tests/Model/CollectionInfoTest.php
PHPLIB-675
This adds `isCollection`, `isTimeSeries`, and `isView` helpers to `CollectionInfo` to complement `isCapped`.
=> PHPLIB-675 Add helpers to check collection types to CollectionInfo

docs/reference/enumeration-classes.txt, docs/reference/method/MongoDBModelCollectionInfo-getCappedMax.txt, docs/reference/method/MongoDBModelCollectionInfo-getCappedSize.txt, docs/reference/method/MongoDBModelCollectionInfo-getIdIndex.txt, docs/reference/method/MongoDBModelCollectionInfo-getInfo.txt, docs/reference/method/MongoDBModelCollectionInfo-getName.txt, docs/reference/method/MongoDBModelCollectionInfo-getOptions.txt, docs/reference/method/MongoDBModelCollectionInfo-getType.txt, docs/reference/method/MongoDBModelCollectionInfo-isCapped.txt
PHPLIB-675
Adds missing documentation for new method and documents the deprecation of helpers relating to capped collections.
=> PHPLIB-675 Document new CollectionInfo methods

docs/includes/apiargs-MongoDBDatabase-method-createCollection-option.yaml, docs/reference/method/MongoDBDatabase-createCollection.txt
=> PHPLIB-690 Update documentation for time series collection options

.evergreen/config.yml
This updates the `driver-versions` axis to test against the latest stable release, the upcoming 1.10.x release, and the upcoming 1.11.0 release. We can enable testing `lowest-supported` once 1.10.1 is released.
=> Update tested ext-mongodb versions

docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-aggregate-option.yaml, docs/includes/apiargs-aggregate-option.yaml
https://jira.mongodb.org/browse/PHPLIB-663
=> PHPLIB-663: Document aggregate "let" option

tests/Collection/CollectionFunctionalTest.php, tests/Database/DatabaseFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-682
=> PHPLIB-682: Add test for Database::dropCollection()

tests/UnifiedSpecTests/Context.php, tests/UnifiedSpecTests/EventObserver.php, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/UnifiedTestRunner.php, tests/UnifiedSpecTests/command-monitoring/redacted-commands.json, tests/UnifiedSpecTests/valid-pass/observeSensitiveCommands.json
https://jira.mongodb.org/browse/PHPLIB-664
https://jira.mongodb.org/browse/PHPLIB-676
https://jira.mongodb.org/browse/PHPLIB-703
Note: this also depended on fixing a missing `use function` statement in https://github.com/mongodb/mongo-php-library/commit/105e728d9030afe9f963c3dc7b7c561ef74db2f0 (also fixed in v1.9 branch).
=> PHPLIB-664, PHPLIB-676, and PHPLIB-703: APM redaction and observeSensitiveCommands

CONTRIBUTING.md, composer.json
This was missed after the 1.10.0 release.
=> Document process for bumping dev-master branch-alias and bump to 1.10-dev

.evergreen/config.yml, composer.json, tests/UnifiedSpecTests/Context.php, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/sessions/snapshot-sessions-not-supported-client-error.json, tests/UnifiedSpecTests/sessions/snapshot-sessions-not-supported-server-error.json, tests/UnifiedSpecTests/sessions/snapshot-sessions-unsupported-ops.json, tests/UnifiedSpecTests/sessions/snapshot-sessions.json
https://jira.mongodb.org/browse/PHPLIB-694
Syncs tests with mongodb/specifications/pull/1046 (will be updated once merged).
Temporarily reduces the `driver-versions` axis in the Evergreen matrix to `latest-dev` to pull in changes from [PHPC-1761](https://jira.mongodb.org/browse/PHPC-1761).
=> PHPLIB-694: Spec tests for snapshot sessions

src/GridFS/StreamWrapper.php, tests/GridFS/BucketFunctionalTest.php, tests/UnifiedSpecTests/Operation.php
https://jira.mongodb.org/browse/PHPLIB-592
Previously, exceptions were converted to E_USER_WARNING with a false return value for consistency with PHP's stream API (e.g. fread). This is not actually required and allowing the original exception to be propagated is likely more helpful for users and simplifies some handling in the spec test runner.
=> PHPLIB-592: Allow GridFS StreamWrapper to throw exceptions

README.md, docs/index.txt, docs/reference/bson.txt, docs/reference/method/MongoDBClient__construct.txt, docs/upgrade.txt
https://jira.mongodb.org/browse/PHPLIB-765
Addresses https://github.com/mongodb/mongo-php-library/issues/871
Targeting the v1.7 branch as the patch applies cleanly. It would require more effort to backport further.
=> PHPLIB-765: Remove links to legacy extension docs

src/Collection.php, src/Database.php, src/Model/CollectionInfoCommandIterator.php, src/Model/IndexInfoIteratorIterator.php, tests/FunctionalTestCase.php, tests/Model/BSONIteratorTest.php, tests/Model/CachingIteratorTest.php, tests/Operation/AggregateFunctionalTest.php, tests/Operation/FindAndModifyFunctionalTest.php, tests/Operation/MapReduceFunctionalTest.php, tests/SpecTests/AtlasDataLakeSpecTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/CommandExpectations.php, tests/SpecTests/ReadWriteConcernSpecTest.php, tests/SpecTests/RetryableReadsSpecTest.php, tests/SpecTests/RetryableWritesSpecTest.php, tests/SpecTests/TransactionsSpecTest.php, tests/UnifiedSpecTests/ExpectedError.php
https://jira.mongodb.org/browse/PHPLIB-766
Supersedes https://github.com/mongodb/mongo-php-library/pull/865
=> PHPLIB-766: Fix deprecation notices for PHP 8.1

docs/includes/apiargs-MongoDBClient-method-listDatabases-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-listCollections-option.yaml, src/Command/ListCollections.php, src/Command/ListDatabases.php, src/Operation/ListCollectionNames.php, src/Operation/ListCollections.php, tests/Command/ListCollectionsTest.php, tests/Operation/ListCollectionNamesFunctionalTest.php, tests/Operation/ListCollectionsFunctionalTest.php, tests/Operation/ListDatabaseNamesFunctionalTest.php, tests/Operation/ListDatabasesFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-740
=> PHPLIB-740: Support authorizedCollections option for listCollections

tests/DocumentationExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-699
=> PHPLIB-699: Versioned API strict migration doc examples

.evergreen/config.yml, phpunit.evergreen.xml, tests/Operation/ModifyCollectionFunctionalTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-783
https://jira.mongodb.org/browse/PHPLIB-784
Upstream changes in drivers-evergreen-tools now require passing LOAD_BALANCER to run-orchestration.sh. Additionally, service ID mocking is no longer required as of server version 5.1.
=> PHPLIB-783, PHPLIB-784: Update load balancer testing config and CSFLE tests

docs/includes/apiargs-MongoDBClient-method-construct-driverOptions.yaml, docs/tutorial.txt, docs/tutorial/stable-api.txt
https://jira.mongodb.org/browse/PHPLIB-786
=> PHPLIB-786: Rename "Versioned API" to "Stable API" in docs

.github/workflows/tests.yml
These secrets are only configured for Evergreen and not GitHub actions.
=> PHPLIB-776: Remove references to CSFLE secrets

tests/UnifiedSpecTests/Constraint/Matches.php, tests/UnifiedSpecTests/Constraint/MatchesTest.php
https://jira.mongodb.org/browse/PHPLIB-831
=> PHPLIB-831: Allow $$exists within $$unsetOrMatches

tests/UnifiedSpecTests/UnifiedSpecTest.php
This was missed in https://github.com/mongodb/mongo-php-library/pull/908 and introduced some avoidable test failures in the full matrix (see: [task log](https://spruce.mongodb.com/version/mongo_php_library_20e8f917f51d99b8a70137cd1d272c1fb8f42ba9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)).
=> Skip additional change stream "comment" tests

tests/DocumentationExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-810
This test expects an exception executing count via the stable API; however, 6.0.0-rc0 added count to the stable API so an exception is no longer raised. Driver changes are not yet specified but we can skip this test in the meantime.
This should prevent CI failures on server version "latest" and allow us to remove `failing-on-waterfall` from [PHPLIB-810](https://jira.mongodb.org/browse/PHPLIB-810).
=> PHPLIB-810: Temporarily skip stable API count test for server 6.0+

docs/includes/apiargs-MongoDBClient-method-watch-option.yaml, docs/includes/apiargs-MongoDBCollection-method-watch-option.yaml, docs/includes/apiargs-MongoDBDatabase-method-watch-option.yaml, docs/includes/apiargs-method-watch-option.yaml, src/Operation/Watch.php, tests/Operation/WatchTest.php, tests/UnifiedSpecTests/Util.php, tests/UnifiedSpecTests/change-streams/change-streams-pre_and_post_images.json
https://jira.mongodb.org/browse/PHPLIB-814
Introduces fullDocumentBeforeChange option. Tests for specifying "whenAvailable" and "required" for both fullDocument and fullDocumentBeforeChange (requires MongoDB 6.0+ with changeStreamPreAndPostImages enabled on the collection).
Depends on https://github.com/mongodb/mongo-php-library/pull/908.
=> PHPLIB-814: Change stream support for point-in-time pre and post-images

docs/includes/apiargs-MongoDBDatabase-method-createCollection-option.yaml, src/Operation/CreateCollection.php, tests/Operation/CreateCollectionTest.php, tests/UnifiedSpecTests/Operation.php, tests/UnifiedSpecTests/Util.php, tests/UnifiedSpecTests/collection-management/clustered-indexes.json, tests/UnifiedSpecTests/collection-management/createCollection-pre_and_post_images.json, tests/UnifiedSpecTests/collection-management/modifyCollection-pre_and_post_images.json
https://jira.mongodb.org/browse/PHPLIB-843
https://jira.mongodb.org/browse/PHPLIB-856
Also adds missing `createCollection` option for [PHPLIB-814](https://jira.mongodb.org/browse/PHPLIB-814), which was included in the recently synced spec tests.
=> PHPLIB-843 and PHPLIB-856: clusteredIndex and changeStreamPreAndPostImages options

tests/UnifiedSpecTests/collection-management/clustered-indexes.json
https://jira.mongodb.org/browse/PHPLIB-874
POC for https://github.com/mongodb/specifications/pull/1217
Depends on https://github.com/mongodb/mongo-php-library/pull/928, so only the PHPLIB-874 commit is relevant to this PR.
=> PHPLIB-874: commandStartedEvent assertions for clusteredIndex tests

tests/UnifiedSpecTests/change-streams/change-streams.json
https://jira.mongodb.org/browse/PHPLIB-873
This is a temporary solution to address flaky test failures on sharded clusters.
Synced with mongodb/specifications@f07351c0c61cd79e0e7a197f78a5cfcc028c2966
=> PHPLIB-873: Restrict unified change stream tests to replica sets

.evergreen/config.yml, .evergreen/run-tests.sh
https://jira.mongodb.org/browse/PHPLIB-868
Also removes remnants of service ID mocking (PHPC-2053). Related to https://github.com/mongodb/mongo-php-driver/pull/1321.
=> PHPLIB-868: Add MongoDB 5.0 to load balancer CI matrix

tests/DocumentationExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-810
MongoDB 6.0 added the count command to API version 1 and that change was later backported to 5.0.9 and 5.3.2.
=> PHPLIB-810: Update version check for stable API count test

docs/tutorial/client-side-encryption.txt
https://jira.mongodb.org/browse/PHPLIB-893
=> PHPLIB-893: Automatic queryable encryption in CSFLE tutorial

.github/workflows/tests.yml, src/Model/BSONArray.php, src/Model/BSONDocument.php, src/Model/ChangeStreamIterator.php, src/Model/IndexInput.php, src/Operation/Watch.php, tests/GridFS/UnusableStream.php, tests/UnifiedSpecTests/Constraint/IsBsonTypeTest.php, tests/UnifiedSpecTests/Constraint/Matches.php, tests/UnifiedSpecTests/Operation.php
PHPLIB-933
This includes changes to remove warnings due to new method signatures in PHPC.
=> PHPLIB-933: Test on PHP 8.2

tests/SpecTests/DocumentsMatchConstraint.php, tests/SpecTests/DocumentsMatchConstraintTest.php, tests/SpecTests/Operation.php, tests/SpecTests/RetryableReadsSpecTest.php, tests/UnifiedSpecTests/Constraint/MatchesTest.php
PHPLIB-715
This unskips a mapReduce test that fails due to strict numerical comparison. To fix this, I applied the same logic used in the unified spec tests. This comes at the cost of removing placeholder functionality in DocumentsMatchConstraint; however this wasn't used in the constraint at all. The transaction spec tests make use of the `42` placeholder, but the transaction spec tests covers these in the command listener it uses to assert the commands, so it's safe to remove without breaking other tests.
=> PHPLIB-715: Use flexible numeric comparisons in DocumentMatchConstraint

tests/UnifiedSpecTests/UnifiedSpecTest.php
PHPLIB-912
Until https://github.com/mongodb/specifications/pull/1293 is resolved, this will skip the test so as to make other test failures more visible.
=> PHPLIB-912: Skip failing test until test is updated

tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/change-streams/change-streams-disambiguatedPaths.json, tests/UnifiedSpecTests/change-streams/change-streams-resume-errorLabels.json, tests/UnifiedSpecTests/change-streams/change-streams-showExpandedEvents.json
https://jira.mongodb.org/browse/PHPLIB-912
https://jira.mongodb.org/browse/PHPLIB-914
https://jira.mongodb.org/browse/PHPLIB-924
This can serve as a POC for https://github.com/mongodb/specifications/pull/1293. It also includes two other PHPLIB tickets for previously updated change stream spec tests, neither of which required driver changes.
Tested locally using server 6.1.0-alpha-2444-gfb80d4b, which I grabbed from [download-mongodb.sh](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergreen/download-mongodb.sh).
=> PHPLIB-912, PHPLIB-914, PHPLIB-924: Sync change stream spec tests

.evergreen/config.yml
https://jira.mongodb.org/browse/PHPLIB-932
Related to mongodb/mongo-php-driver@0a712a3265b856c5416eb2fedbbaefadd21db757
=> PHPLIB-932: Use debian11 and include MongoDB 6.0 for load balancer testing

tests/UnifiedSpecTests/transactions/do-not-retry-read-in-transaction.json, tests/UnifiedSpecTests/transactions/retryable-abort-handshake.json, tests/UnifiedSpecTests/transactions/retryable-commit-handshake.json
https://jira.mongodb.org/browse/PHPLIB-918
Synced with https://github.com/mongodb/specifications/commit/c5d1c778dba6439de72e6a3dbbaeab9de7539306
=> PHPLIB-918: Add test that reads are not retried in a transaction

.evergreen/config.yml, .evergreen/run-tests.sh
https://jira.mongodb.org/browse/PHPLIB-911
Use the crypt_shared library provisioned by download-mongodb.sh and add an additional task to disable the library and fall back to mongocryptd.
This also revises how we pass environment variables into run-tests.sh and the test suite, and restructures run-tests.sh a bit.
Related to https://github.com/mongodb/mongo-php-driver/pull/1353 for [PHPC-2135](https://jira.mongodb.org/browse/PHPC-2135).
Full patch build: https://spruce.mongodb.com/version/630faa3fe3c3315a7b34afd5/tasks
=> PHPLIB-911: Test with consistent version of crypt_shared

.evergreen/run-tests.sh
This corrects a typo introduced in 0fe1a0f0b9ee54ce270980b2651b94fcc58921ff
=> PHPLIB-911: Fix access of $DRIVER_MONGODB_VERSION env var

tests/SpecTests/ClientSideEncryptionSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-947
Patch build with CSFLE-related tasks: https://spruce.mongodb.com/version/6320bebb3e8e86529fdfe162/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Note that the `test-requireApiVersion` on MongoDB 6.0 would have previously failed without this skip.
=> PHPLIB-947: Skip legacy CSFLE explain test pending crypt_shared fix

tests/SpecTests/client-side-encryption/tests/maxWireVersion.json
https://jira.mongodb.org/browse/PHPLIB-949
Sync with mongodb/specifications@e761591616849d9b507287811e77f7a359fb9587
=> PHPLIB-949: FLE - maxWireVersion should run on Mongo Server 4.0.x

examples/changestream.php, examples/command_logger.php
https://jira.mongodb.org/browse/PHPLIB-920
=> PHPLIB-920: Command monitoring and change stream examples

tests/UnifiedSpecTests/change-streams/change-streams-clusterTime.json, tests/UnifiedSpecTests/change-streams/change-streams-showExpandedEvents.json
https://jira.mongodb.org/browse/PHPLIB-945
Sync with mongodb/specifications@1a3b359ad3976f62d4c96f9ba75a533799c2b213
=> PHPLIB-945: Update ChangeStreamEvent type definition to include clusterTime

docs/index.txt, docs/reference/method/MongoDBClient__construct.txt, docs/tutorial.txt, docs/tutorial/connecting.txt
PHPLIB-596
This PR adds a small tutorial with information about connecting to MongoDB. The examples are taken from the documentation for `MongoDB\Client::__construct`, but provides them in a spot that should be easier to find.
Note: I haven't been able to build docs locally, and an attempt to build docs in a GitHub CI build also failed with the same error:
```
~/Code/mongodb/docs-php-library 
[master|✔] ❯❯❯ giza make html
Traceback (most recent call last):
File "/opt/homebrew/bin/giza", line 5, in <module>
from giza.cmdline import main
File "/opt/homebrew/lib/python3.10/site-packages/giza/cmdline.py", line 19, in <module>
from giza.config.runtime import RuntimeStateConfig
File "/opt/homebrew/lib/python3.10/site-packages/giza/config/runtime.py", line 25, in <module>
from …
```
=> PHPLIB-596: Add tutorial for connecting to MongoDB

tests/Operation/FindAndModifyFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-638
=> PHPLIB-638: Ensure writeConcernError is reported for findAndModify

tests/Operation/FindAndModifyFunctionalTest.php
Re: https://github.com/mongodb/mongo-php-library/pull/983#discussion_r984969825
=> Note name of error code literal in findAndModify WC test

docs/index.txt, examples/aggregate.php, examples/bulk.php, examples/changestream.php, examples/command_logger.php, examples/persistable.php, examples/typemap.php, examples/with_transaction.php, phpcs.xml.dist, psalm-baseline.xml
PHPLIB-987
This PR adds more examples for every-day use of the PHP library. New examples:
* bulk writes (this shows the syntax for each bulk write operation)
* `with_transaction` helper
* Aggregation pipeline
* Serialisation and Deserialisation using `MongoDB\BSON\Persistable`
* Deserialisation using `typeMap` and `MongoDB\BSON\Unserializable`
The first commit in the PR fixes an issue where running the example code from outside of the examples directory causes fatal errors.
=> PHPLIB-987: Add more examples

docs/reference/method/MongoDBClient__construct.txt, src/Client.php
PHPLIB-980
I decided to only make the `$uri` parameter nullable. While we could widen the types of both options parameters (constructors are excluded from contravariance checks), I believe this is contra-productive. The signature of `MongoDB\Manager` historically allowed `null`, but it's preferable to not allow `null` and instead default to an empty array. This is something I'd like to change in version 2.0 of the extension.
This also becomes a non-issue starting with PHP 8, as users can use named parameters if they want to only pass a single option:
```php
$client = new Client(driverOptions: ['foo' => 'bar']);
```
This makes using `null` as an easy default value easier.
For convenience and documentation purposes, I've also extracted the default URI into a public constant.
=> PHPLIB-980: Make uri parameter for MongoDB\Client::__construct nullable

.evergreen/config.yml, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/client-side-encryption/tests/fle2-BypassQueryAnalysis.json, tests/SpecTests/client-side-encryption/tests/fle2-Compact.json, tests/SpecTests/client-side-encryption/tests/fle2-CreateCollection.json, tests/SpecTests/client-side-encryption/tests/fle2-DecryptExistingData.json, tests/SpecTests/client-side-encryption/tests/fle2-Delete.json, tests/SpecTests/client-side-encryption/tests/fle2-EncryptedFields-vs-EncryptedFieldsMap.json, tests/SpecTests/client-side-encryption/tests/fle2-EncryptedFields-vs-jsonSchema.json, tests/SpecTests/client-side-encryption/tests/fle2-EncryptedFieldsMap-defaults.json, tests/SpecTests/client-side-encryption/tests/fle2-FindOneAndUpdate.json, tests/SpecTests/client-side-encryption/tests/fle2-InsertFind-Indexed.json, tests/SpecTests/client-side-encryption/tests/fle2-InsertFind-Unindexed.json, tests/SpecTests/client-side-encryption/tests/fle2-MissingKey.json, tests/SpecTests/client-side-encryption/tests/fle2-NoEncryption.json, tests/SpecTests/client-side-encryption/tests/fle2-Update.json, tests/SpecTests/client-side-encryption/tests/fle2-validatorAndPartialFieldExpression.json
PHPLIB-950
Includes fixes required to get CSFLE running on Serverless in general:
* Needs mongocryptd or crypt_shared installed
* Needs secrets exported
* Needs KMS servers running
The download logic was shamelessly copied from the GO driver, as this isn't available through drivers-evergreen-tools. I've created DRIVERS-2459 to track this and will take a look when possible.
=> PHPLIB-950: Run legacy CSFLE tests on serverless

UPGRADE-1.14.md, UPGRADE-1.15.md, docs/reference/method/MongoDBClient-dropDatabase.txt, docs/reference/method/MongoDBClient-selectCollection.txt, docs/reference/method/MongoDBClient-selectDatabase.txt, docs/reference/method/MongoDBClient__get.txt, docs/reference/method/MongoDBCollection-distinct.txt, docs/reference/method/MongoDBCollection__construct.txt, docs/reference/method/MongoDBGridFSBucket-downloadToStreamByName.txt, docs/reference/method/MongoDBGridFSBucket-openDownloadStreamByName.txt, docs/reference/method/MongoDBGridFSBucket-openUploadStream.txt, docs/reference/method/MongoDBGridFSBucket-rename.txt, docs/reference/method/MongoDBGridFSBucket-uploadFromStream.txt, docs/reference/method/MongoDBGridFSBucket__construct.txt, docs/upgrade.txt
PHPLIB-601
I've added an `UPGRADE-1.14` document to inform users of changes they should be aware of when upgrading. Once changes for 2.0 become clearer (including a list of methods that will change their return types), we should add an `UPGRADE-2.0` document to inform users of those.
@jmikola I've renamed the previous upgrade guide in the docs to "Legacy driver upgrade guide", in case we want to add a more visible documentation of method signature changes once we add BC breaks in 2.0. I've skipped a list of changes for this PR, but can list method signature changes in the upgrade document as well. An example of this is the [upgrade document for doctrine/collections](https://github.com/doctrine/collections/blob/2.0.x/UPGRADE.md#doctrinecommoncollectionscollection) where interfaces were …
=> PHPLIB-601: Document upcoming typing changes

composer.json
Follow-up for PHPLIB-610. With 4.28 released, we no longer need to require a dev version of psalm.
=> Bump psalm requirement to 4.28

tests/SpecTests/DocumentsMatchConstraint.php, tests/SpecTests/DocumentsMatchConstraintTest.php, tests/UnifiedSpecTests/Constraint/IsBsonType.php, tests/UnifiedSpecTests/Constraint/IsBsonTypeTest.php
https://jira.mongodb.org/browse/PHPLIB-1001
https://jira.mongodb.org/browse/PHPLIB-1010
https://jira.mongodb.org/browse/PHPLIB-1011
Also revises instantiation of deprecated BSON types and fixes an assertion message.
=> PHPLIB-1001, PHPLIB-1010, PHPLIB-1011: Improvements to $$type operator

tests/UnifiedSpecTests/ExpectedError.php, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/UnifiedTestRunner.php, tests/UnifiedSpecTests/Util.php, tests/UnifiedSpecTests/collection-management/modifyCollection-errorResponse.json, tests/UnifiedSpecTests/crud/aggregate-merge-errorResponse.json, tests/UnifiedSpecTests/crud/bulkWrite-errorResponse.json, tests/UnifiedSpecTests/crud/deleteOne-errorResponse.json, tests/UnifiedSpecTests/crud/distinct-comment.json, tests/UnifiedSpecTests/crud/findOneAndUpdate-errorResponse.json, tests/UnifiedSpecTests/crud/insertOne-errorResponse.json, tests/UnifiedSpecTests/crud/updateOne-errorResponse.json, tests/UnifiedSpecTests/valid-pass/expectedError-errorResponse.json
https://jira.mongodb.org/browse/PHPLIB-909
This is a prototype for https://github.com/mongodb/specifications/pull/1316
=> PHPLIB-909: Spec tests for expectedError.errorResponse assertions

docs/tutorial/client-side-encryption.txt
PHPLIB-986
This PR splits the tutorial section on key alternate names in two parts: creating the key and using it. This is done to better explain the disconnect of creating an encryption key at one time (e.g. on deployment) and using it at a different time (i.e. when inserting data). While we could show ways how to serialise a `MongoDB\BSON\Binary` object and include that via the configuration, I believe the easier way is using an alternate name for this, as it's just a string as opposed to binary data.
In addition I've linked the server's [Encryption Key Management Documentation](https://www.mongodb.com/docs/manual/core/csfle/fundamentals/manage-keys/) as it contains more information about how to manage encryption keys, including examples how to dynamically choose an encryption key when …
=> PHPLIB-986: Split keyAltName example and link key management docs

docs/faq.txt, phpcs.xml.dist, tools/connect.php, tools/detect-extension.php
PHPLIB-572
This PR adds the two debugging scripts from https://github.com/jmikola/buildfest2021 to a new `tools` directory.
The `connect.php` script attempts to connect to a specified MongoDB deployment using socket functions, bypassing the extension. This can be used in case of connection errors when using the library.
The `detect-extension.php` script can be used to debug why the extension isn't being loaded (in any SAPI). I've modified the script compared to the version in the original repository:
- The script now checks for the existence of an extension file in the extension dir and outputs appropriate messages
- Replaced `PHP_EXTENSION_DIR` constant with `ini_get('extension_dir')`. I didn't know this before, but the constant always contains the default extension directory which may …
=> PHPLIB-572: Add debugging tools

.evergreen/config.yml
PHPLIB-1023
This resolves error with our go config to make Atlas Data Lake tests run again. Previous build failures are resolved through the libmongoc update in https://github.com/mongodb/mongo-php-driver/pull/1377
[Patch Build](https://spruce.mongodb.com/version/63563b3fe3c3315544f9c980/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Eatlas-data-lake-test__php-edge-versions~latest-stable_driver-versions~latest-stable%24)
=> PHPLIB-1023: Provide OS variant when building mongohoused

tests/UnifiedSpecTests/Util.php
https://jira.mongodb.org/browse/PHPLIB-951
This prevents a potential PHP warning for accessing a nonexistent array key if the operation doesn't exist, which was responsible for some Astrolabe test failures.
Since assertArgumentsBySchema() is called before the switch statement in Operation execute methods, we don't yet know that the operation exists. With this change, we should never hit default cases in those switch statements; however, they can remain in place for now.
Patch build for [drivers-atlas-testing](https://spruce.mongodb.com/task/drivers_atlas_testing_tests_php__driver~php_master_platform~ubuntu_18.04_runtime~php_74_validate_workload_executor_patch_c7e1bedc4ad19fbaf619153666a49b47a7744e82_636114d032f41762d7b215cd_22_11_01_12_45_23/logs?execution=0) using this PR branch.
=> PHPLIB-951: Assert operation before argument validation

tests/UnifiedSpecTests/UnifiedTestRunner.php
https://jira.mongodb.org/browse/PHPLIB-1037
This handles the case where a test fails prior to Context initialization (e.g. while populating initial data).
Patch build: https://spruce.mongodb.com/version/63633849e3c331270cf5886a/tasks
=> PHPLIB-1037: Ensure EntityMap is set before invoking observer callable

examples/aggregate.php, examples/bulk.php, examples/changestream.php, examples/command_logger.php, examples/persistable.php, examples/typemap.php, examples/with_transaction.php, psalm-baseline.xml, src/Operation/BulkWrite.php, tests/ExamplesTest.php
PHPLIB-981
This PR adds tests for the example scripts. To ensure good coverage, the tests attempt to match against the output of the example scripts. This requires a change in the examples to no longer output to `STDERR`, as PHPUnit considers any output to `STDERR` as condition to fail a test and doesn't allow asserting against it.
When running the tests, I noticed that the tests fail on sharded clusters, because the command replies are different. This would complicate the output matchers by quite a lot, so I'm wondering if it's actually worth matching against the actual command output, or if we're happy asserting that the rough information is the same.
I will likely also change the examples for type maps and persistable classes to no longer use `var_dump`. Having xdebug installed (which …
=> PHPLIB-981: Add tests for examples

docs/tutorial/modeling-bson-data.txt
https://jira.mongodb.org/browse/PHPLIB-1040
I opted not to demonstrate Serializable implementations, which can be found in the PHPC tests. If/when type maps are extended to support callables, this content should be easy to extend.
Note: I also built the docs locally and confirmed that the links render correctly.
=> PHPLIB-1040: Demonstrate enum handling in BSON tutorial

CONTRIBUTING.md
Counterpart to https://github.com/mongodb/mongo-php-driver/pull/1384
=> Revise release instructions

tests/Operation/ExplainFunctionalTest.php
PHPLIB-1044
The aggregation pipeline previously used to test an explain is optimised to a query on MongoDB 6.3, leading to different explain output. Adding a `$sort` stage removes the optimisation potential (for now) and fixes the test.
=> PHPLIB-1044: Ensure ExplainFunctionalTest does not optimise pipeline on MongoDB 6.3

.evergreen/config.yml, tests/SpecTests/ClientSideEncryptionSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-866
Patch build: https://spruce.mongodb.com/version/63857b60d6d80a169794c4e0/tasks
=> PHPLIB-866: CSFLE prose test for on-demand AWS credentials

tests/UnifiedSpecTests/command-monitoring/redacted-commands.json, tests/UnifiedSpecTests/valid-pass/observeSensitiveCommands.json
https://jira.mongodb.org/browse/PHPLIB-1043
Patch build with MongoDB 6.0 and latest: https://spruce.mongodb.com/version/638713bdd6d80a2f663ce1d7/tasks
=> PHPLIB-1043: Update observeSensitiveCommands tests for removed commands

.evergreen/config.yml, composer.json, tests/UnifiedSpecTests/ExpectedError.php, tests/UnifiedSpecTests/UnifiedSpecTest.php
This is a follow-up to PHPLIB-909 that removes the 4 previously skipped tests now that `WriteResult` exposes the errors as sent from the server. Since there may be multiple replies, I decided to only check the first one - another option would be to pass the test if any error response matches, but I'm not sure if that's feasible.
=> PHPLIB-909: Add more error response tests

tests/SpecTests/ClientSideEncryptionSpecTest.php
This was missed in a495bf5369f08048b5467803d9abdec35edac2bb for PHPLIB-884
Came across this while working on [PHPLIB-1049](https://jira.mongodb.org/browse/PHPLIB-1049). Completely my fault since https://github.com/mongodb/mongo-php-library/pull/945 was never reviewed.
=> Remove redundant code in CSFLE legacy spec test runner

.evergreen/config.yml, .evergreen/run-tests.sh, CONTRIBUTING.md, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/Context.php, tests/UnifiedSpecTests/UnifiedSpecTest.php
https://jira.mongodb.org/browse/PHPLIB-1049
https://jira.mongodb.org/browse/PHPLIB-866
Patch build: https://spruce.mongodb.com/version/63984a949ccd4e45e88e709b/tasks
Note: the two failures for the `test-requireApiVersion` task are unrelated and will be addressed in a separate PR.
=> PHPLIB-1049: AWS authentication with temporary credentials in CSFLE

tests/ExamplesTest.php, tests/FunctionalTestCase.php
https://jira.mongodb.org/browse/PHPLIB-1051
The example files create their client objects independently of the test suite, which injects an API version when it's required.
This fixes an issue originally introduced in b309cf8e4deb784705543addace0959ad13c0afc.
Patch build: https://spruce.mongodb.com/version/639927751e2d176a76153859/tasks
=> PHPLIB-1051: Skip example tests when API version is required

docs/faq.txt, docs/tutorial/install-php-library.txt
https://jira.mongodb.org/browse/PHPC-2143
As of ext-mongodb 1.15.0 (PHPC-2143), DLLs are attached to GitHub release notes.
=> Refer Windows users to GitHub releases instead of PECL for DLLs

.evergreen/config.yml
Patch build: https://spruce.mongodb.com/version/63a18cfb61837d26f2cf6e10/tasks
=> PHPLIB-1038: Use activate-kmstlsvenv.sh and find-python3.sh in Evergreen config

.github/workflows/coding-standards.yml, .github/workflows/static-analysis.yml, .github/workflows/tests.yml
For reference see https://github.com/ramsey/composer-install
No need to add `--no-interaction` and `--no-progress` explicitly and caching is done internally.
=> Simplify `composer install` in GithubActions

.gitattributes
This is considered a best practice AFAIK
=> Ship `.gitattributes` file to shrink the dist package

docs/reference/method/MongoDBClient-selectCollection.txt, docs/reference/method/MongoDBClient-selectDatabase.txt, docs/reference/method/MongoDBCollection-getReadConcern.txt, docs/reference/method/MongoDBCollection-updateMany.txt, docs/reference/method/MongoDBCollection-withOptions.txt, docs/reference/method/MongoDBDatabase-command.txt, docs/reference/method/MongoDBDatabase-getReadConcern.txt, docs/reference/method/MongoDBDatabase-selectCollection.txt, docs/reference/method/MongoDBDatabase-selectGridFSBucket.txt, docs/reference/method/MongoDBDatabase-withOptions.txt, docs/reference/method/MongoDBGridFSBucket-getReadConcern.txt, docs/reference/method/MongoDBModelIndexInfo-isGeoHaystack.txt, docs/tutorial/commands.txt
https://jira.mongodb.org/browse/PHPLIB-1055
https://jira.mongodb.org/browse/PHPLIB-1057
=> PHPLIB-1055: Various small documentation fixes

.evergreen/config.yml, .evergreen/run-tests.sh, tests/FunctionalTestCase.php, tests/SpecTests/TransactionsSpecTest.php, tests/UnifiedSpecTests/UnifiedTestRunner.php
https://jira.mongodb.org/browse/PHPLIB-794
Patch build: https://spruce.mongodb.com/version/63a862200ae6060afa805980/tasks
=> PHPLIB-794: Use single/multi-mongos LB URIs when available

src/BulkWriteResult.php, src/DeleteResult.php, src/InsertManyResult.php, src/InsertOneResult.php, src/UpdateResult.php
=> Fix: Typos

.github/workflows/coding-standards.yml, .github/workflows/static-analysis.yml, .github/workflows/tests.yml
Based on https://github.com/actions/cache/blob/main/RELEASES.md I cannot find any BC breaks
=> Use `actions/cache@v3`

tests/SpecTests/RetryableWritesSpecTest.php
=> PHPLIB-935: Propagate Original Error for Write Errors Labeled NoWritesPerformed

src/GridFS/ReadableStream.php, tests/Operation/WatchFunctionalTest.php
In Symfony we try to be kind to newcomers, which means we try to avoid word like "simply", "easily" etc., because it depends on the knowledge of the reader and it can therefore be offensive.
I am not sure how this project or especially MongoDB is handling such things, but from my POV it doesn't hurt. :shrug:
=> Remove the words `easily` and `simply`

docs/tutorial/tailable-cursor.txt, docs/upgrade.txt
Follows
* #1039 
In Symfony we try to be kind to newcomers, which means we try to avoid words like "simply", "easily" etc., because it depends on the knowledge of the reader and it can therefore be offensive.
=> [Documentation] Remove the words `easily` and `simply`

tests/UnifiedSpecTests/UnifiedTestRunner.php
PHPLIB-1037
The current logic makes some of the atlas tests fail as they are using a `mongodb+srv` URI. Since none of those tests currently use `useMultipleMongoses`, we remove the assertions that cause the failures to allow testing this scenario. I'm currently investigating how other drivers handle this to then correctly generate URIs with a single and with multiple mongoses based on the discovered servers.
=> PHPLIB-1037: Don't error when creating context for sharded clusters using mongodb+srv connection string

.github/workflows/coding-standards.yml, .github/workflows/docs.yml, .github/workflows/static-analysis.yml, .github/workflows/tests.yml
With this change, GitHub Actions will no longer run the `coding-standards`,`static-analysis`, and `tests` workflows when only documentation was changed. At the same time, the `docs` workflow is only run if files in the docs folder were changed.
I'll caution that this may cause issues with branch protection: since we require the `tests` workflow to be stable in order for a PR to be mergeable, this may prove to be unfeasible due to us having to override branch protection rules for such pull requests.
=> Skip unrelated builds for documentation

docs/includes/apiargs-MongoDBDatabase-method-createCollection-option.yaml, docs/includes/apiargs-dropCollection-option.yaml, docs/tutorial/client-side-encryption.txt
https://jira.mongodb.org/browse/PHPLIB-1095
This note was originally missed when introducing QE-related APIs in PHPLIB 1.13.
After merging to v1.13, I'll merge up through master and then request a docs build for each branch.
=> PHPLIB-1095: Queryable Encryption is "Public Technical Preview"

.evergreen/config.yml
https://jira.mongodb.org/browse/PHPLIB-1099
=> PHPLIB-1099: Add MongoDB rapid releases to Evergreen matrix

src/Collection.php, src/Database.php, src/Operation/DropEncryptedCollection.php, tests/Operation/DropEncryptedCollectionTest.php
This is based on the extraction of CreateEncryptedCollection for PHPLIB-913 in #1050.
=> Extract DropEncryptedCollection operation from helper methods

.evergreen/config.yml, tests/UnifiedSpecTests/collection-management/timeseries-collection.json
This syncs collection management tests to https://github.com/mongodb/specifications/commit/0fa17f36d4bd4def1dd5acd30264f0e2cc026d6d. It also adds tests for MongoDB 7.0 to Evergreen.
=> PHPLIB-1087: Sync collection management tests

tests/SpecTests/ClientSideEncryptionSpecTest.php
PHPLIB-1031
This is mostly copy-pasta from previous tests, changing the skip condition at the top to only skip the test when crypt_shared isn't available.
=> PHPLIB-1031: Test mongocryptd is not spawned when shared library is loaded

tests/UnifiedSpecTests/Operation.php, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/Util.php, tests/UnifiedSpecTests/run-command/runCommand.json
https://jira.mongodb.org/browse/PHPLIB-1116
Opening this PR preemptively as I noticed some test runner changes were necessary to POC https://github.com/mongodb/specifications/pull/1389. This PR will be updated once the spec is merged and we have a final sync commit.
=> PHPLIB-1116: Add tests for runCommand spec

tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/change-streams/change-streams-clusterTime.json, tests/UnifiedSpecTests/change-streams/change-streams-disambiguatedPaths.json, tests/UnifiedSpecTests/change-streams/change-streams-errors.json, tests/UnifiedSpecTests/change-streams/change-streams-pre_and_post_images.json, tests/UnifiedSpecTests/change-streams/change-streams-resume-allowlist.json, tests/UnifiedSpecTests/change-streams/change-streams-resume-errorLabels.json, tests/UnifiedSpecTests/change-streams/change-streams-showExpandedEvents.json, tests/UnifiedSpecTests/retryable-writes/bulkWrite-serverErrors.json, tests/UnifiedSpecTests/retryable-writes/handshakeError.json, tests/UnifiedSpecTests/retryable-writes/insertOne-noWritesPerformedError.json, tests/UnifiedSpecTests/retryable-writes/insertOne-serverErrors.json, tests/UnifiedSpecTests/sessions/driver-sessions-dirty-session-errors.json, tests/UnifiedSpecTests/sessions/implicit-sessions-default-causal-consistency.json, tests/UnifiedSpecTests/sessions/snapshot-sessions-unsupported-ops.json, tests/UnifiedSpecTests/sessions/snapshot-sessions.json, tests/UnifiedSpecTests/transactions/mongos-unpin.json, tests/UnifiedSpecTests/valid-pass/collectionData-createOptions.json, tests/UnifiedSpecTests/valid-pass/poc-crud.json, tests/UnifiedSpecTests/valid-pass/poc-retryable-writes.json, tests/UnifiedSpecTests/valid-pass/poc-sessions.json, tests/UnifiedSpecTests/valid-pass/poc-transactions-convenient-api.json, tests/UnifiedSpecTests/valid-pass/poc-transactions-mongos-pin-auto.json, tests/UnifiedSpecTests/valid-pass/poc-transactions.json, tests/UnifiedSpecTests/versioned-api/transaction-handling.json
https://jira.mongodb.org/browse/PHPLIB-1132
POC for https://github.com/mongodb/specifications/pull/1408 ([DRIVERS-2609](https://jira.mongodb.org/browse/DRIVERS-2609)).
This also adds unified tests for retryable writes that were originally missed in [PHPLIB-755](https://jira.mongodb.org/browse/PHPLIB-755).
Patch build: https://spruce.mongodb.com/version/64422c46850e615956fc1a71/tasks
=> PHPLIB-1132: Sync unified spec tests for revised runOnRequirements

.evergreen/config.yml
=> PHPLIB-1034: Use PHP 8.2 as latest-stable in edge versions

tests/Collection/FunctionalTestCase.php, tests/DocumentationExamplesTest.php, tests/Model/IndexInfoFunctionalTest.php, tests/Operation/FunctionalTestCase.php, tests/Operation/RenameCollectionFunctionalTest.php
Fix [PHPLIB-693](https://jira.mongodb.org/browse/PHPLIB-693)
Ensure `parent::tearDown` is always called. The call to `disableFailPoints` in `FunctionalTestCase::tearDown` was not necessary since fail points are not used in the modified test classes.
=> PHPLIB-693: Remove early returns for failed tests from tearDown methods

.github/workflows/coding-standards.yml, .github/workflows/static-analysis.yml, .github/workflows/tests.yml
This fixes warnings about node 12 actions being deprecated.
=> Update actions/checkout to v3

docs/reference/method/MongoDBCollection-count.txt, docs/reference/method/MongoDBCollection-countDocuments.txt, docs/reference/method/MongoDBCollection-createIndex.txt, docs/reference/method/MongoDBCollection-deleteMany.txt, docs/reference/method/MongoDBCollection-deleteOne.txt, docs/reference/method/MongoDBCollection-distinct.txt, docs/reference/method/MongoDBCollection-dropIndex.txt, docs/reference/method/MongoDBCollection-find.txt, docs/reference/method/MongoDBCollection-findOne.txt, docs/reference/method/MongoDBCollection-findOneAndDelete.txt, docs/reference/method/MongoDBCollection-findOneAndReplace.txt, docs/reference/method/MongoDBCollection-findOneAndUpdate.txt, docs/reference/method/MongoDBCollection-insertOne.txt, docs/reference/method/MongoDBCollection-mapReduce.txt, docs/reference/method/MongoDBCollection-replaceOne.txt, docs/reference/method/MongoDBCollection-updateMany.txt, docs/reference/method/MongoDBCollection-updateOne.txt, docs/reference/method/MongoDBDatabase-command.txt, docs/reference/method/MongoDBDatabase-createCollection.txt, docs/reference/method/MongoDBDatabase-dropCollection.txt, docs/reference/method/MongoDBDatabase-modifyCollection.txt, docs/reference/method/MongoDBDatabase-selectCollection.txt, docs/reference/method/MongoDBDatabase__get.txt, docs/reference/method/MongoDBGridFSBucket-downloadToStreamByName.txt, docs/reference/method/MongoDBGridFSBucket-find.txt, docs/reference/method/MongoDBGridFSBucket-findOne.txt, docs/reference/method/MongoDBGridFSBucket-getFileDocumentForStream.txt, docs/reference/method/MongoDBGridFSBucket-getFileIdForStream.txt, docs/reference/method/MongoDBGridFSBucket-uploadFromStream.txt
Fix [PHPLIB-1056](https://jira.mongodb.org/browse/PHPLIB-1056)
I checked all the methods to make sure that all the arguments have a defined. I used the syntax of the latest PHP versions but that's not a problem for the doc.
=> PHPLIB-1056: Add missing types in reference doc

examples/persistable.php, examples/typemap.php, tests/ExamplesTest.php
`var_dump` output is modified by [xdebug](https://xdebug.org/docs/develop), what causes tests to fail during debug.
I think it's easier to read this way.
There other calls to `var_dump` in `DocumentationExamplesTest`, but they are hidden and not tested.
=> PHPLIB-1135: Remove var_dump from tests, use print_r instead

src/GridFS/Bucket.php, src/GridFS/StreamWrapper.php, src/GridFS/WritableStream.php, src/Operation/Explain.php
Remove private properties and method never accessed. Found thanks to `./vendor/bin/psalm --find-dead-code`.
This code should be safe to remove, unless it's used for introspection, using reflection or by the C driver.
=> Remove unreachable code

composer.json, psalm-baseline.xml, src/Operation/Find.php, src/Operation/FindAndModify.php, src/functions.php, tests/FunctionsTest.php, tests/Operation/CountDocumentsFunctionalTest.php, tests/Operation/CountFunctionalTest.php, tests/Operation/CreateIndexesFunctionalTest.php, tests/Operation/CreateIndexesTest.php, tests/Operation/DatabaseCommandFunctionalTest.php, tests/Operation/DeleteFunctionalTest.php, tests/Operation/DistinctFunctionalTest.php, tests/Operation/FindAndModifyFunctionalTest.php, tests/Operation/FindFunctionalTest.php, tests/Operation/FindOneAndReplaceTest.php, tests/Operation/FindOneAndUpdateTest.php, tests/Operation/InsertManyFunctionalTest.php, tests/Operation/InsertOneFunctionalTest.php, tests/Operation/ReplaceOneTest.php, tests/Operation/UpdateFunctionalTest.php, tests/Operation/UpdateManyTest.php, tests/Operation/UpdateOneTest.php, tests/Operation/UpdateTest.php, tests/TestCase.php
https://jira.mongodb.org/browse/PHPLIB-1122
Excluding tests, most changes were concentrated in functions.php. A document_to_array() function was introduced to make it easier to access document values as arrays. This is mainly used by other utility functions (e.g. checking for dollar prefixed keys) but also ended up being used in the Find operation for handling the "modifiers" option.
Adds tests for using Document and PackedArray objects in operations.
Beyond handling of document/array types, this also filled gaps in test coverage for:
* Validation for IndexInput key/name options
* Passing a MongoDB\Driver\Command directly to DatabaseCommand
* is_last_pipeline_operator_write()
----
Most changes were made to internal functions, which are used by many operations/classes. The following is a …
=> PHPLIB-1122: Support Document and PackedArray objects in public APIs

psalm-baseline.xml, src/Operation/Aggregate.php, src/Operation/Count.php, src/Operation/Delete.php, src/Operation/Distinct.php, src/Operation/Find.php, src/Operation/Update.php
Fix [PHPLIB-802](https://jira.mongodb.org/browse/PHPLIB-802)
`ReadConcern` is relevant for query plan evaluation, not `WriteConcern` ([comment](https://jira.mongodb.org/browse/SERVER-28678?focusedCommentId=3457279&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3457279))
This should be covered by unit tests PHPLIB-1144.
=> PHPLIB-802: Send readConcern but not writeConcern to explain commands

tests/DocumentationExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-1115
Using find instead of aggregate should ensure documents are available in the calling test case on 7.0+ servers.
=> PHPLIB-1115: Fix waitForSnapshot() for MongoDB 7.0+

src/Operation/CreateEncryptedCollection.php, src/Operation/DropEncryptedCollection.php
The line in DropEncryptedCollection was never necessary. The line in CreateEncryptedCollection may have been used at one point since Binary is only referenced in a psalm-var annotation, but phpcs no longer complains.
=> Remove phpcs:ignore comments for unused use statements

psalm-baseline.xml, src/Model/IndexInput.php, src/functions.php, tests/FunctionsTest.php, tests/Model/IndexInputTest.php
Fix PHPLIB-1128
`generate_index_name()` was originally made a utility function in [bc65629](https://github.com/mongodb/mongo-php-library/commit/bc65629c772a53c57b4f5debad6aae5b76c9a01c) because it was shared by both the CreateIndexes (via IndexInput) and Count operations. It was later removed from Count in [PHPLIB-285](https://jira.mongodb.org/browse/PHPLIB-285).
=> PHPLIB-1128: Move generate_index_name() to private method within IndexInput

psalm-baseline.xml, src/Operation/CreateEncryptedCollection.php, src/Operation/DropEncryptedCollection.php, src/Operation/MapReduce.php, tests/Operation/BulkWriteFunctionalTest.php, tests/Operation/BulkWriteTest.php, tests/Operation/CreateEncryptedCollectionFunctionalTest.php, tests/Operation/InsertOneFunctionalTest.php, tests/Operation/MapReduceTest.php
https://jira.mongodb.org/browse/PHPLIB-1122
Adds support for BSON objects with:
* MapReduce `$out` parameter
* CreateEncryptedCollection and DropEncryptedCollection `encryptedFields` option
Adds test coverage for BulkWrite operations.
=> PHPLIB-1122: Additional support for BSON objects

psalm-baseline.xml, src/Operation/BulkWrite.php, src/Operation/FindAndModify.php, src/Operation/FindOneAndReplace.php, src/Operation/FindOneAndUpdate.php, src/Operation/ReplaceOne.php, src/Operation/Update.php, src/Operation/UpdateMany.php, src/Operation/UpdateOne.php, src/functions.php, tests/Operation/BulkWriteFunctionalTest.php, tests/Operation/BulkWriteTest.php, tests/Operation/CountDocumentsFunctionalTest.php, tests/Operation/CountFunctionalTest.php, tests/Operation/DeleteFunctionalTest.php, tests/Operation/DistinctFunctionalTest.php, tests/Operation/FindAndModifyFunctionalTest.php, tests/Operation/FindFunctionalTest.php, tests/Operation/FindOneAndReplaceTest.php, tests/Operation/FindOneAndUpdateTest.php, tests/Operation/FunctionalTestCase.php, tests/Operation/ReplaceOneTest.php, tests/Operation/TestCase.php, tests/Operation/UpdateFunctionalTest.php, tests/Operation/UpdateManyTest.php, tests/Operation/UpdateOneTest.php, tests/Operation/UpdateTest.php
https://jira.mongodb.org/browse/PHPLIB-1129
Consolidates data providers in base TestCase and FunctionalTestCase classes.
Change is_pipeline() to conditionally consider empty arrays as pipelines. This was needed for improvements to replace/update parameter validation, and will prove useful for consolidated pipeline validation in [PHPLIB-881](https://jira.mongodb.org/browse/PHPLIB-881).
Prohibit update documents and pipelines (both empty and non-empty) for replacement operations.
Prohibit replacement documents and empty pipeines for update operations. Empty pipelines must be prohibited because libmongoc does not support them for update commands (they're indistinguishable from empty replacement documents). For consistency, we also prohibit them for FindOneAndUpdate even though PHPLIB could …
=> PHPLIB-1129: Improve pipeline checks for replace operations

psalm-baseline.xml, src/ChangeStream.php, src/Client.php, src/Collection.php, src/Database.php, src/GridFS/Bucket.php, src/GridFS/WritableStream.php, src/Model/BSONIterator.php, src/Operation/CreateEncryptedCollection.php, src/Operation/CreateIndexes.php, src/Operation/Delete.php, src/Operation/DropCollection.php, src/Operation/Explain.php, src/Operation/FindAndModify.php, src/Operation/ListIndexes.php, src/Operation/Update.php, src/Operation/Watch.php
Fix PHPLIB-1152
`Client::$version` is the only one left because it is initialised from composer install.
=> PHPLIB-1152: replace `private static` with `private const`

src/functions.php
Fix PHPLIB-1161
The polyfill is already installed.
=> PHPLIB-1161: Leverage array_key_first in functions

tests/SpecTests/FunctionalTestCase.php, tests/SpecTests/client-side-encryption/tests/fle2v2-CreateCollection-OldServer.json, tests/SpecTests/client-side-encryption/tests/fle2v2-CreateCollection.json
https://jira.mongodb.org/browse/PHPLIB-1157
https://jira.mongodb.org/browse/PHPLIB-1071
This reverts previous functionality added in d95e7623390b8f657755f6601859d4649612a40d.
CSFLE tests are synced to mongodb/specifications@e59a0ac6daa19e7605b0a1d2c667a67367d52edd
Also updates fle2v2-CreateCollection-OldServer.json from mongodb/specifications@9e770b54bbb6315aa82a162c42c577a5b3f8037a, which was a late change for PHPLIB-1071
=> PHPLIB-1157: Limit omitted field assertions to top-level

src/Operation/Aggregate.php, src/Operation/Count.php, src/Operation/Delete.php, src/Operation/DeleteMany.php, src/Operation/DeleteOne.php, src/Operation/Distinct.php, src/Operation/EstimatedDocumentCount.php, src/Operation/Explain.php, src/Operation/Explainable.php, src/Operation/Find.php, src/Operation/FindAndModify.php, src/Operation/FindOne.php, src/Operation/FindOneAndDelete.php, src/Operation/FindOneAndReplace.php, src/Operation/FindOneAndUpdate.php, src/Operation/Update.php, src/Operation/UpdateMany.php, src/Operation/UpdateOne.php
=> PHPLIB-1162: Remove unused argument Explainable::getCommandDocument(Server $server)

tests/DocumentationExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-1120
=> PHPLIB-1120: Remove redundant options from with_transaction() docs examples

docs/reference/method/MongoDBModelIndexInfo-isGeoHaystack.txt, src/Model/IndexInfo.php, tests/Model/IndexInfoFunctionalTest.php, tests/Model/IndexInfoTest.php
Fix [PHPLIB-1057](https://jira.mongodb.org/browse/PHPLIB-1057)
MongoDB 5.0 removes support for "geoHaystack" indexes, the method "IndexInfo::isGeoHaystack()" will be removed in a future release.
=> PHPLIB-1057: Deprecate method IndexInfo::isGeoHaystack()

psalm-baseline.xml, src/Client.php, src/Collection.php, src/Database.php, src/Operation/Aggregate.php, src/Operation/CreateCollection.php, src/Operation/Watch.php, src/functions.php, tests/FunctionsTest.php, tests/Operation/AggregateTest.php, tests/Operation/CreateCollectionTest.php, tests/Operation/WatchTest.php
Fix PHPLIB-881
Leverage `is_pipeline` to validate `$pipeline` argument and `"pipeline"` option. Since this function returns a boolean, it does not provide context about the error. This change allows to factorise the code and to go further in the validation, but the message in the exception is less precise.
=> PHPLIB-881: Consolidate validation of aggregation pipeline options

src/GridFS/Bucket.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/FunctionalTestCase.php
Fix PHPLIB-1142
Bugfix, the option value set to the constructor was ignored. The only way to disable md5 was to  set the option when calling `Bucket::uploadFromStream`.
Added a functional test to ensure this option works. But it does not cover this specific bug.
=> PHPLIB-1142: Use `disableMD5` when provided to GridFS Bucket constructor

docs/includes/apiargs-MongoDBDatabase-method-createCollection-option.yaml, docs/includes/apiargs-dropCollection-option.yaml, docs/reference/method/MongoDBDatabase-createEncryptedCollection.txt, docs/tutorial/client-side-encryption.txt
https://jira.mongodb.org/browse/PHPLIB-1130
Complements https://github.com/php/doc-en/commit/00a6867b300b3415e9f3ff57e119c2f397b1f782
=> PHPLIB-1130: Remove preview notice for CSFLE Queryable Encryption

.github/workflows/coding-standards.yml, .github/workflows/static-analysis.yml, psalm-baseline.xml
Fix PHPLIB-1158
Psalm detects the lowest supported PHP version by reading the `composer.json` ([doc](https://psalm.dev/docs/running_psalm/configuration/#phpversion))
=> PHPLIB-1158: Upgrade psalm+rector+phpcs jobs to PHP 8.2

phpunit.evergreen.xml, phpunit.xml.dist, tests/Comparator/Int64Comparator.php, tests/Comparator/Int64ComparatorTest.php, tests/SpecTests/ClientSideEncryption/FunctionalTestCase.php, tests/SpecTests/ClientSideEncryption/Prose22_RangeExplicitEncryptionTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/DocumentsMatchConstraint.php, tests/SpecTests/DocumentsMatchConstraintTest.php, tests/UnifiedSpecTests/Constraint/IsBsonTypeTest.php, tests/UnifiedSpecTests/Constraint/Matches.php, tests/bootstrap.php
PHPLIB-1147
PHPLIB-1148
This PR removes the previous workarounds for creating Int64 instances through `unserialise` and adds a comparator for Int64 values. Using this comparator renders other workarounds for comparing Int64 instances obsolete.
I've built the comparator to only become active if at least one value is an Int64 instance and the other value is an int or numeric string. On 64-bit platforms we're comparing int values directly, whereas we compare string representations on 32-bit platforms to ensure correct behaviour for 64-bit values.
A note to contributors: if you have your own `phpunit.xml` file, make sure to update the `bootstrap` configuration as seen in `phpunit.xml.dist`. This is necessary to ensure that the new comparator is loaded.
=> PHPLIB-1147, PHPLIB-1148: Int64 improvements

.github/workflows/coding-standards.yml, .github/workflows/static-analysis.yml
Using a matrix strategy results in changing names whenever we change the driver or PHP version, requiring an update to protected branch settings. Moving this configuration to env variables prevents this issue.
=> Refactor psalm and phpcs workflows to get static names

tests/SpecTests/client-side-encryption/tests/explain.json
https://jira.mongodb.org/browse/PHPLIB-947
POC for https://github.com/mongodb/specifications/pull/1435
As noted in [DRIVERS-2612](https://jira.mongodb.org/browse/DRIVERS-2612?focusedCommentId=5502676&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5502676), this is blocked on the release of 7.0.0-rc4 for [BACKPORT-16190](https://jira.mongodb.org/browse/BACKPORT-16190).
=> PHPLIB-947: Require 7.0+ for explain apiVersion bug fix

src/Operation/Aggregate.php, tests/Collection/CollectionFunctionalTest.php
Fix PHPLIB-722
This does not change anything functionally, but cleanup `$options` in the constructor instead of picking the `writeOption` conditionally in `executeCommand()`. There is no impact on `getCommandDocument()` which already ignores `writeConcern`.
=> PHPLIB-722: Ignore writeConcern option for read-only aggregations

CONTRIBUTING.md, RELEASING.md, composer.json
Ease dev process by adding shortcuts to the common commands.
Also adding me to the authors of the library, not because I've deleted almost as many lines as I've added, but because it's become my full-time activity.
=> Add composer scripts

docs/tutorial/client-side-encryption.txt, psalm-baseline.xml, src/GridFS/WritableStream.php, tests/DocumentationExamplesTest.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/ReadableStreamFunctionalTest.php, tests/GridFS/StreamWrapperFunctionalTest.php, tests/Operation/CreateEncryptedCollectionFunctionalTest.php, tests/SpecTests/ClientSideEncryption/Prose21_AutomaticDataEncryptionKeysTest.php, tests/SpecTests/ClientSideEncryption/Prose22_RangeExplicitEncryptionTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/DocumentsMatchConstraintTest.php, tests/UnifiedSpecTests/Constraint/IsBsonTypeTest.php
https://jira.mongodb.org/browse/PHPLIB-1174
=> PHPLIB-1174: Rely on Binary constructor default type

src/Model/CallbackIterator.php, tests/Model/CallbackIteratorTest.php
PHPLIB-1184
#1059 contained some improvements to the `CallbackIterator`. These have been extracted here:
* Pass element key to the callback
* Define template for types in CallbackIterator
* Declare the expected type for the callback
* Accept any callable as callback instead of only accepting a `Closure` instance
=> PHPLIB-1184: Improve CallbackIterator

.evergreen/config.yml
PHPLIB-1098
This PR updates the build pipeline to test on supported platforms:
* Add Ubuntu 22.04 and 20.04
* Add RHEL 9.0, 8.2, 8.1, and 7.6
The main tests are currently disabled for RHEL 7.6 and Ubuntu 20.04. Ubuntu 20.04 has issues with the "Start KMS servers" task due to dependency conflicts that I'll have to investigate separately. RHEL 7.6 has issues installing the extension via PECL as it fails with an SSL error when attempting to connect to pecl.php.net. I suspect a certificate problem but need to investigate further.
=> PHPLIB-1098: Test on supported platforms

.gitattributes, psalm-baseline.xml, psalm.xml.dist, src/Codec/Codec.php, src/Codec/CodecLibrary.php, src/Codec/DecodeIfSupported.php, src/Codec/Decoder.php, src/Codec/DocumentCodec.php, src/Codec/EncodeIfSupported.php, src/Codec/Encoder.php, src/Codec/KnowsCodecLibrary.php, src/Codec/architecture.md, src/Exception/UnsupportedValueException.php, stubs/BSON/Document.stub.php, stubs/BSON/Iterator.stub.php, stubs/BSON/PackedArray.stub.php, tests/Codec/CodecLibraryTest.php, tests/PedantryTest.php
PHPLIB-1180
This follows the prototyping work done in #1059.
This PR only introduces the codec interfaces and two standard codecs to traverse arrays and objects. Support for lazy BSON deserialisation will be added in a separate PR.
Compared to the prototype PR, the following changes have been made to the codecs:
* Introduced `encodeIfSupported` and `decodeIfSupported` methods (suggested during review)
* Special treatment for `null` in CodecLibrary has been removed
Other comments in the prototype PR concerned other areas (such as lazy BSON structures), those will be worked into future pull requests.
=> PHPLIB-1180: Add basic infrastructure for codecs

.evergreen/config.yml, .evergreen/run-tests.sh, tests/TestCase.php, tests/bootstrap.php
PHPLIB-1008
This changes CSFLE testing to not only test without crypt_shared, but to also test crypt_shared on all server versions, including those that do not ship with the shared library. For those versions, drivers-evergreen-tools downloads crypt_shared for MongoDB 6.0. This requires us to test on a platform that supports MongoDB 4.2 up to 6.0, hence the usage of RHEL 8.0 for that pipeline.
As an aside, I'm not sure if the previous tests properly tested without crypt_shared. After adding the initial commit to output some basic information about the test environment, I noticed that crypt_shared was still available. The `SKIP_CRYPT_SHARED` variable was incorrectly set in the call to "run tests", but needs to be set when starting mongo-orchestration as that function downloads crypt_shared …
=> PHPLIB-1008: Test crypt_shared with older server versions

docs/includes/apiargs-MongoDBCollection-method-aggregate-option.yaml, docs/reference/method/MongoDBCollection-aggregate.txt, src/Collection.php, src/Operation/Aggregate.php, src/Operation/CountDocuments.php, src/Operation/Watch.php, tests/Operation/AggregateTest.php, tests/UnifiedSpecTests/Util.php
PHPLIB-1192
I came across this while working on codecs, and removing this legacy logic makes the logic significantly simpler.
=> PHPLIB-1192: Remove useCursor option in aggregate

tests/UnifiedSpecTests/run-command/runCommand.json
https://jira.mongodb.org/browse/PHPLIB-1205
POC for https://github.com/mongodb/specifications/pull/1443
Includes some changes from pending runCursorCommand spec work (PHPLIB-1077).
Patch build with various topologies: https://spruce.mongodb.com/version/64b575990305b9d6044c42ce/tasks
=> PHPLIB-1205: Sync runCommand spec tests for removal of "sharded-replicaset"

tests/ExamplesTest.php
Fixes two build failures on 7.0 and latest that started appearing recently.
=> Skip queryable encryption tests on standalone servers

tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php, tests/Operation/CreateEncryptedCollectionFunctionalTest.php, tests/Operation/FindAndModifyFunctionalTest.php, tests/SpecTests/ClientSideEncryption/Prose21_AutomaticDataEncryptionKeysTest.php, tests/SpecTests/ClientSideEncryption/Prose22_RangeExplicitEncryptionTest.php, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/SpecTests/RetryableWritesSpecTest.php, tests/UnifiedSpecTests/UnifiedTestRunner.php
https://jira.mongodb.org/browse/PHPLIB-1202
=> PHPLIB-1202: Assume sharded clusters use replica sets

phpcs.xml.dist, src/GridFS/Bucket.php, tests/DocumentationExamplesTest.php, tests/FunctionalTestCase.php, tests/GridFS/BucketFunctionalTest.php, tests/PedantryTest.php, tools/detect-extension.php
This adds a rule requiring arrow functions to our coding standard. In addition to that, I enabled a rule requiring single quotes where possible. Commits are split by rule for a better review experience.
The last commit entails no actual changes, this was left over from before we were specifying a PHP version in the config.
=> Improve coding standard

tests/UnifiedSpecTests/UnifiedTestRunner.php, tests/UnifiedSpecTests/UnifiedTestRunnerTest.php, tests/UnifiedSpecTests/runner/entity-map-observer.json
`UnifiedTestRunner::setEntityMapObserver()` is used in `[drivers-atlas-testing](https://github.com/mongodb-labs/drivers-atlas-testing/).
=> Add test on `UnifiedTestRunner::setEntityMapObserver()`

examples/aggregate.php, examples/bulk.php, examples/changestream.php, examples/command_logger.php, examples/persistable.php, examples/typemap.php, examples/with_transaction.php, tests/ExamplesTest.php
PHPLIB-1208
The appstract/laravel-opcache package looks compiles all php files using `opcache_compile_file`. This creates some duplicate function declarations in our example files. Since we want to ship the examples for users' benefit, these files need to be excluded by another measure. ~Luckily, the package [excludes files containing a shebang](https://github.com/appstract/laravel-opcache/blob/d2ce88cddda6af54c14d1f9ceaaf94b54f38f9d3/src/OpcacheClass.php#L61), so adding that and making the examples executable not only fixes the opcache issues, but also makes them a little easier to run.~
The above solution does not work on all PHP versions, as our tests require the files and the addition of the shebang makes the `declare` and `namespace` declarations no longer the first statements in the …
=> PHPLIB-1208: Split example namespaces

examples/sdam_logger.php, tests/ExamplesTest.php
https://jira.mongodb.org/browse/PHPLIB-1177
=> PHPLIB-1177: SDAM logger example

.evergreen/config.yml, .evergreen/run-tests.sh
PHPLIB-1168
This PR adds a new evergreen build configuration to run all tests in the `atlas` group on an Atlas cluster. At the moment, this is limited to search index spec tests, but may encompass more tests later.
To ensure the atlas cluster is shut down, this leverages a task group. No other tasks or build variants have changed, as that's handled in the separate CI cleanup.
I've included a run for the build variant in the patch build for this PR, but these tests will usually not be run as part of a pull request to save build resources.
=> PHPLIB-1168: Run atlas tests on an Atlas cluster

.evergreen/run-tests.sh, phpunit.evergreen.xml, phpunit.xml.dist, tests/SpecTests/AtlasDataLakeSpecTest.php
Why using a named test suite while we use groups for other environment-specific tests?
This test suite was introduced by #771 before groups started to be used in the project.
=> Use phpunit group instead of Atlas Data Lake test suite

.evergreen/run-tests.sh
As mentioned by @jmikola in https://github.com/mongodb/mongo-php-library/pull/1150#discussion_r1317639037, the wildcard character breaks running the data-lake test suite.
=> Remove wildcards from cases in run-tests

tests/Operation/AggregateFunctionalTest.php, tests/Operation/ExplainFunctionalTest.php
PHPLIB-1230
Instead of assuming that the `shards` key is present, I decided on the cautious route and check for it, handling the different output more gracefully.
=> PHPLIB-1230: Fix explain tests on MongoDB latest

examples/persistable.php, psalm-baseline.xml, src/Model/IndexInput.php, src/Model/SearchIndexInput.php
https://github.com/mongodb/mongo-php-driver/pull/1449 changed the tentative return type of `MongoDB\BSON\Serializable` to no longer allow any `object` (which was incorrect as we never supported returning any object other than `stdClass` instances), instead restricting it to `stdClass` instances. This PR deals with the resulting deprecation notices emitted on PHP 8.1 and newer.
=> Fix signatures of bsonSerialize() methods

src/GridFS/Bucket.php, src/GridFS/WritableStream.php, tests/Fixtures/Codec/TestFileCodec.php, tests/Fixtures/Document/TestFile.php, tests/GridFS/BucketFunctionalTest.php
PHPLIB-1220
Note that the `Bucket` class does not forward the codec option to the underlying collections, as they can't both work with the same codec (it's only applicable to file documents). Setting a codec on the file collection also wouldn't work, as the collection would expect to apply the codec when inserting a file document. To work around these issues, the codec is manually applied in the `findOne`, `find`, and `getFileDocumentForStream` methods.
=> PHPLIB-1220: Support codec option for GridFS buckets

tests/UnifiedSpecTests/collection-management/timeseries-collection.json
PHPLIB-1232
This syncs the file with commit https://github.com/mongodb/specifications/commit/b7792587a6600d07a0e26d65283c67c7418d0b28
=> PHPLIB-1232: Run timeseries createCollection tests on MongoDB 6.3

examples/atlas-search.php, psalm-baseline.xml, tests/ExamplesTest.php
Follow-up #1097
The example requires an Atlas M10+ cluster with Sample data loaded. It creates an index and performs a search query.
[![asciicast](https://asciinema.org/a/HI0JnAOjE813nqV54xMhIJbO2.svg)](https://asciinema.org/a/HI0JnAOjE813nqV54xMhIJbO2)
=> Add Atlas Search example

benchmark/DriverBench/GridFSBench.php, benchmark/DriverBench/MultiDocBench.php, benchmark/Extension/EnvironmentProvider.php, benchmark/Fixtures/Data.php, benchmark/Utils.php, phpbench.json.dist
Fix [PHPLIB-1236](https://jira.mongodb.org/browse/PHPLIB-1236)
https://github.com/mongodb/specifications/blob/master/source/benchmarking/benchmarking.rst#multi-doc-benchmarks
```
\MongoDB\Benchmark\DriverBench\MultiDocBench
benchFindMany # Driver default typemap..I2 - Mo133.957ms (±0.20%)
benchFindMany # Raw BSON................I2 - Mo17.109ms (±0.86%)
benchBulkInsert # Small doc.............I2 - Mo53.328ms (±0.25%)
benchBulkInsert # Small BSON doc........I2 - Mo53.180ms (±0.36%)
benchBulkInsert # Large doc.............I2 - Mo242.104ms (±2.10%)
benchBulkInsert # Large BSON doc........I2 - Mo239.291ms (±0.63%)
\MongoDB\Benchmark\DriverBench\GridFSBench
benchUpload.............................I2 - Mo31.448ms (±0.47%)
benchDownload...........................I2 - Mo67.099ms (±11.71%) …
```
=> PHPLIB-1236 Implement Multi-Doc Benchmarks

benchmark/composer.json, composer.json
I think it has been forgotten in https://github.com/mongodb/mongo-php-library/pull/1128
- PHP 7.4 don't need PHP.3 polyfill
- the function `get_debug_type` from PHP 8.0 polyfill is used
- the function `array_is_list` from PHP 8.1 polyfill is used
The benchmark sub-project requires PHP 8.1, I disable the installation of this polyfills.
=> PHP 7.3 polyfill is not necessary because PHP 7.4 is required

benchmark/composer.json, benchmark/src/DriverBench/Amp/ExportFileTask.php, benchmark/src/DriverBench/Amp/ImportFileTask.php, benchmark/src/DriverBench/BSONMicroBench.php, benchmark/src/DriverBench/ParallelMultiFileExportBench.php, benchmark/src/DriverBench/ParallelMultiFileImportBench.php
Fix [PHPLIB-1237](https://jira.mongodb.org/browse/PHPLIB-1237)
Follows https://github.com/mongodb/mongo-php-library/pull/1166
Parallel Benchmarks specs: [LDJSON multi-file export](https://github.com/mongodb/specifications/blob/e09b41df206f9efaa36ba4c332c47d04ddb7d6d1/source/benchmarking/benchmarking.rst#ldjson-multi-file-export)
Upgrade to AMPHP with Fibers.
Implementations:
- 🥇 Using multiple forked threads
- 🥈 Using `amphp/parallel` with worker pool
- 🥉 Using a single process 
The scenario have 3 critical steps that I tried to optimize:
I grouped files by chunks to perform a single query for several files and reduce server round trips.
I had to use `limit`/`skip` to paginate on results. I tried an aggregation pipeline to get the first ID of each chunk, but it takes ~600ms, which is too …
=> PHPLIB-1237 Implement Parallel Multi File Export Bench

examples/atlas-search.php, tests/ExamplesTest.php
Fix [PHPLIB-1247](https://jira.mongodb.org/browse/PHPLIB-1247)
This operation is not allowed on Atlas and each example takes care of cleaning the server state before creating objects.
=> PHPLIB-1247 Don't drop the database in `ExamplesTest`

tests/LogNonGenuineHostTest.php
https://jira.mongodb.org/browse/PHPLIB-1194
Depends on https://github.com/mongodb/mongo-php-library/pull/1158
=> PHPLIB-1194: Test log message for non-genuine hosts

src/functions.php
https://jira.mongodb.org/browse/PHPLIB-1137
This was missed in 88731a55c3dfd97b38ce0360f53b5b2674209754
=> PHPLIB-1137: Mark is_document() as internal

src/Client.php, src/Collection.php, src/Database.php, src/functions.php, tests/Functions/SelectServerFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-476
This also refactors the conditionals in extract_session_from_options and extract_read_preference_from_options to improve readability.
select_server() previously did not consider the read preference of an active transaction. This isn't very significant, as transactions require a primary read preference, but it is correct to do so.
=> PHPLIB-476: Consider transaction readPreference in select_server

src/Codec/architecture.md
The classes documented here were subsequently removed, so we shouldn't document them.
=> Remove obsolete codec documentation

.evergreen/config.yml, .evergreen/config/test-tasks.yml
Follow-Up to PHPLIB-1260.
The default `exec_timeout_secs` of 10 minutes is too short, as sharded tests run significantly longer. 20 minutes seem more appropriate before killing tasks. In addition to that, the Atlas and Serverless tests already run close to 20 minutes, so those tasks get a 30 minute timeout.
=> Increase task timeouts

.evergreen/config/functions.yml, .evergreen/config/php.ini, .evergreen/config/test-tasks.yml, .evergreen/config/test-variants.yml, benchmark/phpbench.json.dist, benchmark/src/BSON/DocumentBench.php, benchmark/src/BSON/PackedArrayBench.php, benchmark/src/DriverBench/ParallelMultiFileExportBench.php, benchmark/src/DriverBench/ParallelMultiFileImportBench.php, benchmark/src/DriverBench/SingleDocBench.php, benchmark/src/Extension/EvergreenReport.php, benchmark/src/Extension/MongoDBExtension.php
PHPLIB-1187
This pull request adds a task to run benchmarks on Evergreen. It also uses `perf.send` to store benchmark metrics in CI so we can analyse the performance.
I've also removed a couple of benchmarks in order to bring the benchmark time down. Most recent tests show a 33 minute runtime on Evergreen. I also had to skip the AMP subjects as I ran into issues with socket creation. Since AMP does not perform significantly different from forking, I think it's safe to exclude them from the metrics we collect on Evergreen.
=> PHPLIB-1187: Run benchmark on Evergreen

docs/reference.txt
https://jira.mongodb.org/browse/PHPLIB-1277
Not going to bother back-porting this, as it wasn't requested in the JIRA ticket and honestly isn't worth the trouble of coordinating deploys for old branches.
=> PHPLIB-1277: Rename "Reference" to "API Documentation"

src/Operation/ListSearchIndexes.php, tests/Operation/ListSearchIndexesTest.php
Fix PHPLIB-1305
It's definitely not a place where I would expect a codec to be used, but why not.
I don't think we need to test all the options.
=> PHPLIB-1305 Support "codec" option in listSearchIndexes()

docs/includes/apiargs-function-add_logger-param.yaml, docs/includes/apiargs-function-remove_logger-param.yaml, docs/reference/function/add_logger.txt, docs/reference/function/remove_logger.txt, docs/reference/functions.txt
https://jira.mongodb.org/browse/PHPLIB-1243
=> PHPLIB-1243: Document add/remove logger functions

tests/Operation/AggregateFunctionalTest.php, tests/Operation/ExplainFunctionalTest.php
Once again, the latest server versions broke explain tests. This commit is yet another attempt at hardening the checks, short of removing the test altogether.
=> Harden explain tests

CHANGELOG.md, docs/includes/apiargs-MongoDBClient-method-addSubscriber-param.yaml, docs/includes/apiargs-MongoDBClient-method-removeSubscriber-param.yaml, docs/reference/class/MongoDBClient.txt, docs/reference/method/MongoDBClient-addSubscriber.txt, docs/reference/method/MongoDBClient-removeSubscriber.txt, examples/command_logger.php, src/Client.php, tests/ClientFunctionalTest.php
Fix PHPLIB-1309
This need emerged while working on the MongoDB profiler for Symfony using monitoring features. Chaining method calls isn't possible in Symfony DI configuration. You have to use a "configurator".
I made the methods final so that we can change the signature in the future if necessary.
=> PHPLIB-1309 Add addSubscriber/removeSubscriber to Client class to ease configuration

docs/examples/codecs/handling-data-types/Person.php, docs/tutorial/codecs.txt
As is, the example would cause a type error. Thanks @OskarStark for bringing this to our attention!
=> Fix wrong data type in codec tutorial

psalm-baseline.xml, src/Model/CollectionInfo.php, src/Model/DatabaseInfo.php, src/Model/IndexInfo.php, src/PsrLogAdapter.php
PHPLIB-1315
Some of the errors have been fixed. Additional errors in `PsrLogAdapter` have been added to the baseline pending the merge of new signatures in the psalm call map (see https://github.com/vimeo/psalm/pull/10402).
=> PHPLIB-1315: Fix psalm errors

.evergreen/config/functions.yml, .evergreen/config/test-variants.yml
PHPLIB-1304
ADL tests have been scheduled as part of the PR patch on Evergreen.
=> PHPLIB-1304: Pull mongohouse image from ECR repo

psalm-baseline.xml, src/Model/BSONDocument.php
This fixes a couple of errors that appeared due to a psalm update which updated the PHPC method signatures.
=> Fix psalm errors

docs/reference/class/MongoDBGridFSBucket.txt, docs/reference/method/MongoDBGridFSBucket-registerGlobalStreamWrapperAlias.txt, examples/gridfs-stream-wrapper.php, psalm-baseline.xml, src/GridFS/Bucket.php, src/GridFS/Exception/LogicException.php, src/GridFS/StreamWrapper.php, tests/ExamplesTest.php, tests/GridFS/BucketFunctionalTest.php, tests/GridFS/StreamWrapperFunctionalTest.php
Fix [PHPLIB-1206](https://jira.mongodb.org/browse/PHPLIB-1206)
Fix https://github.com/mongodb/mongo-php-library/issues/1137
Allows to register an alias for the stream wrapper. File urls looks like:
```
gridfs://<bucket-alias>/<filename>
```
Where `<bucket-alias>` is an alias for the bucket
```php
$client = new Client();
$bucket = $client->selectDatabase('test_db')->selectGridFSBucket();
$bucket->registerGlobalStreamWrapperAlias('mybucket');
file_put_contents("gridfs://mybucket/filename.txt", 'Hello GridFS!');
if (file_exists("gridfs://mybucket/filename.txt")) {
echo file_get_contents("gridfs://mybucket/filename.txt") . PHP_EOL;
}
```
Todo:
=> PHPLIB-1206 Allow global registration of GridFS buckets with `gridfs://` protocol

docs/reference/method/MongoDBDatabase-selectGridFSBucket.txt, docs/reference/method/MongoDBGridFSBucket-openUploadStream.txt, docs/reference/method/MongoDBGridFSBucket-uploadFromStream.txt, docs/reference/method/MongoDBGridFSBucket__construct.txt, src/GridFS/Bucket.php
=> PHPLIB-1325 Deprecate setting `disableMD5` to `false` when using GridFS

docs/reference/method/MongoDBGridFSBucket-registerGlobalStreamWrapperAlias.txt, phpcs.xml.dist, src/GridFS/CollectionWrapper.php, src/GridFS/Exception/LogicException.php, src/GridFS/ReadableStream.php, src/GridFS/StreamWrapper.php, tests/GridFS/StreamWrapperFunctionalTest.php
Fix PHPLIB-1324
Rename all the revisions as [defined in the spec](https://github.com/mongodb/specifications/blob/0b47194538aa817978fae0f77f684f6d5e62ebab/source/gridfs/gridfs-spec.rst#renaming-stored-files)
> To rename multiple revisions of the same filename, users must retrieve the full list of files collection documents for a given filename and execute “rename” on each corresponding “_id”.
```php
file_put_contents('gridfs://bucket/filename', 'Hello, GridFS!');
rename('gridfs://bucket/filename', 'gridfs://bucket/newname');
echo file_get_contents('gridfs://bucket/newname');
```
=> PHPLIB-1324 Implement `rename` for GridFS stream wrapper 

composer.json
Fix PHPLIB-1331
rector 0.18.* is incompatible with phpstan 1.10.55
=> PHPLIB-1331 Upgrade to rector 0.19 to fix phpstan/phpstan incompatibility

docs/reference/method/MongoDBGridFSBucket-registerGlobalStreamWrapperAlias.txt, psalm-baseline.xml, src/GridFS/CollectionWrapper.php, src/GridFS/Exception/FileNotFoundException.php, src/GridFS/ReadableStream.php, src/GridFS/StreamWrapper.php, src/GridFS/WritableStream.php, tests/GridFS/StreamWrapperFunctionalTest.php
Fix PHPLIB-1323
This is not optimized as it creates a `WritableStream` instance that is not really used.
The context resolver mechanism introduces in #1138 doesn't give direct access to the `CollectionWrapper` which is required for this feature.
=> PHPLIB-1323 Implement `unlink` for GridFS stream wrapper

.evergreen/config/functions.yml, .evergreen/config/test-variants.yml, tests/SpecTests/ClientSideEncryptionSpecTest.php, tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/index-management/createSearchIndex.json, tests/UnifiedSpecTests/index-management/createSearchIndexes.json, tests/UnifiedSpecTests/index-management/dropSearchIndex.json, tests/UnifiedSpecTests/index-management/listSearchIndexes.json, tests/UnifiedSpecTests/index-management/searchIndexIgnoresReadWriteConcern.json, tests/UnifiedSpecTests/index-management/updateSearchIndex.json
This PR takes care of a number of test failures:
* no-aws-cred tests were failing due to exception class changing. Instead of the expected `AuthenticationException`, it now throws an `EncryptionException`. I don't think the exception class matters for the tests (as the spec only suggests checking for failures, not a specific failure), but I can take a closer look at the reason for the change if necessary.
* PHPLIB-1327: Index management tests fail on latest due to recent changes. This PR syncs the tests with mongodb/specifications@e54cb7c3da226cb14285a14fa7219cdc5c8ed997.
* PHPLIB-1304: changes for ADL tests were only merged to the main branch, I backported these changes to v1.17 to avoid the system failure. Tests still fail however as we can't connect to the local ADL instance. This is a …
=> Fix CI issues

psalm.xml.dist, src/ChangeStream.php, src/Operation/Count.php, src/Operation/Distinct.php
Fix PHPLIB-1372
The new [RiskyTruthyFalsyComparison](https://psalm.dev/docs/running_psalm/issues/RiskyTruthyFalsyComparison/) errors are introduced by psalm [5.20.0](https://github.com/vimeo/psalm/releases/tag/5.20.0).
- Disable on example files. Using `getenv('MONGODB_URI') ?: 'mongodb://127.0.0.1/'` is safe as any falsy value could be replaced by the default URI.
- Replace `!empty($filter)` by `$filter !== []` as `$filter` is an array or an object, and even `empty(new stdClass)` is true. This might be a necessary bug fix.
=> PHPLIB-1372 Fix `RiskyTruthyFalsyComparison`

psalm-baseline.xml, psalm.xml.dist
Same as #1218 for branch v1.17.
I don't backport the code fixes to not introduce behavior change in a bugfix release. Adding the errors to the psalm-baseline instead.
Follows @jmikola comment: https://github.com/mongodb/mongo-php-library/pull/1201#issuecomment-1910698984
=> Add `RiskyTruthyFalsyComparison` psalm errors to the baseline for maintenance branch

docs/reference/method/MongoDBCollection-createSearchIndexes.txt
https://jira.mongodb.org/browse/PHPLIB-1321
I opted not to pull in a more complex example from https://www.mongodb.com/docs/atlas/atlas-search/define-field-mappings that creates multiple indexes at once, since we already link to that page. Demonstrating the argument and return type difference seems sufficient.
=> PHPLIB-1321: Use correct method in createSearchIndexes() example

tests/SpecTests/TransactionsSpecTest.php
PHPLIB-1330 pulled in a new test file that was extracted for compatibility with different runOnRequirements. The pull request in question however broke load-balanced tests as it didn't rename the incomplete test.
We currently don't run load-balanced tests in pull request - is that something we should add?
=> PHPLIB-1330: Update skipped test list to account for moved test

docs/tutorial/crud.txt, docs/tutorial/modeling-bson-data.txt
Fix the RST formatting for seealso admonitions in the docs.
JIRA: https://jira.mongodb.org/browse/DOCSP-36898
Staging:
- [CRUD](https://preview-mongodbcchomongodb.gatsbyjs.io/php-library/DOCSP-36898-fix-seealso-admonition/tutorial/crud/)
- [Modeling BSON Data](https://preview-mongodbcchomongodb.gatsbyjs.io/php-library/DOCSP-36898-fix-seealso-admonition/tutorial/modeling-bson-data/)
- [In-Use Encryption](https://preview-mongodbcchomongodb.gatsbyjs.io/php-library/DOCSP-36898-fix-seealso-admonition/tutorial/encryption/)
=> DOCSP-36898: fix seealso admonition formatting

.github/workflows/coding-standards.yml, .github/workflows/static-analysis.yml
Since coding-standards and psalm are required through branch protection rules, skipping them for docs-only PRs results in an unmergeable pull request. This PR undoes those changes. Note that phpunit checks in GitHub Actions are still skipped, as those are not required in the rules.
=> Don't skip static checks for docs changes

docs/includes/extracts-note.yaml, docs/reference/method/MongoDBClient__construct.txt, docs/tutorial/collation.txt, docs/tutorial/decimal128.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37038
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-37038/
=> DOCSP-37038: Fix broken links

tests/UnifiedSpecTests/CollectionData.php, tests/UnifiedSpecTests/Context.php, tests/UnifiedSpecTests/UnifiedTestRunner.php
https://jira.mongodb.org/browse/PHPLIB-1400
POC for https://github.com/mongodb/specifications/pull/1523
Patch build: https://spruce.mongodb.com/version/65d63c500305b9dcd65fa961/tasks
=> PHPLIB-1400: Work around MigrationConflict errors on sharded clusters

tests/UnifiedSpecTests/CollectionData.php
https://jira.mongodb.org/browse/PHPLIB-1400
Fixes an issue from https://github.com/mongodb/mongo-php-library/pull/1232
Patch build: https://spruce.mongodb.com/version/65d8d2b72a60edef51646df4/tasks
=> PHPLIB-1400: Add missing use statement

.evergreen/config/functions.yml
This fixes the serverless build after the credentials were rotated.
Note: the change to use subprocess.exec instead of shell.exec is not related to the original issue, but it's recommended by the evergreen team.
=> Use secrets manager to read serverless credentials

docs/reference/method/MongoDBCollection-explain.txt, docs/reference/method/MongoDBUpdateResult-getMatchedCount.txt, docs/tutorial/tailable-cursor.txt, docs/upgrade.txt
Additional fixes for #1239 
JIRA - https://jira.mongodb.org/browse/DOCSP-36627
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-36627-more-slash-fixes/
=> DOCSP-36627: More backslash fixes

tests/UnifiedSpecTests/UnifiedSpecTest.php, tests/UnifiedSpecTests/retryable-reads/exceededTimeLimit.json, tests/UnifiedSpecTests/retryable-reads/handshakeError.json, tests/UnifiedSpecTests/retryable-reads/readConcernMajorityNotAvailableYet.json
https://jira.mongodb.org/browse/PHPLIB-1294
https://jira.mongodb.org/browse/PHPLIB-1295
Tests for ExceededTimeLimit and ReadConcernMajorityNotAvailableYet as retryable errors. Handshake tests are skipped pending libmongoc functionality.
Synced with mongodb/specifications@a0bac5c874786d49cb6a3647182a9955fd2be94a
=> PHPLIB-1294 and PHPLIB-1295: Sync retryable reads unified tests

.github/workflows/merge-up.yml
Similar to the [corresponding change in laravel-mongodb](https://github.com/mongodb/laravel-mongodb/pull/2748), this new workflow ensures that changes pushed to older branches are merged up to newer branches.
=> Add GitHub Actions workflow to create merge-up pull requests

src/GridFS/ReadableStream.php, src/Model/SearchIndexInput.php
Fixes some phpcs errors that popped up in https://github.com/mongodb/mongo-php-library/pull/1250. I assume this was related to some upstream change, since the code is quite old.
=> Remove redundant annotations

tests/UnifiedSpecTests/UnifiedSpecTest.php
Previously we were fine running all unified tests on serverless, but the read-write-concern tests fail and are not required to be tested. I've moved the `@group` annotation to all individual tests and only included the read-write-concern tests.
=> Exclude read-write-concern tests from serverless testing

tests/UnifiedSpecTests/read-write-concern/default-write-concern-3.4.json
https://jira.mongodb.org/browse/PHPLIB-1409
Complements #1253, although that PR can be left as-is to exclude running these tests on serverless. This PR's Evergreen build will confirm that the modified tests play nice with serverless.
POC for https://github.com/mongodb/specifications/pull/1550
Patch build: https://spruce.mongodb.com/version/65f1b98a7d9e260007b65496/tasks
=> PHPLIB-1409: Skip $out and mapReduce tests on serverless

.github/workflows/tests.yml
https://jira.mongodb.org/browse/PHPLIB-1413
env vars are not available in jobs.<job_id>.strategy.matrix. Since the driver-version never changes for jobs, reference the common env var in step configs.
=> PHPLIB-1413: Use env instead of matrix for driver-version

src/Collection.php, tests/Collection/CollectionFunctionalTest.php
https://jira.mongodb.org/browse/PHPLIB-1320
Adds test coverage for "comment" and "commitQuorum" options.
=> PHPLIB-1320: Support "comment" command option in Collection::createIndex()

composer.json, src/Client.php
https://jira.mongodb.org/browse/PHPLIB-1302
There is no impact on Composer requirements since jean85/pretty-package-versions 2.0+ previously required composer-runtime-api 2.0+.
=> PHPLIB-1302: Use Composer\InstalledVersions

docs/tutorial/client-side-encryption.txt
https://jira.mongodb.org/browse/DOCSP-36898
This was missed in https://github.com/mongodb/mongo-php-library/pull/1230
=> DOCSP-36898: Fix seealso syntax in CSFLE tutorial

.evergreen/compile-extension.sh, .evergreen/config/functions.yml, .evergreen/install-composer.sh, .evergreen/install-dependencies.sh, .evergreen/run-tests.sh
https://jira.mongodb.org/browse/PHPLIB-1410
Complete patch build: https://spruce.mongodb.com/version/65fd95a8ff9ec9000770f3b3/tasks
=> PHPLIB-1410: Invoke drivers-evergreen-tools scripts with bash

docs/includes/extracts-bucket-option.yaml, docs/includes/extracts-collection-option.yaml, docs/includes/extracts-common-option.yaml, docs/reference/method/MongoDBClient-selectCollection.txt, docs/reference/method/MongoDBClient-watch.txt, docs/reference/method/MongoDBCollection-aggregate.txt, docs/reference/method/MongoDBCollection-bulkWrite.txt, docs/reference/method/MongoDBCollection-find.txt, docs/reference/method/MongoDBCollection-findOne.txt, docs/reference/method/MongoDBCollection-findOneAndReplace.txt, docs/reference/method/MongoDBCollection-insertMany.txt, docs/reference/method/MongoDBCollection-insertOne.txt, docs/reference/method/MongoDBCollection-listSearchIndexes.txt, docs/reference/method/MongoDBCollection-replaceOne.txt, docs/reference/method/MongoDBCollection-watch.txt, docs/reference/method/MongoDBCollection-withOptions.txt, docs/reference/method/MongoDBCollection__construct.txt, docs/reference/method/MongoDBDatabase-aggregate.txt, docs/reference/method/MongoDBDatabase-selectCollection.txt, docs/reference/method/MongoDBDatabase-selectGridFSBucket.txt, docs/reference/method/MongoDBDatabase-watch.txt, docs/reference/method/MongoDBGridFSBucket-find.txt, docs/reference/method/MongoDBGridFSBucket-findOne.txt, docs/reference/method/MongoDBGridFSBucket__construct.txt, src/GridFS/Bucket.php
https://jira.mongodb.org/browse/PHPLIB-1322
=> PHPLIB-1322: Document codec option for classes and operations

src/functions.php, tests/UnifiedSpecTests/Constraint/Matches.php, tests/UnifiedSpecTests/UnifiedTestRunner.php
We use symfony/php80-polyfill that provides `str_starts_with`, `str_ends_with` and `str_contains`.
=> Leverage PHP 8.0 string functions

tests/UnifiedSpecTests/command-monitoring/unacknowledgedBulkWrite.json
https://jira.mongodb.org/browse/PHPLIB-1424
Synced with mongodb/specifications@cd08b7248eb4e3ab901a8f7905874da41b908f7c
This PR supersedes https://github.com/mongodb/mongo-php-library/pull/1275
=> PHPLIB-1424: Fix potentially racy w:0 unified tests

RELEASING.md, composer.json
This will make the release process a bit simpler.
`branch-alias: 1.x-dev` only applies to the `master` branch only, regardless of the branch on which it is committed. This is always the lastest dev version.
=> Relax `branch-alias` on `dev-master` to avoid update on each release

sbom.json
PHPLIB-1447
Since we don't have any bundled dependencies, we can add an empty SBOM file
=> PHPLIB-1447: Add SBOM lite

docs/includes/extracts-option-requires.yaml, docs/reference.txt, docs/reference/method/MongoDBCollection-bulkWrite.txt, docs/reference/method/MongoDBCollection-dropIndex.txt, docs/reference/method/MongoDBCollection-dropIndexes.txt, docs/reference/method/MongoDBCollection-explain.txt, docs/reference/method/MongoDBCollection-findOneAndUpdate.txt, docs/reference/method/MongoDBCollection-updateMany.txt, docs/reference/method/MongoDBCollection-updateOne.txt, docs/reference/method/MongoDBDatabase-createCollection.txt, docs/reference/result-classes.txt, docs/tutorial/gridfs.txt
=> DOCSP-37027: Fix 1.16 build errors (#1290)

docs/tutorial/encryption.txt
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-37027-more-fixes/tutorial/encryption/
Build log - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663e48d0b67dbf804ac1978b
=> DOCSP-37027: Additional 1.17 build fixes

.github/actions/setup/action.yml, .github/workflows/coding-standards.yml, .github/workflows/static-analysis.yml, .github/workflows/tests.yml, composer.json
PHPLIB-1435
This extracts a commit from #1288 to get code scanning integrated before we automate releases.
=> PHPLIB-1435: Integrate static analysis for releases

.evergreen/config/generated/build/build-php-7.4.yml, .evergreen/config/generated/build/build-php-8.0.yml, .evergreen/config/generated/build/build-php-8.1.yml, .evergreen/config/generated/build/build-php-8.2.yml, .evergreen/config/generated/build/build-php-8.3.yml, .evergreen/config/templates/build/build-extension.yml, composer.json, tests/UnifiedSpecTests/EventObserver.php, tests/UnifiedSpecTests/UnifiedTestRunner.php
https://jira.mongodb.org/browse/PHPLIB-1080
=> PHPLIB-1080: Spec tests for command events databaseName property

docs/tutorial/decimal128.txt
Merges up https://github.com/mongodb/mongo-php-library/pull/1312.
Supersedes https://github.com/mongodb/mongo-php-library/pull/1313, since we needed to resolve a merge conflict.
=> Merge v1.16 into v1.17

.github/workflows/release.yml, README.md
PHPLIB-583 (Release process automation)
PHPLIB-584 (Signing releases)
PHPLIB-1435 (Running static analysis for tags)
This PR builds on the work done for the MongoDB extension. It uses the same flow to trigger a release, but there is no packaging step involved. Since we don't have a file to track the version, this workflow runs different consistency checks: it ensures that the version being released doesn't exist yet, and that it is created from the correct branch (i.e. version `X.Y.Z` has to be released from the `vX.Y` branch). The tag created for the release is signed with the same key that we use for the PHP extension.
The static analysis workflow has been changed to also run for tags. The resulting SARIF report is uploaded to GitHub's Code Scanning feature where we can then handle it …
=> PHPLIB-583: Automate release process

.github/workflows/release.yml
With significant changes being introduced to the release tooling in the shared repository, we should rely on a tagged version of those release tools.
=> Use stable version of release tooling

.github/workflows/release.yml
Reverts mongodb/mongo-php-library#1332. v2 uses a different setup process to fetch credentials which wouldn't work with our setup. I'll be migrating to v2 separately and have created PHPLIB-1462 to track this.
=> Revert "Bump mongodb-labs/drivers-github-tools from 1 to 2"

phpcs.xml.dist, tests/Comparator/ServerComparator.php, tests/SpecTests/RetryableReads/Prose2_RetryOnMongosTest.php, tests/SpecTests/RetryableWrites/Prose3_ReturnOriginalErrorTest.php, tests/SpecTests/RetryableWrites/Prose4_RetryOnDifferentMongosTest.php, tests/SpecTests/RetryableWrites/Prose5_RetryOnSameMongosTest.php, tests/bootstrap.php
https://jira.mongodb.org/browse/PHPLIB-1459
=> PHPLIB-1459: Retryable read/write prose tests for mongos selection

tests/UnifiedSpecTests/command-monitoring/unacknowledgedBulkWrite.json
https://jira.mongodb.org/browse/PHPLIB-1461
POC for https://github.com/mongodb/specifications/pull/1595
=> PHPLIB-1461: Use single mongos in unacknowledgedBulkWrite command monitoring test

.github/workflows/release.yml
PHPLIB-1462
Same story as with https://github.com/mongodb/mongo-php-driver/pull/1573 - environment and credentials are already prepared, releases before 1.18 are no longer possible (but also and not needed).
=> PHPLIB-1462: update to drivers-github-tools v2

docs/faq.txt, docs/includes/extracts-error.yaml, docs/includes/extracts-note.yaml, docs/index.txt, docs/reference/bson.txt, docs/reference/class/MongoDBClient.txt, docs/reference/class/MongoDBCollection.txt, docs/reference/class/MongoDBDatabase.txt, docs/reference/class/MongoDBGridFSBucket.txt, docs/reference/exception-classes.txt, docs/reference/function/add_logger.txt, docs/reference/function/remove_logger.txt, docs/reference/method/MongoDBDatabase__construct.txt, docs/reference/method/MongoDBGridFSBucket__construct.txt, docs/tutorial/commands.txt, docs/tutorial/custom-types.txt, docs/tutorial/decimal128.txt, docs/tutorial/encryption.txt, docs/tutorial/example-data.txt, docs/tutorial/install-php-library.txt, docs/tutorial/modeling-bson-data.txt, docs/tutorial/server-selection.txt, docs/upgrade.txt
https://jira.mongodb.org/browse/PHPLIB-1279
https://jira.mongodb.org/browse/PHPLIB-1466
This updates references where we're discussing something specific to the extension. I've left "driver" in place for more general discussion about the PHP driver or for special topics such as "driver options" on Manager and Client objects.
I've targeted v1.17 for this as it's the oldest branch that doesn't conflict. I think it'd be reasonable to drop v1.16 entirely from https://www.mongodb.com/docs/php-library/current/ since we've had new releases following the original Giza -> Snooty port.
=> PHPLIB-1279: Revise driver/extension terminology

.github/workflows/release.yml
This PR makes use of the `secure-checkout` and `tag-version` actions from drivers-github-tools to reduce the amount of logic in our release workflow.
=> Use checkout and tag actions from drivers-github-tools

.github/workflows/release.yml, .github/workflows/static-analysis.yml
There are two changes here:
- When invoking the static analysis job from the release job, the `github.ref` variable is set to the branch that the release workflow was triggered in. This is changed to the tag reference we just created.
- The code scanning export action was invoked with the same `github.ref`, which was also changed to using the ref of the newly created tag.
=> Fix refs used for code scanning results

.github/workflows/release.yml
This PR leverages the new [full-report action](https://github.com/mongodb-labs/drivers-github-tools?tab=readme-ov-file#full-report) to generate all necessary SSDLC reports.
=> Use full-report convenience action for SSDLC reports

.evergreen/config.yml, .evergreen/config/build-variants.yml
This PR makes some adjustments to what we test in pull requests and tags:
- All "build" variants are run for tags
-  "build" variants on x64 platforms are run for pull requests
- Only run tasks tagged "pr" on pull requests for PHP 8
=> Test all builds in pull requests and tags

tests/SpecTests/client-side-encryption/tests/azureKMS.json, tests/SpecTests/client-side-encryption/tests/gcpKMS.json, tests/SpecTests/client-side-encryption/tests/kmipKMS.json, tests/SpecTests/client-side-encryption/tests/timeoutMS.json, tests/UnifiedSpecTests/client-side-encryption/createDataKey.json, tests/UnifiedSpecTests/client-side-encryption/rewrapManyDataKey.json
PHPLIB-1375
I also included the changes for PHPLIB-1401, which make no difference as both test are skipped as we don't implement CSOT.
The patch definition for this pull request includes CSFLE tests with mongocryptd and crypt_shared for all supported server versions.
=> PHPLIB-1375: Test KMIP "delegated" protocol

docs/tutorial/custom-types.txt, docs/tutorial/example-data.txt, examples/aggregate.php, examples/bulk.php, examples/changestream.php, examples/command_logger.php, examples/sdam_logger.php, examples/with_transaction.php, psalm-baseline.xml, src/GridFS/Bucket.php, src/GridFS/Exception/FileNotFoundException.php, src/GridFS/Exception/StreamException.php, src/Model/BSONIterator.php, src/functions.php, tests/Model/BSONIteratorTest.php, tests/SpecTests/DocumentsMatchConstraintTest.php, tests/SpecTests/FunctionalTestCase.php, tests/TestCase.php, tests/UnifiedSpecTests/Constraint/IsBsonTypeTest.php, tests/UnifiedSpecTests/UnifiedTestCase.php
This fixes a number of failures due to unexpected deprecation messages after these methods were deprecated in PHPC 1.20
=> Remove usage of deprecated BSON functions

docs/index.txt, docs/whats-new.txt
adds whats new page and information about server support removal
https://jira.mongodb.org/browse/DOCSP-41495
staging - https://preview-mongodbrustagir.gatsbyjs.io/php-library/DOCSP-41495-php-server-eol/whats-new/
=> DOCSP-41495: php v1.20 compat updates

tests/UnifiedSpecTests/load-balancers/sdam-error-handling.json
Fix PHPLIB-1444
Sync https://github.com/mongodb/specifications/commit/a35de873621a244b88cad01aa3cd7c8da31a5ecd
Skipped this files, because they are missing:
```
source/client-side-operations-timeout/tests/command-execution.json
source/server-discovery-and-monitoring/tests/unified/hello-command-error.json
source/server-discovery-and-monitoring/tests/unified/hello-network-error.json
source/server-discovery-and-monitoring/tests/unified/interruptInUse-pool-clear.json
source/server-discovery-and-monitoring/tests/unified/minPoolSize-error.json
```
=> PHPLIB-1444 Unskip failCommand+appName tests on MongoDB 4.4.7+

psalm-baseline.xml, src/ChangeStream.php, src/Model/CodecCursor.php, tests/Model/CodecCursorFunctionalTest.php
PHPLIB-1489
This PR complements https://github.com/mongodb/mongo-php-driver/pull/1616 by introducing the same `$asInt64` argument to all classes that implement `CursorInterface::getId` or wrap a cursor class. Not providing the argument or providing `false` as a value will trigger a deprecation warning to inform the user they need to update. In 2.0, we can deprecate the parameter and change the return type of the methods to `Int64`.
=> PHPLIB-1489: Handle CursorId deprecations

.evergreen/config/generated/build/build-extension.yml, .evergreen/config/templates/build/build-extension.yml, .github/workflows/coding-standards.yml, .github/workflows/static-analysis.yml, .github/workflows/tests.yml
When https://github.com/mongodb/mongo-php-driver/pull/1631 is merged to master, builds on PHP 7.4 and 8.0 will fail. This PR changes the PHPC branch to 1.20 until a stable release of 1.20 is available so the build keeps working.
Note: CSFLE failures will be fixed by #1373.
=> Test with 1.20 branch in CI

psalm-baseline.xml, src/Collection.php, src/Model/SearchIndexInput.php, tests/Model/SearchIndexInputTest.php, tests/Operation/CreateSearchIndexesTest.php, tests/UnifiedSpecTests/Operation.php, tests/UnifiedSpecTests/index-management/createSearchIndex.json, tests/UnifiedSpecTests/index-management/createSearchIndexes.json, tests/UnifiedSpecTests/index-management/searchIndexIgnoresReadWriteConcern.json
https://jira.mongodb.org/browse/PHPLIB-1394
=> PHPLIB-1394: Support "type" option for createSearchIndex(es)
